include-file = ~/.config/polybar/catppuccin.ini

[bar/main]
monitor = ${env:MONITOR:Virtual1}
width = 100%
height = 30 
offset-x = 0
offset-y = 0
radius = 0
fixed-center = true
bottom = false
enable-ipc = true

background = ${colors.base}
foreground = ${colors.text}

line-size = 0
line-color = ${colors.base}

border-size = 0
border-color = ${colors.base}

padding-left = 2
padding-right = 3
padding-top= 5

module-margin-left = 2
module-margin-right = 2

font-0 = Ubuntu:style=Bold:size=11;2
font-1 = Symbols Nerd Font:style=Solid:pixelsize=15;3
font-2 = Symbols Nerd Font:style=Regular:pixelsize=20;3
font-3 = Symbols Nerd Font:style=Regular:pixelsize=17;5
font-4 = Ubuntu:style=Bold:size=11;3
font-5 = Ubuntu:style=Bold:size=15;2

modules-left    = time date
modules-center  = ewmh
modules-right   = cpu memory pulseaudio battery powermenu

override-redirect = true

cursor-click = pointer
cursor-scroll = default

tray-position = right
tray-detached = false
tray-background = ${colors.base}
tray-foreground = ${colors.text}
tray-maxsize = 20
tray-offset-x = 5
tray-offset-y = 0
tray-padding = 1
tray-scale = 1.0

[bar/left]
monitor = ${env:MONITOR:DP-1}
width = 94.5%
height = 40 
offset-x = 2.75%
offset-y = 0.5%
radius = 3
fixed-center = true
bottom = false

background = ${colors.base}
foreground = ${colors.text}

line-size = 0
line-color = ${colors.base}

border-size = 0
border-color = ${colors.base}

padding-left = 0
padding-right = 2

module-margin-left = 2
module-margin-right = 2

font-0 = Terminus:style=Regular:size=16;2
font-1 = Font Awesome 6 Free:style=Solid:pixelsize=15;3
font-2 = Font Awesome 6 Brands:style=Regular:pixelsize=15;3
font-3 = Material Design Icons:style=Regular:pixelsize=17;5
font-4 = Sugar Snow:style=Regular:size=12,2

modules-left    = 
modules-center  = ewmh
modules-right   = 

override-redirect = true 

cursor-click = pointer
cursor-scroll = default

[module/network]
type = internal/network
interface = ${env:DEFAULT_NETWORK_INTERFACE}
interval = 5.0

format-connected =  %{T1}<label-connected>%{T-} 

format-disconnected = <label-disconnected>

format-connected-foreground = ${colors.green}

label-connected = %downspeed%
label-connected-foreground = ${colors.text} 


label-disconnected =  
label-disconnected-foreground = ${colors.red}

margin = 0

[module/pulseaudio]
type = internal/pulseaudio
label-font = 3
format-volume =<ramp-volume> <label-volume>
label-volume = %percentage:2:3%%
format-volume-foreground = ${colors.blue}
use-ui-max = true
interval = 5
label-volume-foreground = ${colors.text}
ramp-volume-0 = ""
ramp-volume-1 = ""
ramp-volume-2 = ""
label-muted = "婢"
format-muted-foreground = ${colors.red}

[module/cpu]
type = internal/cpu
interval = 5
format-prefix = " "
format-prefix-foreground = ${colors.lavender}
label = %percentage:1%%


[module/powermenu]
type = custom/menu
expand-right = true

menu-0-0 = "Sleep"
menu-0-0-background = ${colors.base}
menu-0-0-exec = systemctl suspend
menu-0-1 = "Reboot"
menu-0-1-background = ${colors.base}
menu-0-1-exec = systemctl reboot
menu-0-2 = "Shutdown"
menu-0-2-background = ${colors.base}
menu-0-2-exec = systemctl poweroff

format = <label-toggle><menu>
format-overline = ${colors.base}
format-underline = ${colors.base}

label-open = 
label-open-background = ${colors.base}
label-open-foreground = ${colors.red}
label-close = 
label-close-background = ${colors.base}
label-close-foreground = ${colors.red}

label-separator = " : "
label-separator-foreground = ${colors.pink}

[module/memory]
type = internal/memory
interval = 5
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.flamingo}
label = %percentage_used:1%%

[module/date]
type = internal/date
interval = 5
format-prefix-foreground = ${colors.blue}
date      = %A, %d %B %Y
format-prefix = ""
label = " %date%"
label-foreground = ${colors.text}

[module/time]
type = internal/date
interval = 5
format-prefix-foreground = ${colors.mauve}
time      = %I:%M %p
format-prefix = ""
label = " %time%"
label-foreground = ${colors.text}

[global/wm]
margin-top = 0
margin-bottom = 0

[module/ewmh]
type = internal/xworkspaces
enable-click = false
enable-scroll = false

icon-0 = one;%{T3}  %{T-}
icon-1 = two;%{T3}  %{T-}
icon-2 = three;%{T3}  %{T-}
icon-3 = four;%{T3}  %{T-}
icon-4 = five;%{T3}  %{T-}
icon-5 = NSP;

format = <label-state>
label-active = %icon% 
label-occupied = %icon%
label-empty = %icon%

label-empty-padding = 1
label-active-padding = 1
label-urgent-padding = 1
label-occupied-padding = 1

label-empty-foreground = ${colors.surface2}
label-active-foreground = ${colors.green}
label-urgent-foreground = ${colors.red}
label-occupied-foreground = ${colors.flamingo}

[module/sep]
type = custom/text
content = "    "
content-foreground = ${colors.mauve}
content-offset = -4

[module/logo]
type = custom/text
content = "   "
content-foreground = ${colors.teal}
content-offset = -10

[module/spotify]
type = custom/script
interval = 1
format-prefix = " "
format-prefix-foreground = #1DB954
format = <label>
exec = python ~/.config/polybar/spotify.py -t 80 -f '{artist}: {song}' --font=5
click-left = playerctl --player=spotify play-pause 
click-right = playerctl --player=spotify next 
click-middle = playerctl --player=spotify previous

[module/pacupd]
type = custom/script
exec = paru -Qu | wc -l
click-left = kitty -e "paru"
interval = 900
format-prefix = " "
format-prefix-foreground = ${colors.pink}

[module/xmonad]
type = custom/script
exec = ~/.config/xmonad/xmonad-contrib/scripts/xmonadpropread.hs
tail = true
format-font = 5
format-foreground = ${colors.peach}
format-offset = -20

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 99

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 5

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP1

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = <animation-charging> <label-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = <ramp-capacity> <label-discharging>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
;format-full = <ramp-capacity> <label-full>

; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
;format-low = <label-low> <animation-low>

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging = %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging = %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = Fully charged

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = 

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-5 = 
ramp-capacity-6 = 
ramp-capacity-7 = 
ramp-capacity-8 = 
ramp-capacity-9 = 

; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-5 = 
; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200
