#!/usr/bin/env bash

SPACE_INDEX=$2
CURRENT_SPACE_INDEX="$(/opt/homebrew/bin/aerospace list-workspaces --focused)"

if [ "$SPACE_INDEX" != "$CURRENT_SPACE_INDEX" ];
then
  if [ "$1" == 'focus' ];
  then
    /opt/homebrew/bin/aerospace workspace "$SPACE_INDEX"
  fi

  if [ "$1" == 'move-and-focus' ];
    then
      /opt/homebrew/bin/aerospace move-node-to-workspace "$SPACE_INDEX" && /opt/homebrew/bin/aerospace workspace "$SPACE_INDEX"
    fi
    
  if [ "$1" == 'move' ];
    then
      /opt/homebrew/bin/rerospace move-node-to-workspace "$SPACE_INDEX"
    fi
fi
