-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "gruvbox-material-2.0"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@annotation", { link = "TSAnnotation" })
hi(0, "@attribute", { link = "TSAttribute" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@boolean", { link = "TSBoolean" })
hi(0, "@character", { link = "TSCharacter" })
hi(0, "@character.special", { link = "TSCharacterSpecial" })
hi(0, "@comment", { link = "TSComment" })
hi(0, "@comment.error", { link = "TSDanger" })
hi(0, "@comment.note", { link = "TSNote" })
hi(0, "@comment.todo", { link = "TSTodo" })
hi(0, "@comment.warning", { link = "TSWarning" })
hi(0, "@conceal", { link = "Grey" })
hi(0, "@conditional", { link = "TSConditional" })
hi(0, "@constant", { link = "TSConstant" })
hi(0, "@constant.builtin", { link = "TSConstBuiltin" })
hi(0, "@constant.macro", { link = "TSConstMacro" })
hi(0, "@constructor", { link = "TSConstructor" })
hi(0, "@constructor.lua", { link = "luaTSConstructor" })
hi(0, "@debug", { link = "TSDebug" })
hi(0, "@define", { link = "TSDefine" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "TSError" })
hi(0, "@exception", { link = "TSException" })
hi(0, "@field", { link = "TSField" })
hi(0, "@float", { link = "TSFloat" })
hi(0, "@function", { link = "TSFunction" })
hi(0, "@function.builtin", { link = "TSFuncBuiltin" })
hi(0, "@function.call", { link = "TSFunctionCall" })
hi(0, "@function.macro", { link = "TSFuncMacro" })
hi(0, "@function.method", { link = "TSMethod" })
hi(0, "@function.method.call", { link = "TSMethodCall" })
hi(0, "@include", { link = "TSInclude" })
hi(0, "@keyword", { link = "TSKeyword" })
hi(0, "@keyword.conditional", { link = "TSConditional" })
hi(0, "@keyword.debug", { link = "TSDebug" })
hi(0, "@keyword.directive", { link = "TSPreProc" })
hi(0, "@keyword.directive.define", { link = "TSDefine" })
hi(0, "@keyword.exception", { link = "TSException" })
hi(0, "@keyword.function", { link = "TSKeywordFunction" })
hi(0, "@keyword.import", { link = "TSInclude" })
hi(0, "@keyword.operator", { link = "TSKeywordOperator" })
hi(0, "@keyword.repeat", { link = "TSRepeat" })
hi(0, "@keyword.return", { link = "TSKeywordReturn" })
hi(0, "@keyword.storage", { link = "TSStorageClass" })
hi(0, "@label", { link = "TSLabel" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "TSType" })
hi(0, "@lsp.type.comment", { link = "TSComment" })
hi(0, "@lsp.type.decorator", { link = "TSFunction" })
hi(0, "@lsp.type.enum", { link = "TSType" })
hi(0, "@lsp.type.enumMember", { link = "TSProperty" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.events", { link = "TSLabel" })
hi(0, "@lsp.type.function", { link = "TSFunction" })
hi(0, "@lsp.type.interface", { link = "TSType" })
hi(0, "@lsp.type.keyword", { link = "TSKeyword" })
hi(0, "@lsp.type.macro", { link = "TSConstMacro" })
hi(0, "@lsp.type.method", { link = "TSMethod" })
hi(0, "@lsp.type.modifier", { link = "TSTypeQualifier" })
hi(0, "@lsp.type.namespace", { link = "TSNamespace" })
hi(0, "@lsp.type.number", { link = "TSNumber" })
hi(0, "@lsp.type.operator", { link = "TSOperator" })
hi(0, "@lsp.type.parameter", { link = "TSParameter" })
hi(0, "@lsp.type.property", { link = "TSProperty" })
hi(0, "@lsp.type.regexp", { link = "TSStringRegex" })
hi(0, "@lsp.type.string", { link = "TSString" })
hi(0, "@lsp.type.struct", { link = "TSType" })
hi(0, "@lsp.type.type", { link = "TSType" })
hi(0, "@lsp.type.typeParameter", { link = "TSTypeDefinition" })
hi(0, "@lsp.type.variable", { link = "TSVariable" })
hi(0, "@markup.emphasis", { link = "TSEmphasis" })
hi(0, "@markup.environment", { link = "TSEnvironment" })
hi(0, "@markup.environment.name", { link = "TSEnvironmentName" })
hi(0, "@markup.heading", { link = "TSTitle" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#0f2324", fg = "#1d3139", nocombine = true, sp = "#ebdbb2", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#0f2324", fg = "#1d3139", nocombine = true, sp = "#ebdbb2", underline = true })
hi(0, "@markup.link", { link = "TSTextReference" })
hi(0, "@markup.link.label", { link = "TSStringSpecial" })
hi(0, "@markup.link.url", { link = "TSURI" })
hi(0, "@markup.list", { link = "TSPunctSpecial" })
hi(0, "@markup.list.checked", { link = "Green" })
hi(0, "@markup.list.unchecked", { link = "Ignore" })
hi(0, "@markup.math", { link = "TSMath" })
hi(0, "@markup.note", { link = "TSNote" })
hi(0, "@markup.quote", { link = "Grey" })
hi(0, "@markup.raw", { link = "TSLiteral" })
hi(0, "@markup.strike", { link = "TSStrike" })
hi(0, "@math", { link = "TSMath" })
hi(0, "@method", { link = "TSMethod" })
hi(0, "@method.call", { link = "TSMethodCall" })
hi(0, "@module", { link = "TSNamespace" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { link = "TSNamespace" })
hi(0, "@none", { link = "TSNone" })
hi(0, "@number", { link = "TSNumber" })
hi(0, "@number.float", { link = "TSFloat" })
hi(0, "@operator", { link = "TSOperator" })
hi(0, "@parameter", { link = "TSParameter" })
hi(0, "@parameter.reference", { link = "TSParameterReference" })
hi(0, "@preproc", { link = "TSPreProc" })
hi(0, "@property", { link = "TSProperty" })
hi(0, "@punctuation.bracket", { link = "TSPunctBracket" })
hi(0, "@punctuation.delimiter", { link = "TSPunctDelimiter" })
hi(0, "@punctuation.special", { link = "TSPunctSpecial" })
hi(0, "@repeat", { link = "TSRepeat" })
hi(0, "@storageclass", { link = "TSStorageClass" })
hi(0, "@storageclass.lifetime", { link = "TSStorageClassLifetime" })
hi(0, "@strike", { link = "TSStrike" })
hi(0, "@string", { link = "TSString" })
hi(0, "@string.escape", { link = "TSStringEscape" })
hi(0, "@string.regex", { link = "TSStringRegex" })
hi(0, "@string.regexp", { link = "TSStringRegex" })
hi(0, "@string.special", { link = "TSStringSpecial" })
hi(0, "@string.special.symbol", { link = "TSSymbol" })
hi(0, "@string.special.uri", { link = "TSURI" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@symbol", { link = "TSSymbol" })
hi(0, "@tag", { link = "TSTag" })
hi(0, "@tag.attribute", { link = "TSTagAttribute" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { link = "TSTagDelimiter" })
hi(0, "@text", { link = "TSText" })
hi(0, "@text.danger", { link = "TSDanger" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { link = "TSEmphasis" })
hi(0, "@text.environment", { link = "TSEnvironment" })
hi(0, "@text.environment.name", { link = "TSEnvironmentName" })
hi(0, "@text.literal", { link = "TSLiteral" })
hi(0, "@text.math", { link = "TSMath" })
hi(0, "@text.note", { link = "TSNote" })
hi(0, "@text.reference", { link = "TSTextReference" })
hi(0, "@text.strike", { link = "TSStrike" })
hi(0, "@text.strong", { link = "TSStrong" })
hi(0, "@text.title", { link = "TSTitle" })
hi(0, "@text.todo", { link = "TSTodo" })
hi(0, "@text.todo.checked", { link = "Green" })
hi(0, "@text.todo.unchecked", { link = "Ignore" })
hi(0, "@text.underline", { link = "TSUnderline" })
hi(0, "@text.uri", { link = "TSURI" })
hi(0, "@text.warning", { link = "TSWarning" })
hi(0, "@todo", { link = "TSTodo" })
hi(0, "@type", { link = "TSType" })
hi(0, "@type.builtin", { link = "TSTypeBuiltin" })
hi(0, "@type.definition", { link = "TSTypeDefinition" })
hi(0, "@type.qualifier", { link = "TSTypeQualifier" })
hi(0, "@uri", { link = "TSURI" })
hi(0, "@variable", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "@variable.builtin", { link = "TSVariableBuiltin" })
hi(0, "@variable.member", { link = "TSField" })
hi(0, "@variable.parameter", { link = "TSParameter" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "ALEError", { link = "ErrorText" })
hi(0, "ALEErrorLine", { link = "ErrorLine" })
hi(0, "ALEErrorSign", { link = "RedSign" })
hi(0, "ALEInfo", { link = "InfoText" })
hi(0, "ALEInfoLine", { link = "InfoLine" })
hi(0, "ALEInfoSign", { link = "BlueSign" })
hi(0, "ALEVirtualTextError", { link = "VirtualTextError" })
hi(0, "ALEVirtualTextInfo", { link = "VirtualTextInfo" })
hi(0, "ALEVirtualTextStyleError", { link = "VirtualTextHint" })
hi(0, "ALEVirtualTextStyleWarning", { link = "VirtualTextHint" })
hi(0, "ALEVirtualTextWarning", { link = "VirtualTextWarning" })
hi(0, "ALEWarning", { link = "WarningText" })
hi(0, "ALEWarningLine", { link = "WarningLine" })
hi(0, "ALEWarningSign", { link = "YellowSign" })
hi(0, "Added", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "Aqua", { ctermfg = 108, fg = "#3ce451" })
hi(0, "AquaBold", { ctermfg = 108, fg = "#3ce451" })
hi(0, "AquaItalic", { ctermfg = 108, fg = "#3ce451" })
hi(0, "AquaSign", { ctermfg = 108, fg = "#3ce451" })
hi(0, "AvanteAnnotation", { link = "Comment" })
hi(0, "AvanteButtonDanger", { bg = "#81b9e4", fg = "#1d2767" })
hi(0, "AvanteButtonDangerHover", { bg = "#f54197", fg = "#1d2767" })
hi(0, "AvanteButtonDefault", { bg = "#81b9e4", fg = "#1d2767" })
hi(0, "AvanteButtonDefaultHover", { bg = "#c5ca00", fg = "#1d2767" })
hi(0, "AvanteButtonPrimary", { bg = "#81b9e4", fg = "#1d2767" })
hi(0, "AvanteButtonPrimaryHover", { bg = "#16beb2", fg = "#1d2767" })
hi(0, "AvanteCommentFg", { fg = "#bb8c48" })
hi(0, "AvanteConfirmTitle", { bg = "#f54197", fg = "#1d2767" })
hi(0, "AvanteConflictCurrent", { bg = "#6a0c3f", bold = true })
hi(0, "AvanteConflictCurrentLabel", { bg = "#87104f" })
hi(0, "AvanteConflictIncoming", { bg = "#014d58", bold = true })
hi(0, "AvanteConflictIncomingLabel", { bg = "#016371" })
hi(0, "AvanteInlineHint", { link = "Keyword" })
hi(0, "AvantePopupHint", { link = "NormalFloat" })
hi(0, "AvantePromptInputBorder", { link = "NormalFloat" })
hi(0, "AvanteReversedNormal", { bg = "#ffd29e", fg = "#1d3139" })
hi(0, "AvanteReversedSubtitle", { fg = "#37cae5" })
hi(0, "AvanteReversedThirdTitle", { fg = "#31457f" })
hi(0, "AvanteReversedTitle", { fg = "#6ce44f" })
hi(0, "AvanteSidebarNormal", { link = "NormalFloat" })
hi(0, "AvanteSidebarWinHorizontalSeparator", { bg = "#0f2324", fg = "#775030" })
hi(0, "AvanteSidebarWinSeparator", { bg = "#0f2324", fg = "#1d3139" })
hi(0, "AvanteStateSpinnerCompacting", { bg = "#af78ff", fg = "#1d2767" })
hi(0, "AvanteStateSpinnerFailed", { bg = "#f54197", fg = "#1d2767" })
hi(0, "AvanteStateSpinnerGenerating", { bg = "#89a2ff", fg = "#1d2767" })
hi(0, "AvanteStateSpinnerSearching", { bg = "#af78ff", fg = "#1d2767" })
hi(0, "AvanteStateSpinnerSucceeded", { bg = "#b6be00", fg = "#1d2767" })
hi(0, "AvanteStateSpinnerThinking", { bg = "#af78ff", fg = "#1d2767" })
hi(0, "AvanteStateSpinnerToolCalling", { bg = "#16beb2", fg = "#1d2767" })
hi(0, "AvanteSubtitle", { bg = "#16beb2", fg = "#1d2767" })
hi(0, "AvanteSuggestion", { link = "Comment" })
hi(0, "AvanteTaskCompleted", { bg = "#0f2324", fg = "#6ce44f" })
hi(0, "AvanteThinking", { bg = "#0f2324", fg = "#fa5eff" })
hi(0, "AvanteThirdTitle", { bg = "#003f61", fg = "#abbfff" })
hi(0, "AvanteTitle", { bg = "#b6be00", fg = "#1d2767" })
hi(0, "AvanteToBeDeleted", { bg = "#fcc6d7", strikethrough = true })
hi(0, "AvanteToBeDeletedWOStrikethrough", { bg = "#6a0c3f" })
hi(0, "Blamer", { link = "Grey" })
hi(0, "BlinkCmpKindArray", { link = "Aqua" })
hi(0, "BlinkCmpKindBoolean", { link = "Aqua" })
hi(0, "BlinkCmpKindClass", { link = "Red" })
hi(0, "BlinkCmpKindColor", { link = "Aqua" })
hi(0, "BlinkCmpKindConstant", { link = "Blue" })
hi(0, "BlinkCmpKindConstructor", { link = "Green" })
hi(0, "BlinkCmpKindDefault", { link = "Aqua" })
hi(0, "BlinkCmpKindEnum", { link = "Yellow" })
hi(0, "BlinkCmpKindEnumMember", { link = "Purple" })
hi(0, "BlinkCmpKindEvent", { link = "Orange" })
hi(0, "BlinkCmpKindField", { link = "Green" })
hi(0, "BlinkCmpKindFile", { link = "Green" })
hi(0, "BlinkCmpKindFolder", { link = "Aqua" })
hi(0, "BlinkCmpKindFunction", { link = "Green" })
hi(0, "BlinkCmpKindInterface", { link = "Yellow" })
hi(0, "BlinkCmpKindKey", { link = "Red" })
hi(0, "BlinkCmpKindKeyword", { link = "Red" })
hi(0, "BlinkCmpKindMethod", { link = "Green" })
hi(0, "BlinkCmpKindModule", { link = "Purple" })
hi(0, "BlinkCmpKindNamespace", { link = "Purple" })
hi(0, "BlinkCmpKindNull", { link = "Aqua" })
hi(0, "BlinkCmpKindNumber", { link = "Aqua" })
hi(0, "BlinkCmpKindObject", { link = "Aqua" })
hi(0, "BlinkCmpKindOperator", { link = "Orange" })
hi(0, "BlinkCmpKindPackage", { link = "Purple" })
hi(0, "BlinkCmpKindProperty", { link = "Blue" })
hi(0, "BlinkCmpKindReference", { link = "Aqua" })
hi(0, "BlinkCmpKindSnippet", { link = "Aqua" })
hi(0, "BlinkCmpKindString", { link = "Aqua" })
hi(0, "BlinkCmpKindStruct", { link = "Yellow" })
hi(0, "BlinkCmpKindText", { link = "Fg" })
hi(0, "BlinkCmpKindTypeParameter", { link = "Yellow" })
hi(0, "BlinkCmpKindUnit", { link = "Purple" })
hi(0, "BlinkCmpKindValue", { link = "Purple" })
hi(0, "BlinkCmpKindVariable", { link = "Blue" })
hi(0, "BlinkCmpLabelMatch", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "Blue", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "BlueBold", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "BlueItalic", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "BlueSign", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "BookmarkAnnotationLine", { link = "DiffAdd" })
hi(0, "BookmarkAnnotationSign", { link = "GreenSign" })
hi(0, "BookmarkLine", { link = "DiffChange" })
hi(0, "BookmarkSign", { link = "BlueSign" })
hi(0, "Boolean", { ctermfg = 175, fg = "#ff7196" })
hi(0, "BufTabLineActive", { link = "TabLine" })
hi(0, "BufTabLineCurrent", { link = "TabLineSel" })
hi(0, "BufTabLineFill", { link = "TabLineFill" })
hi(0, "BufTabLineHidden", { link = "TabLineFill" })
hi(0, "BufferCurrent", { bg = "#0f2324", ctermbg = 234, ctermfg = 223, fg = "#ffeea4" })
hi(0, "BufferCurrentADDED", { bg = "#0f2324", ctermbg = 234, ctermfg = 142, fg = "#bbd13d" })
hi(0, "BufferCurrentCHANGED", { bg = "#0f2324", ctermbg = 234, ctermfg = 109, fg = "#43c4ab" })
hi(0, "BufferCurrentDELETED", { bg = "#0f2324", ctermbg = 234, ctermfg = 167, fg = "#ff6939" })
hi(0, "BufferCurrentIndex", { bg = "#0f2324", ctermbg = 234, ctermfg = 223, fg = "#ffeea4" })
hi(0, "BufferCurrentMod", { bg = "#0f2324", ctermbg = 234, ctermfg = 109, fg = "#43c4ab" })
hi(0, "BufferCurrentSign", { bg = "#0f2324", ctermbg = 234, ctermfg = 246, fg = "#cea44f" })
hi(0, "BufferCurrentTarget", { bg = "#0f2324", bold = true, ctermbg = 234, ctermfg = 167, fg = "#ff6939" })
hi(0, "BufferInactive", { bg = "#08191b", ctermbg = 232, ctermfg = 245, fg = "#bb8c48" })
hi(0, "BufferInactiveADDED", { link = "BufferInactiveSign" })
hi(0, "BufferInactiveCHANGED", { link = "BufferInactiveSign" })
hi(0, "BufferInactiveDELETED", { link = "BufferInactiveSign" })
hi(0, "BufferInactiveIndex", { bg = "#08191b", ctermbg = 232, ctermfg = 245, fg = "#bb8c48" })
hi(0, "BufferInactiveMod", { bg = "#08191b", ctermbg = 232, ctermfg = 245, fg = "#bb8c48" })
hi(0, "BufferInactiveSign", { bg = "#08191b", ctermbg = 232, ctermfg = 243, fg = "#a4773e" })
hi(0, "BufferInactiveTarget", { bg = "#08191b", bold = true, ctermbg = 232, ctermfg = 214, fg = "#ffd450" })
hi(0, "BufferTabpageFill", { bg = "#08191b", ctermbg = 232, ctermfg = 232, fg = "#17272f" })
hi(0, "BufferTabpages", { bg = "#08191b", bold = true, ctermbg = 232, ctermfg = 245, fg = "#bb8c48" })
hi(0, "BufferTabpagesSep", { bg = "#08191b", bold = true, ctermbg = 232, ctermfg = 243, fg = "#a4773e" })
hi(0, "BufferVisible", { bg = "#08191b", ctermbg = 232, ctermfg = 223, fg = "#ffeea4" })
hi(0, "BufferVisibleIndex", { bg = "#08191b", ctermbg = 232, ctermfg = 223, fg = "#ffeea4" })
hi(0, "BufferVisibleMod", { bg = "#08191b", ctermbg = 232, ctermfg = 109, fg = "#43c4ab" })
hi(0, "BufferVisibleSign", { bg = "#08191b", ctermbg = 232, ctermfg = 246, fg = "#cea44f" })
hi(0, "BufferVisibleTarget", { bg = "#08191b", bold = true, ctermbg = 232, ctermfg = 214, fg = "#ffd450" })
hi(0, "Changed", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "Character", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "ClapBlines", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "ClapBlinesLineNr", { link = "Grey" })
hi(0, "ClapCurrentSelection", { bg = "#282828", bold = true, ctermbg = 235 })
hi(0, "ClapDisplay", { link = "Pmenu" })
hi(0, "ClapFile", { link = "Fg" })
hi(0, "ClapFuzzyMatches", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "ClapFuzzyMatches1", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches10", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches11", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches12", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches2", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches3", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches4", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches5", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches6", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches7", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches8", { link = "ClapFuzzyMatches" })
hi(0, "ClapFuzzyMatches9", { link = "ClapFuzzyMatches" })
hi(0, "ClapInput", { link = "Pmenu" })
hi(0, "ClapMatches1", { bold = true, ctermfg = 167, fg = "#ff6939" })
hi(0, "ClapMatches2", { bold = true, ctermfg = 208, fg = "#ff9c44" })
hi(0, "ClapMatches3", { bold = true, ctermfg = 214, fg = "#ffd450" })
hi(0, "ClapMatches4", { bold = true, ctermfg = 108, fg = "#3ce451" })
hi(0, "ClapMatches5", { bold = true, ctermfg = 109, fg = "#43c4ab" })
hi(0, "ClapMatches6", { bold = true, ctermfg = 175, fg = "#ff7196" })
hi(0, "ClapNoMatchesFound", { bold = true, ctermfg = 167, fg = "#ff6939" })
hi(0, "ClapPreview", { link = "Pmenu" })
hi(0, "ClapProviderAbout", { link = "ClapBlines" })
hi(0, "ClapProviderColon", { link = "ClapBlines" })
hi(0, "ClapProviderId", { bold = true, ctermfg = 223, fg = "#ffeea4" })
hi(0, "ClapSearchText", { link = "ClapFuzzyMatches" })
hi(0, "ClapSelected", { bold = true, ctermfg = 167, fg = "#ff6939" })
hi(0, "ClapSpinner", { bg = "#512e28", bold = true, ctermbg = 237, ctermfg = 208, fg = "#ff9c44" })
hi(0, "CleverFDefaultLabel", { link = "Search" })
hi(0, "CmpItemAbbr", { link = "Fg" })
hi(0, "CmpItemAbbrDeprecated", { link = "Grey" })
hi(0, "CmpItemAbbrMatch", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "CmpItemKind", { link = "Yellow" })
hi(0, "CmpItemKindArray", { link = "Aqua" })
hi(0, "CmpItemKindBoolean", { link = "Aqua" })
hi(0, "CmpItemKindClass", { link = "Red" })
hi(0, "CmpItemKindColor", { link = "Aqua" })
hi(0, "CmpItemKindConstant", { link = "Blue" })
hi(0, "CmpItemKindConstructor", { link = "Green" })
hi(0, "CmpItemKindDefault", { link = "Aqua" })
hi(0, "CmpItemKindEnum", { link = "Yellow" })
hi(0, "CmpItemKindEnumMember", { link = "Purple" })
hi(0, "CmpItemKindEvent", { link = "Orange" })
hi(0, "CmpItemKindField", { link = "Green" })
hi(0, "CmpItemKindFile", { link = "Green" })
hi(0, "CmpItemKindFolder", { link = "Aqua" })
hi(0, "CmpItemKindFunction", { link = "Green" })
hi(0, "CmpItemKindInterface", { link = "Yellow" })
hi(0, "CmpItemKindKey", { link = "Red" })
hi(0, "CmpItemKindKeyword", { link = "Red" })
hi(0, "CmpItemKindMethod", { link = "Green" })
hi(0, "CmpItemKindModule", { link = "Purple" })
hi(0, "CmpItemKindNamespace", { link = "Purple" })
hi(0, "CmpItemKindNull", { link = "Aqua" })
hi(0, "CmpItemKindNumber", { link = "Aqua" })
hi(0, "CmpItemKindObject", { link = "Aqua" })
hi(0, "CmpItemKindOperator", { link = "Orange" })
hi(0, "CmpItemKindPackage", { link = "Purple" })
hi(0, "CmpItemKindProperty", { link = "Blue" })
hi(0, "CmpItemKindReference", { link = "Aqua" })
hi(0, "CmpItemKindSnippet", { link = "Aqua" })
hi(0, "CmpItemKindString", { link = "Aqua" })
hi(0, "CmpItemKindStruct", { link = "Yellow" })
hi(0, "CmpItemKindText", { link = "Fg" })
hi(0, "CmpItemKindTypeParameter", { link = "Yellow" })
hi(0, "CmpItemKindUnit", { link = "Purple" })
hi(0, "CmpItemKindValue", { link = "Purple" })
hi(0, "CmpItemKindVariable", { link = "Blue" })
hi(0, "CmpItemMenu", { link = "Fg" })
hi(0, "CocCodeLens", { link = "Grey" })
hi(0, "CocDisabled", { link = "Grey" })
hi(0, "CocErrorFloat", { link = "ErrorFloat" })
hi(0, "CocErrorHighlight", { link = "ErrorText" })
hi(0, "CocErrorLine", { link = "ErrorLine" })
hi(0, "CocErrorSign", { link = "RedSign" })
hi(0, "CocErrorVirtualText", { link = "VirtualTextError" })
hi(0, "CocFadeOut", { link = "Grey" })
hi(0, "CocFloatDividingLine", { link = "Grey" })
hi(0, "CocFloating", { link = "NormalFloat" })
hi(0, "CocGitAddedSign", { link = "GreenSign" })
hi(0, "CocGitChangeRemovedSign", { link = "PurpleSign" })
hi(0, "CocGitChangedSign", { link = "BlueSign" })
hi(0, "CocGitRemovedSign", { link = "RedSign" })
hi(0, "CocGitTopRemovedSign", { link = "RedSign" })
hi(0, "CocHighlightText", { link = "CurrentWord" })
hi(0, "CocHintFloat", { link = "HintFloat" })
hi(0, "CocHintHighlight", { link = "HintText" })
hi(0, "CocHintLine", { link = "HintLine" })
hi(0, "CocHintSign", { link = "GreenSign" })
hi(0, "CocHintVirtualText", { link = "VirtualTextHint" })
hi(0, "CocHoverRange", { bg = "#452723", ctermbg = 236 })
hi(0, "CocInfoFloat", { link = "InfoFloat" })
hi(0, "CocInfoHighlight", { link = "InfoText" })
hi(0, "CocInfoLine", { link = "InfoLine" })
hi(0, "CocInfoSign", { link = "BlueSign" })
hi(0, "CocInfoVirtualText", { link = "VirtualTextInfo" })
hi(0, "CocInlayHint", { link = "InlayHints" })
hi(0, "CocInlineVirtualText", { link = "Grey" })
hi(0, "CocListMode", { link = "StatusLine" })
hi(0, "CocListPath", { link = "StatusLine" })
hi(0, "CocListsDesc", { link = "Grey" })
hi(0, "CocListsLine", { link = "Fg" })
hi(0, "CocMarkdownCode", { link = "Green" })
hi(0, "CocMarkdownHeader", { bold = true, ctermfg = 208, fg = "#ff9c44" })
hi(0, "CocMarkdownLink", { ctermfg = 142, fg = "#bbd13d", underline = true })
hi(0, "CocMenuSel", { link = "PmenuSel" })
hi(0, "CocNotificationButton", { link = "PmenuSel" })
hi(0, "CocNotificationProgress", { link = "Green" })
hi(0, "CocPumMenu", { link = "Pmenu" })
hi(0, "CocPumSearch", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "CocPumShortcut", { link = "Grey" })
hi(0, "CocPumVirtualText", { link = "Grey" })
hi(0, "CocSearch", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "CocSelectedText", { link = "Orange" })
hi(0, "CocSemClass", { link = "TSType" })
hi(0, "CocSemEnum", { link = "TSType" })
hi(0, "CocSemEnumMember", { link = "TSProperty" })
hi(0, "CocSemEvent", { link = "TSLabel" })
hi(0, "CocSemInterface", { link = "TSType" })
hi(0, "CocSemModifier", { link = "TSOperator" })
hi(0, "CocSemStruct", { link = "TSType" })
hi(0, "CocSemTypeParameter", { link = "TSType" })
hi(0, "CocSemVariable", { link = "TSVariable" })
hi(0, "CocSnippetVisual", { link = "DiffAdd" })
hi(0, "CocStrikeThrough", { link = "Grey" })
hi(0, "CocWarningFloat", { link = "WarningFloat" })
hi(0, "CocWarningHighlight", { link = "WarningText" })
hi(0, "CocWarningLine", { link = "WarningLine" })
hi(0, "CocWarningSign", { link = "YellowSign" })
hi(0, "CocWarningVirtualText", { link = "VirtualTextWarning" })
hi(0, "ColorColumn", { bg = "#282828", ctermbg = 235 })
hi(0, "CommandMode", { link = "Identifier" })
hi(0, "Comment", { ctermfg = 245, fg = "#bb8c48", italic = true })
hi(0, "Conceal", { ctermfg = 243, fg = "#a4773e" })
hi(0, "Conditional", { ctermfg = 167, fg = "#ff6939" })
hi(0, "Constant", { ctermfg = 108, fg = "#3ce451" })
hi(0, "CopilotSuggestion", { link = "Grey" })
hi(0, "CtrlPLinePre", { ctermfg = 237, fg = "#5f3e28" })
hi(0, "CtrlPMatch", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "CtrlPMode1", { bg = "#512e28", bold = true, ctermbg = 237, ctermfg = 109, fg = "#43c4ab" })
hi(0, "CtrlPMode2", { bg = "#67af76", bold = true, ctermbg = 109, ctermfg = 234, fg = "#1d3139" })
hi(0, "CtrlPNoEntries", { link = "Red" })
hi(0, "CtrlPPrtBase", { ctermfg = 237, fg = "#5f3e28" })
hi(0, "CtrlPPrtCursor", { link = "Blue" })
hi(0, "CtrlPStats", { bg = "#512e28", bold = true, ctermbg = 237, ctermfg = 246, fg = "#cea44f" })
hi(0, "CurSearch", { bg = "#cf0056", ctermbg = 124, ctermfg = 234, fg = "#1d3139" })
hi(0, "CurrentWord", { bg = "#452723", ctermbg = 236 })
hi(0, "CurrentWordTwins", { link = "CurrentWord" })
hi(0, "Cursor", { reverse = true })
hi(0, "CursorColumn", { bg = "#282828", ctermbg = 235 })
hi(0, "CursorLine", { bg = "#282828", ctermbg = 235 })
hi(0, "CursorLineNr", { ctermfg = 246, fg = "#cea44f" })
hi(0, "CursorWord0", { link = "CurrentWord" })
hi(0, "CursorWord1", { link = "CurrentWord" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, ctermfg = 109, fg = "#43c4ab" })
hi(0, "DapUIBreakpointsInfo", { link = "Green" })
hi(0, "DapUIBreakpointsPath", { link = "Blue" })
hi(0, "DapUIDecoration", { link = "Blue" })
hi(0, "DapUIFloatBorder", { link = "Blue" })
hi(0, "DapUILineNumber", { link = "Blue" })
hi(0, "DapUIModifiedValue", { bold = true, ctermfg = 109, fg = "#43c4ab" })
hi(0, "DapUIScope", { link = "Blue" })
hi(0, "DapUISource", { link = "Purple" })
hi(0, "DapUIStoppedThread", { link = "Blue" })
hi(0, "DapUIThread", { link = "Green" })
hi(0, "DapUIType", { link = "Purple" })
hi(0, "DapUIWatchesEmpty", { link = "Red" })
hi(0, "DapUIWatchesError", { link = "Red" })
hi(0, "DapUIWatchesValue", { link = "Green" })
hi(0, "Debug", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "Define", { ctermfg = 175, fg = "#ff7196" })
hi(0, "DefinitionCount", { link = "Grey" })
hi(0, "DefinitionIcon", { link = "Blue" })
hi(0, "DefinitionPreviewTitle", { bold = true, ctermfg = 109, fg = "#43c4ab" })
hi(0, "Delimiter", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "DiagnosticError", { ctermfg = 167, fg = "#ff6939" })
hi(0, "DiagnosticFloatingError", { link = "ErrorFloat" })
hi(0, "DiagnosticFloatingHint", { link = "HintFloat" })
hi(0, "DiagnosticFloatingInfo", { link = "InfoFloat" })
hi(0, "DiagnosticFloatingWarn", { link = "WarningFloat" })
hi(0, "DiagnosticHint", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "DiagnosticInfo", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "DiagnosticInformation", { link = "DiagnosticInfo" })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#c9ffde" })
hi(0, "DiagnosticSignError", { link = "RedSign" })
hi(0, "DiagnosticSignHint", { link = "GreenSign" })
hi(0, "DiagnosticSignInfo", { link = "BlueSign" })
hi(0, "DiagnosticSignWarn", { link = "YellowSign" })
hi(0, "DiagnosticUnderlineError", { sp = "#fb4934", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#b8bb26", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#83a598", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#fabd2f", undercurl = true })
hi(0, "DiagnosticUnnecessary", { ctermfg = 245, fg = "#bb8c48" })
hi(0, "DiagnosticVirtualTextError", { link = "VirtualTextError" })
hi(0, "DiagnosticVirtualTextHint", { link = "VirtualTextHint" })
hi(0, "DiagnosticVirtualTextInfo", { link = "VirtualTextInfo" })
hi(0, "DiagnosticVirtualTextWarn", { link = "VirtualTextWarning" })
hi(0, "DiagnosticWarn", { ctermfg = 214, fg = "#ffd450" })
hi(0, "DiagnosticWarning", { link = "DiagnosticWarn" })
hi(0, "DiffAdd", { bg = "#3e3200", ctermbg = 22 })
hi(0, "DiffChange", { bg = "#003333", ctermbg = 17 })
hi(0, "DiffDelete", { bg = "#4d0824", ctermbg = 52 })
hi(0, "DiffText", { bg = "#67af76", ctermbg = 109, ctermfg = 234, fg = "#1d3139" })
hi(0, "Directory", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "EasyMotionShade", { link = "Grey" })
hi(0, "EasyMotionTarget", { link = "Search" })
hi(0, "EndOfBuffer", { ctermfg = 239, fg = "#775030" })
hi(0, "Error", { ctermfg = 167, fg = "#ff6939" })
hi(0, "ErrorFloat", { ctermfg = 167, fg = "#ff6939" })
hi(0, "ErrorMsg", { bold = true, ctermfg = 167, fg = "#ff6939", underline = true })
hi(0, "ErrorText", { sp = "#fb4934", undercurl = true })
hi(0, "Exception", { ctermfg = 167, fg = "#ff6939" })
hi(0, "Fg", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "Float", { ctermfg = 175, fg = "#ff7196" })
hi(0, "FloatBorder", { ctermbg = 237, ctermfg = 245, fg = "#bb8c48" })
hi(0, "FloatShadow", { bg = "#005689", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#005689", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#512e28", bold = true, ctermbg = 237, ctermfg = 208, fg = "#ff9c44" })
hi(0, "FloatermBorder", { link = "Grey" })
hi(0, "FoldColumn", { ctermfg = 243, fg = "#a4773e" })
hi(0, "Folded", { bg = "#282828", ctermbg = 235, ctermfg = 245, fg = "#bb8c48" })
hi(0, "Function", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "FzfLuaBorder", { link = "Grey" })
hi(0, "FzfLuaTitle", { link = "Title" })
hi(0, "GitGutterAdd", { link = "GreenSign" })
hi(0, "GitGutterAddLine", { link = "DiffAdd" })
hi(0, "GitGutterAddLineNr", { link = "Green" })
hi(0, "GitGutterChange", { link = "BlueSign" })
hi(0, "GitGutterChangeDelete", { link = "PurpleSign" })
hi(0, "GitGutterChangeDeleteLine", { link = "DiffChange" })
hi(0, "GitGutterChangeDeleteLineNr", { link = "Purple" })
hi(0, "GitGutterChangeLine", { link = "DiffChange" })
hi(0, "GitGutterChangeLineNr", { link = "Blue" })
hi(0, "GitGutterDelete", { link = "RedSign" })
hi(0, "GitGutterDeleteLine", { link = "DiffDelete" })
hi(0, "GitGutterDeleteLineNr", { link = "Red" })
hi(0, "GitSignsAdd", { link = "GreenSign" })
hi(0, "GitSignsAddLn", { link = "DiffAdd" })
hi(0, "GitSignsAddNr", { link = "Green" })
hi(0, "GitSignsChange", { link = "BlueSign" })
hi(0, "GitSignsChangeLn", { link = "DiffChange" })
hi(0, "GitSignsChangeNr", { link = "Blue" })
hi(0, "GitSignsCurrentLineBlame", { link = "Grey" })
hi(0, "GitSignsDelete", { link = "RedSign" })
hi(0, "GitSignsDeleteLn", { link = "DiffDelete" })
hi(0, "GitSignsDeleteNr", { link = "Red" })
hi(0, "GitSignsStagedAdd", { fg = "#636e22" })
hi(0, "GitSignsStagedAddCul", { fg = "#636e22" })
hi(0, "GitSignsStagedAddLn", { bg = "#3e3200" })
hi(0, "GitSignsStagedAddNr", { fg = "#636e22" })
hi(0, "GitSignsStagedChange", { fg = "#28695d" })
hi(0, "GitSignsStagedChangeCul", { fg = "#28695d" })
hi(0, "GitSignsStagedChangeLn", { bg = "#003333" })
hi(0, "GitSignsStagedChangeNr", { fg = "#28695d" })
hi(0, "GitSignsStagedChangedelete", { fg = "#28695d" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#28695d" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#003333" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#28695d" })
hi(0, "GitSignsStagedDelete", { fg = "#923115" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#923115" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#923115" })
hi(0, "GitSignsStagedTopdelete", { fg = "#923115" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#923115" })
hi(0, "GitSignsStagedTopdeleteLn", { bg = "#4d0824" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#923115" })
hi(0, "GitSignsStagedUntracked", { fg = "#636e22" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#636e22" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#3e3200" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#636e22" })
hi(0, "Green", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "GreenBold", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "GreenItalic", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "GreenSign", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "Grey", { ctermfg = 245, fg = "#bb8c48" })
hi(0, "HighlightedyankRegion", { link = "Visual" })
hi(0, "HintFloat", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "HintText", { sp = "#b8bb26", undercurl = true })
hi(0, "HopNextKey", { bold = true, ctermfg = 208, fg = "#ff9c44" })
hi(0, "HopNextKey1", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "HopNextKey2", { link = "Green" })
hi(0, "HopUnmatched", { link = "Grey" })
hi(0, "IblIndent", { ctermfg = 239, fg = "#775030", nocombine = true })
hi(0, "IblScope", { ctermfg = 245, fg = "#bb8c48", nocombine = true })
hi(0, "Identifier", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "Ignore", { ctermfg = 245, fg = "#bb8c48" })
hi(0, "IlluminatedWordRead", { link = "CurrentWord" })
hi(0, "IlluminatedWordText", { link = "CurrentWord" })
hi(0, "IlluminatedWordWrite", { link = "CurrentWord" })
hi(0, "IncSearch", { bg = "#cf0056", ctermbg = 124, ctermfg = 234, fg = "#1d3139" })
hi(0, "InclineNormalNC", { bg = "#512e28", ctermbg = 237, ctermfg = 245, fg = "#bb8c48" })
hi(0, "Include", { ctermfg = 175, fg = "#ff7196" })
hi(0, "IndentBlanklineChar", { link = "IblIndent" })
hi(0, "IndentBlanklineContextChar", { link = "IblScope" })
hi(0, "IndentBlanklineSpaceChar", { link = "IndentBlanklineChar" })
hi(0, "IndentBlanklineSpaceCharBlankline", { link = "IndentBlanklineChar" })
hi(0, "InfoFloat", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "InfoText", { sp = "#83a598", undercurl = true })
hi(0, "InlayHints", { link = "LineNr" })
hi(0, "InsertMode", { link = "Question" })
hi(0, "Keyword", { ctermfg = 167, fg = "#ff6939" })
hi(0, "Label", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "Lf_hl_cursorline", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "Lf_hl_gtagsHighlight", { link = "Visual" })
hi(0, "Lf_hl_match", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "Lf_hl_match0", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "Lf_hl_match1", { bold = true, ctermfg = 108, fg = "#3ce451" })
hi(0, "Lf_hl_match2", { bold = true, ctermfg = 109, fg = "#43c4ab" })
hi(0, "Lf_hl_match3", { bold = true, ctermfg = 175, fg = "#ff7196" })
hi(0, "Lf_hl_match4", { bold = true, ctermfg = 208, fg = "#ff9c44" })
hi(0, "Lf_hl_matchRefine", { bold = true, ctermfg = 167, fg = "#ff6939" })
hi(0, "Lf_hl_popup_blank", { link = "Lf_hl_popup_window" })
hi(0, "Lf_hl_popup_category", { bg = "#b67351", ctermbg = 245, ctermfg = 234, fg = "#1d3139" })
hi(0, "Lf_hl_popup_cursor", { bg = "#d8ad00", ctermbg = 142, ctermfg = 234, fg = "#1d3139" })
hi(0, "Lf_hl_popup_cwd", { link = "Pmenu" })
hi(0, "Lf_hl_popup_fullPathMode", { bg = "#693d34", ctermbg = 239, ctermfg = 223, fg = "#ffeea4" })
hi(0, "Lf_hl_popup_fuzzyMode", { bg = "#9d6048", ctermbg = 243, ctermfg = 234, fg = "#1d3139" })
hi(0, "Lf_hl_popup_inputMode", { bg = "#ce8957", bold = true, ctermbg = 246, ctermfg = 234, fg = "#1d3139" })
hi(0, "Lf_hl_popup_inputText", { bg = "#512e28", ctermbg = 237, ctermfg = 142, fg = "#bbd13d" })
hi(0, "Lf_hl_popup_lineInfo", { bg = "#d8ad00", ctermbg = 142, ctermfg = 234, fg = "#1d3139" })
hi(0, "Lf_hl_popup_nameOnlyMode", { bg = "#693d34", ctermbg = 239, ctermfg = 223, fg = "#ffeea4" })
hi(0, "Lf_hl_popup_normalMode", { bg = "#ce8957", bold = true, ctermbg = 246, ctermfg = 234, fg = "#1d3139" })
hi(0, "Lf_hl_popup_prompt", { link = "Orange" })
hi(0, "Lf_hl_popup_regexMode", { bg = "#693d34", ctermbg = 239, ctermfg = 223, fg = "#ffeea4" })
hi(0, "Lf_hl_popup_spin", { link = "Purple" })
hi(0, "Lf_hl_popup_total", { bg = "#ffb670", ctermbg = 214, ctermfg = 234, fg = "#1d3139" })
hi(0, "Lf_hl_popup_window", { link = "Pmenu" })
hi(0, "Lf_hl_rgHighlight", { link = "Visual" })
hi(0, "Lf_hl_selection", { link = "DiffAdd" })
hi(0, "LightspeedGreyWash", { link = "Grey" })
hi(0, "LightspeedLabel", { bold = true, ctermfg = 167, fg = "#ff6939", underline = true })
hi(0, "LightspeedLabelDistant", { bold = true, ctermfg = 109, fg = "#43c4ab", underline = true })
hi(0, "LightspeedMaskedChar", { link = "Purple" })
hi(0, "LightspeedPendingOpArea", { bg = "#d8ad00", ctermbg = 142, ctermfg = 234, fg = "#1d3139" })
hi(0, "LightspeedShortcut", { bg = "#fc356e", bold = true, ctermbg = 167, ctermfg = 234, fg = "#1d3139" })
hi(0, "LightspeedUnlabeledMatch", { bold = true, ctermfg = 223, fg = "#ffeea4" })
hi(0, "LineDiagTuncateLine", { link = "Yellow" })
hi(0, "LineNr", { ctermfg = 243, fg = "#a4773e" })
hi(0, "LspCodeLens", { link = "VirtualTextInfo" })
hi(0, "LspCodeLensSeparator", { link = "VirtualTextHint" })
hi(0, "LspDiagInlineError", { link = "ErrorText" })
hi(0, "LspDiagInlineHint", { link = "HintText" })
hi(0, "LspDiagInlineInfo", { link = "InfoText" })
hi(0, "LspDiagInlineWarning", { link = "WarningText" })
hi(0, "LspDiagSignErrorText", { link = "RedSign" })
hi(0, "LspDiagSignHintText", { link = "GreenSign" })
hi(0, "LspDiagSignInfoText", { link = "BlueSign" })
hi(0, "LspDiagSignWarningText", { link = "YellowSign" })
hi(0, "LspDiagVirtualTextError", { link = "VirtualTextError" })
hi(0, "LspDiagVirtualTextHint", { link = "VirtualTextHint" })
hi(0, "LspDiagVirtualTextInfo", { link = "VirtualTextInfo" })
hi(0, "LspDiagVirtualTextWarning", { link = "VirtualTextWarning" })
hi(0, "LspDiagnosticsDefaultError", { link = "DiagnosticError" })
hi(0, "LspDiagnosticsDefaultHint", { link = "DiagnosticHint" })
hi(0, "LspDiagnosticsDefaultInformation", { link = "DiagnosticInfo" })
hi(0, "LspDiagnosticsDefaultWarning", { link = "DiagnosticWarn" })
hi(0, "LspDiagnosticsFloatingError", { link = "DiagnosticFloatingError" })
hi(0, "LspDiagnosticsFloatingHint", { link = "DiagnosticFloatingHint" })
hi(0, "LspDiagnosticsFloatingInformation", { link = "DiagnosticFloatingInfo" })
hi(0, "LspDiagnosticsFloatingWarning", { link = "DiagnosticFloatingWarn" })
hi(0, "LspDiagnosticsSignError", { link = "DiagnosticSignError" })
hi(0, "LspDiagnosticsSignHint", { link = "DiagnosticSignHint" })
hi(0, "LspDiagnosticsSignInformation", { link = "DiagnosticSignInfo" })
hi(0, "LspDiagnosticsSignWarning", { link = "DiagnosticSignWarn" })
hi(0, "LspDiagnosticsUnderlineError", { link = "DiagnosticUnderlineError" })
hi(0, "LspDiagnosticsUnderlineHint", { link = "DiagnosticUnderlineHint" })
hi(0, "LspDiagnosticsUnderlineInformation", { link = "DiagnosticUnderlineInfo" })
hi(0, "LspDiagnosticsUnderlineWarning", { link = "DiagnosticUnderlineWarn" })
hi(0, "LspDiagnosticsVirtualTextError", { link = "DiagnosticVirtualTextError" })
hi(0, "LspDiagnosticsVirtualTextHint", { link = "DiagnosticVirtualTextHint" })
hi(0, "LspDiagnosticsVirtualTextInformation", { link = "DiagnosticVirtualTextInfo" })
hi(0, "LspDiagnosticsVirtualTextWarning", { link = "DiagnosticVirtualTextWarn" })
hi(0, "LspErrorHighlight", { link = "ErrorText" })
hi(0, "LspErrorVirtualText", { link = "VirtualTextError" })
hi(0, "LspFloatWinBorder", { bg = "#0f2324", ctermbg = 234, ctermfg = 234, fg = "#1d3139" })
hi(0, "LspHintHighlight", { link = "HintText" })
hi(0, "LspHintVirtualText", { link = "VirtualTextHint" })
hi(0, "LspInformationHighlight", { link = "InfoText" })
hi(0, "LspInformationVirtualText", { link = "VirtualTextInfo" })
hi(0, "LspInlayHint", { link = "InlayHints" })
hi(0, "LspInlayHintsParam", { link = "InlayHints" })
hi(0, "LspLinesDiagBorder", { link = "Yellow" })
hi(0, "LspReferenceRead", { link = "CurrentWord" })
hi(0, "LspReferenceText", { link = "CurrentWord" })
hi(0, "LspReferenceWrite", { link = "CurrentWord" })
hi(0, "LspSagaAutoPreview", { link = "Green" })
hi(0, "LspSagaCodeActionBorder", { link = "Purple" })
hi(0, "LspSagaCodeActionContent", { link = "Green" })
hi(0, "LspSagaCodeActionTitle", { bold = true, ctermfg = 175, fg = "#ff7196" })
hi(0, "LspSagaCodeActionTruncateLine", { link = "Purple" })
hi(0, "LspSagaDefPreviewBorder", { link = "Blue" })
hi(0, "LspSagaDiagnosticBorder", { link = "Orange" })
hi(0, "LspSagaDiagnosticError", { link = "Red" })
hi(0, "LspSagaDiagnosticHeader", { bold = true, ctermfg = 208, fg = "#ff9c44" })
hi(0, "LspSagaDiagnosticHint", { link = "Green" })
hi(0, "LspSagaDiagnosticInfo", { link = "Blue" })
hi(0, "LspSagaDiagnosticSource", { link = "Orange" })
hi(0, "LspSagaDiagnosticWarn", { link = "Yellow" })
hi(0, "LspSagaDocTruncateLine", { link = "Green" })
hi(0, "LspSagaErrorTrunCateLine", { link = "LspSagaDiagnosticError" })
hi(0, "LspSagaFinderSelection", { link = "Fg" })
hi(0, "LspSagaHintTrunCateLine", { link = "LspSagaDiagnosticHint" })
hi(0, "LspSagaHoverBorder", { link = "Green" })
hi(0, "LspSagaInfoTrunCateLine", { link = "LspSagaDiagnosticInfo" })
hi(0, "LspSagaRenameBorder", { link = "Purple" })
hi(0, "LspSagaRenamePromptPrefix", { link = "Blue" })
hi(0, "LspSagaShTruncateLine", { link = "Green" })
hi(0, "LspSagaSignatureHelpBorder", { link = "Green" })
hi(0, "LspSagaWarnTrunCateLine", { link = "LspSagaDiagnosticWarn" })
hi(0, "LspSemanticClass", { link = "TSType" })
hi(0, "LspSemanticComment", { link = "TSComment" })
hi(0, "LspSemanticEnum", { link = "TSType" })
hi(0, "LspSemanticEnumMember", { link = "TSProperty" })
hi(0, "LspSemanticEvents", { link = "TSLabel" })
hi(0, "LspSemanticFunction", { link = "TSFunction" })
hi(0, "LspSemanticInterface", { link = "TSType" })
hi(0, "LspSemanticKeyword", { link = "TSKeyword" })
hi(0, "LspSemanticMethod", { link = "TSMethod" })
hi(0, "LspSemanticModifier", { link = "TSOperator" })
hi(0, "LspSemanticNumber", { link = "TSNumber" })
hi(0, "LspSemanticOperator", { link = "TSOperator" })
hi(0, "LspSemanticParameter", { link = "TSParameter" })
hi(0, "LspSemanticProperty", { link = "TSProperty" })
hi(0, "LspSemanticRegexp", { link = "TSStringRegex" })
hi(0, "LspSemanticString", { link = "TSString" })
hi(0, "LspSemanticStruct", { link = "TSType" })
hi(0, "LspSemanticType", { link = "TSType" })
hi(0, "LspSemanticTypeParameter", { link = "TSType" })
hi(0, "LspSemanticVariable", { link = "TSVariable" })
hi(0, "LspSigActiveParameter", { link = "DiffAdd" })
hi(0, "LspSignatureActiveParameter", { link = "Search" })
hi(0, "LspWarningHighlight", { link = "WarningText" })
hi(0, "LspWarningVirtualText", { link = "VirtualTextWarning" })
hi(0, "Macro", { ctermfg = 108, fg = "#3ce451" })
hi(0, "MatchParen", { bg = "#512e28", ctermbg = 237 })
hi(0, "MatchParenCur", { bold = true })
hi(0, "MatchWord", { underline = true })
hi(0, "MatchWordCur", { underline = true })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { link = "LspSignatureActiveParameter" })
hi(0, "MiniCursorword", { link = "CurrentWord" })
hi(0, "MiniCursorwordCurrent", { link = "CurrentWord" })
hi(0, "MiniDepsChangeAdded", { link = "Added" })
hi(0, "MiniDepsChangeRemoved", { link = "Removed" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffChange" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { link = "GreenSign" })
hi(0, "MiniDiffSignChange", { link = "BlueSign" })
hi(0, "MiniDiffSignDelete", { link = "RedSign" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bg = "#512e28", bold = true, ctermbg = 237, ctermfg = 142, fg = "#bbd13d" })
hi(0, "MiniHipatternsFixme", { bg = "#fc356e", bold = true, ctermbg = 167, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniHipatternsHack", { bg = "#ffb670", bold = true, ctermbg = 214, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniHipatternsNote", { bg = "#67af76", bold = true, ctermbg = 109, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniHipatternsTodo", { bg = "#d8ad00", bold = true, ctermbg = 142, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniIconsAzure", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "MiniIconsBlue", { ctermfg = 109, fg = "#43c4ab" })
hi(0, "MiniIconsCyan", { ctermfg = 108, fg = "#3ce451" })
hi(0, "MiniIconsGreen", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "MiniIconsGrey", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "MiniIconsOrange", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "MiniIconsPurple", { ctermfg = 175, fg = "#ff7196" })
hi(0, "MiniIconsRed", { ctermfg = 167, fg = "#ff6939" })
hi(0, "MiniIconsYellow", { ctermfg = 214, fg = "#ffd450" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { link = "Grey" })
hi(0, "MiniJump", { link = "Search" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bold = true, ctermfg = 208, fg = "#ff9c44", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { ctermfg = 108, fg = "#3ce451", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, ctermfg = 214, fg = "#ffd450", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "DiffChange" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#512e28", ctermbg = 237, ctermfg = 109, fg = "#43c4ab" })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { link = "Orange" })
hi(0, "MiniStarterHeader", { link = "Yellow" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { link = "Grey" })
hi(0, "MiniStarterItemPrefix", { link = "Yellow" })
hi(0, "MiniStarterQuery", { link = "Blue" })
hi(0, "MiniStarterSection", { link = "Title" })
hi(0, "MiniStatuslineDevinfo", { bg = "#452723", ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "MiniStatuslineFileinfo", { bg = "#452723", ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "MiniStatuslineFilename", { bg = "#282828", ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "MiniStatuslineInactive", { bg = "#282828", ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "MiniStatuslineModeCommand", { bg = "#67af76", bold = true, ctermbg = 109, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniStatuslineModeInsert", { bg = "#d8ad00", bold = true, ctermbg = 106, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniStatuslineModeNormal", { bg = "#ce8957", bold = true, ctermbg = 246, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniStatuslineModeOther", { bg = "#ef61c3", bold = true, ctermbg = 175, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniStatuslineModeReplace", { bg = "#ffb670", bold = true, ctermbg = 172, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniStatuslineModeVisual", { bg = "#cf0056", bold = true, ctermbg = 124, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniSurround", { link = "IncSearch" })
hi(0, "MiniTablineCurrent", { bg = "#693d34", ctermbg = 239, ctermfg = 223, fg = "#ffeea4" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#512e28", ctermbg = 237, ctermfg = 245, fg = "#bb8c48" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#693d34", ctermbg = 239, ctermfg = 109, fg = "#43c4ab" })
hi(0, "MiniTablineModifiedHidden", { bg = "#512e28", ctermbg = 237, ctermfg = 245, fg = "#bb8c48" })
hi(0, "MiniTablineModifiedVisible", { bg = "#512e28", ctermbg = 237, ctermfg = 109, fg = "#43c4ab" })
hi(0, "MiniTablineTabpagesection", { bg = "#ce8957", bold = true, ctermbg = 246, ctermfg = 234, fg = "#1d3139" })
hi(0, "MiniTablineVisible", { bg = "#512e28", ctermbg = 237, ctermfg = 223, fg = "#ffeea4" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, ctermfg = 167, fg = "#ff6939" })
hi(0, "MiniTestPass", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "MiniTrailspace", { bg = "#fc356e", ctermbg = 167 })
hi(0, "ModeMsg", { bold = true, ctermfg = 223, fg = "#ffeea4" })
hi(0, "MoreMsg", { bold = true, ctermfg = 214, fg = "#ffd450" })
hi(0, "NavicIconsArray", { link = "Aqua" })
hi(0, "NavicIconsBoolean", { link = "Aqua" })
hi(0, "NavicIconsClass", { link = "Red" })
hi(0, "NavicIconsColor", { link = "Aqua" })
hi(0, "NavicIconsConstant", { link = "Blue" })
hi(0, "NavicIconsConstructor", { link = "Green" })
hi(0, "NavicIconsDefault", { link = "Aqua" })
hi(0, "NavicIconsEnum", { link = "Yellow" })
hi(0, "NavicIconsEnumMember", { link = "Purple" })
hi(0, "NavicIconsEvent", { link = "Orange" })
hi(0, "NavicIconsField", { link = "Green" })
hi(0, "NavicIconsFile", { link = "Green" })
hi(0, "NavicIconsFolder", { link = "Aqua" })
hi(0, "NavicIconsFunction", { link = "Green" })
hi(0, "NavicIconsInterface", { link = "Yellow" })
hi(0, "NavicIconsKey", { link = "Red" })
hi(0, "NavicIconsKeyword", { link = "Red" })
hi(0, "NavicIconsMethod", { link = "Green" })
hi(0, "NavicIconsModule", { link = "Purple" })
hi(0, "NavicIconsNamespace", { link = "Purple" })
hi(0, "NavicIconsNull", { link = "Aqua" })
hi(0, "NavicIconsNumber", { link = "Aqua" })
hi(0, "NavicIconsObject", { link = "Aqua" })
hi(0, "NavicIconsOperator", { link = "Orange" })
hi(0, "NavicIconsPackage", { link = "Purple" })
hi(0, "NavicIconsProperty", { link = "Blue" })
hi(0, "NavicIconsReference", { link = "Aqua" })
hi(0, "NavicIconsSnippet", { link = "Aqua" })
hi(0, "NavicIconsString", { link = "Aqua" })
hi(0, "NavicIconsStruct", { link = "Yellow" })
hi(0, "NavicIconsText", { link = "Fg" })
hi(0, "NavicIconsTypeParameter", { link = "Yellow" })
hi(0, "NavicIconsUnit", { link = "Purple" })
hi(0, "NavicIconsValue", { link = "Purple" })
hi(0, "NavicIconsVariable", { link = "Blue" })
hi(0, "NavicSeparator", { link = "Grey" })
hi(0, "NavicText", { link = "Fg" })
hi(0, "NeomakeError", { link = "ErrorText" })
hi(0, "NeomakeErrorSign", { link = "RedSign" })
hi(0, "NeomakeInfo", { link = "InfoText" })
hi(0, "NeomakeInfoSign", { link = "BlueSign" })
hi(0, "NeomakeMessage", { link = "HintText" })
hi(0, "NeomakeMessageSign", { link = "AquaSign" })
hi(0, "NeomakeVirtualtextError", { link = "VirtualTextError" })
hi(0, "NeomakeVirtualtextInfo", { link = "VirtualTextInfo" })
hi(0, "NeomakeVirtualtextMessag", { link = "VirtualTextHint" })
hi(0, "NeomakeVirtualtextWarning", { link = "VirtualTextWarning" })
hi(0, "NeomakeWarning", { link = "WarningText" })
hi(0, "NeomakeWarningSign", { link = "YellowSign" })
hi(0, "NeotestFailed", { link = "RedSign" })
hi(0, "NeotestPassed", { link = "GreenSign" })
hi(0, "NeotestRunning", { link = "YellowSign" })
hi(0, "NeotestSkipped", { link = "BlueSign" })
hi(0, "NoiceFormatProgressDone", { bg = "#d8ad00", fg = "#1d3139" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { ctermfg = 239, fg = "#775030" })
hi(0, "Normal", { bg = "#0f2324", ctermbg = 234, ctermfg = 223, fg = "#ffeea4" })
hi(0, "NormalFloat", { ctermbg = 237, ctermfg = 223, fg = "#ffeea4" })
hi(0, "NormalMode", { ctermfg = 246, fg = "#cea44f" })
hi(0, "NormalNC", { bg = "#0f2324", ctermbg = 234, ctermfg = 223, fg = "#ffeea4" })
hi(0, "NotifyBackground", { bg = "#0f2324", ctermbg = 234 })
hi(0, "NotifyDEBUGBorder", { link = "Grey" })
hi(0, "NotifyDEBUGIcon", { link = "Grey" })
hi(0, "NotifyDEBUGTitle", { link = "Grey" })
hi(0, "NotifyERRORBorder", { link = "Red" })
hi(0, "NotifyERRORIcon", { link = "Red" })
hi(0, "NotifyERRORTitle", { link = "Red" })
hi(0, "NotifyINFOBorder", { link = "Green" })
hi(0, "NotifyINFOIcon", { link = "Green" })
hi(0, "NotifyINFOTitle", { link = "Green" })
hi(0, "NotifyTRACEBorder", { link = "Purple" })
hi(0, "NotifyTRACEIcon", { link = "Purple" })
hi(0, "NotifyTRACETitle", { link = "Purple" })
hi(0, "NotifyWARNBorder", { link = "Yellow" })
hi(0, "NotifyWARNIcon", { link = "Yellow" })
hi(0, "NotifyWARNTitle", { link = "Yellow" })
hi(0, "Number", { ctermfg = 175, fg = "#ff7196" })
hi(0, "NvimInternalError", { bg = "#f90067", ctermbg = 9, ctermfg = 9, fg = "#ff5623" })
hi(0, "Operator", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "Orange", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "OrangeBold", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "OrangeItalic", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "OrangeSign", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "Pmenu", { ctermbg = 237, ctermfg = 223, fg = "#ffeea4" })
hi(0, "PmenuExtra", { ctermbg = 237, ctermfg = 246, fg = "#cea44f" })
hi(0, "PmenuKind", { bg = "#512e28", ctermbg = 237, ctermfg = 142, fg = "#bbd13d" })
hi(0, "PmenuSbar", { bg = "#512e28", ctermbg = 237 })
hi(0, "PmenuSel", { bg = "#ce8957", blend = 0, ctermbg = 246, ctermfg = 237, fg = "#5f3e28" })
hi(0, "PmenuThumb", { bg = "#9d6048", ctermbg = 243 })
hi(0, "PreCondit", { ctermfg = 175, fg = "#ff7196" })
hi(0, "PreProc", { ctermfg = 175, fg = "#ff7196" })
hi(0, "Purple", { ctermfg = 175, fg = "#ff7196" })
hi(0, "PurpleBold", { ctermfg = 175, fg = "#ff7196" })
hi(0, "PurpleItalic", { ctermfg = 175, fg = "#ff7196" })
hi(0, "PurpleSign", { ctermfg = 175, fg = "#ff7196" })
hi(0, "Question", { ctermfg = 214, fg = "#ffd450" })
hi(0, "QuickFixLine", { bold = true, ctermfg = 175, fg = "#ff7196" })
hi(0, "QuickScopePrimary", { ctermfg = 108, fg = "#3ce451", underline = true })
hi(0, "QuickScopeSecondary", { ctermfg = 109, fg = "#43c4ab", underline = true })
hi(0, "RainbowDelimiterBlue", { link = "Blue" })
hi(0, "RainbowDelimiterCyan", { link = "Aqua" })
hi(0, "RainbowDelimiterGreen", { link = "Green" })
hi(0, "RainbowDelimiterOrange", { link = "Orange" })
hi(0, "RainbowDelimiterRed", { link = "Red" })
hi(0, "RainbowDelimiterViolet", { link = "Purple" })
hi(0, "RainbowDelimiterYellow", { link = "Yellow" })
hi(0, "RainbowLevel0", { link = "Red" })
hi(0, "RainbowLevel1", { link = "Orange" })
hi(0, "RainbowLevel2", { link = "Yellow" })
hi(0, "RainbowLevel3", { link = "Green" })
hi(0, "RainbowLevel4", { link = "Aqua" })
hi(0, "RainbowLevel5", { link = "Blue" })
hi(0, "RainbowLevel6", { link = "Purple" })
hi(0, "RainbowLevel7", { link = "Yellow" })
hi(0, "RainbowLevel8", { link = "Green" })
hi(0, "Red", { ctermfg = 167, fg = "#ff6939" })
hi(0, "RedBold", { ctermfg = 167, fg = "#ff6939" })
hi(0, "RedItalic", { ctermfg = 167, fg = "#ff6939" })
hi(0, "RedSign", { ctermfg = 167, fg = "#ff6939" })
hi(0, "RedrawDebugClear", { bg = "#774c0d", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#335000", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#560024", ctermbg = 9, ctermfg = 0 })
hi(0, "ReferencesCount", { link = "Grey" })
hi(0, "Removed", { ctermfg = 167, fg = "#ff6939" })
hi(0, "Repeat", { ctermfg = 167, fg = "#ff6939" })
hi(0, "ReplaceMode", { link = "WarningMsg" })
hi(0, "Search", { bg = "#d8ad00", ctermbg = 106, ctermfg = 234, fg = "#1d3139" })
hi(0, "SelectMode", { link = "ErrorMsg" })
hi(0, "SignColumn", { ctermfg = 223, fg = "#ffeea4" })
hi(0, "SignatureMarkText", { link = "BlueSign" })
hi(0, "SignatureMarkerText", { link = "PurpleSign" })
hi(0, "SignifyLineAdd", { link = "DiffAdd" })
hi(0, "SignifyLineChange", { link = "DiffChange" })
hi(0, "SignifyLineChangeDelete", { link = "DiffChange" })
hi(0, "SignifyLineDelete", { link = "DiffDelete" })
hi(0, "SignifySignAdd", { link = "GreenSign" })
hi(0, "SignifySignChange", { link = "BlueSign" })
hi(0, "SignifySignChangeDelete", { link = "PurpleSign" })
hi(0, "SignifySignDelete", { link = "RedSign" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksBackdrop_000000", { bg = "#000000" })
hi(0, "SnacksImageMath", { fg = "#43c4ab" })
hi(0, "SnacksPicker", { link = "Normal" })
hi(0, "SnacksPickerBorder", { link = "Grey" })
hi(0, "SnacksPickerBufFlags", { link = "Blue" })
hi(0, "SnacksPickerDir", { link = "Comment" })
hi(0, "SnacksPickerFooter", { link = "SnacksPickerTitle" })
hi(0, "SnacksPickerInputCursorLine", { link = "Normal" })
hi(0, "SnacksPickerKeymapRhs", { link = "Normal" })
hi(0, "SnacksPickerListCursorLine", { link = "DiffAdd" })
hi(0, "SnacksPickerMatch", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "SnacksPickerPrompt", { link = "Orange" })
hi(0, "SnacksPickerTitle", { link = "Title" })
hi(0, "SnacksPickerToggle", { link = "CursorLine" })
hi(0, "SnacksPickerTotals", { link = "Grey" })
hi(0, "Sneak", { link = "Search" })
hi(0, "SneakLabel", { link = "Search" })
hi(0, "SneakLabelMask", { bg = "#d8ad00", ctermbg = 106, ctermfg = 106, fg = "#bbd13d" })
hi(0, "SneakScope", { link = "DiffText" })
hi(0, "Special", { ctermfg = 214, fg = "#ffd450" })
hi(0, "SpecialChar", { ctermfg = 214, fg = "#ffd450" })
hi(0, "SpecialComment", { ctermfg = 245, fg = "#bb8c48", italic = true })
hi(0, "SpecialKey", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "SpellBad", { sp = "#fb4934", undercurl = true })
hi(0, "SpellCap", { sp = "#83a598", undercurl = true })
hi(0, "SpellLocal", { sp = "#8ec07c", undercurl = true })
hi(0, "SpellRare", { sp = "#d3869b", undercurl = true })
hi(0, "Statement", { ctermfg = 167, fg = "#ff6939" })
hi(0, "StatusLine", { bg = "#452723", ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "StatusLineNC", { bg = "#282828", ctermbg = 235, ctermfg = 245, fg = "#bb8c48" })
hi(0, "StatusLineTerm", { bg = "#452723", ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "StatusLineTermNC", { bg = "#282828", ctermbg = 235, ctermfg = 245, fg = "#bb8c48" })
hi(0, "StorageClass", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "String", { ctermfg = 142, fg = "#bbd13d" })
hi(0, "Structure", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "Substitute", { bg = "#ffb670", ctermbg = 214, ctermfg = 234, fg = "#1d3139" })
hi(0, "SyntasticError", { link = "ErrorText" })
hi(0, "SyntasticErrorLine", { link = "ErrorLine" })
hi(0, "SyntasticErrorSign", { link = "RedSign" })
hi(0, "SyntasticWarning", { link = "WarningText" })
hi(0, "SyntasticWarningLine", { link = "WarningLine" })
hi(0, "SyntasticWarningSign", { link = "YellowSign" })
hi(0, "TSAnnotation", { link = "Purple" })
hi(0, "TSAttribute", { link = "Purple" })
hi(0, "TSBoolean", { link = "Purple" })
hi(0, "TSCharacter", { link = "Aqua" })
hi(0, "TSCharacterSpecial", { link = "SpecialChar" })
hi(0, "TSComment", { link = "Comment" })
hi(0, "TSConditional", { link = "Red" })
hi(0, "TSConstBuiltin", { link = "PurpleItalic" })
hi(0, "TSConstMacro", { link = "PurpleItalic" })
hi(0, "TSConstant", { link = "Fg" })
hi(0, "TSConstructor", { link = "GreenBold" })
hi(0, "TSDanger", { bg = "#fc356e", bold = true, ctermbg = 167, ctermfg = 234, fg = "#1d3139" })
hi(0, "TSDebug", { link = "Debug" })
hi(0, "TSDefine", { link = "Define" })
hi(0, "TSEmphasis", { italic = true })
hi(0, "TSEnvironment", { link = "Macro" })
hi(0, "TSEnvironmentName", { link = "Type" })
hi(0, "TSError", { link = "Error" })
hi(0, "TSException", { link = "Red" })
hi(0, "TSField", { link = "Blue" })
hi(0, "TSFloat", { link = "Purple" })
hi(0, "TSFuncBuiltin", { link = "GreenBold" })
hi(0, "TSFuncMacro", { link = "GreenBold" })
hi(0, "TSFunction", { link = "GreenBold" })
hi(0, "TSFunctionCall", { link = "GreenBold" })
hi(0, "TSInclude", { link = "Red" })
hi(0, "TSKeyword", { link = "Red" })
hi(0, "TSKeywordFunction", { link = "Red" })
hi(0, "TSKeywordOperator", { link = "Orange" })
hi(0, "TSKeywordReturn", { link = "Red" })
hi(0, "TSLabel", { link = "Orange" })
hi(0, "TSLiteral", { link = "String" })
hi(0, "TSMath", { link = "Blue" })
hi(0, "TSMethod", { link = "GreenBold" })
hi(0, "TSMethodCall", { link = "GreenBold" })
hi(0, "TSModuleInfoBad", { link = "Red" })
hi(0, "TSModuleInfoGood", { link = "Green" })
hi(0, "TSNamespace", { link = "YellowItalic" })
hi(0, "TSNone", { link = "Fg" })
hi(0, "TSNote", { bg = "#d8ad00", bold = true, ctermbg = 142, ctermfg = 234, fg = "#1d3139" })
hi(0, "TSNumber", { link = "Purple" })
hi(0, "TSOperator", { link = "Orange" })
hi(0, "TSParameter", { link = "Fg" })
hi(0, "TSParameterReference", { link = "Fg" })
hi(0, "TSPreProc", { link = "PreProc" })
hi(0, "TSProperty", { link = "Blue" })
hi(0, "TSPunctBracket", { link = "Fg" })
hi(0, "TSPunctDelimiter", { link = "Grey" })
hi(0, "TSPunctSpecial", { link = "Blue" })
hi(0, "TSRepeat", { link = "Red" })
hi(0, "TSStorageClass", { link = "Orange" })
hi(0, "TSStorageClassLifetime", { link = "Orange" })
hi(0, "TSStrike", { link = "Grey" })
hi(0, "TSString", { link = "Aqua" })
hi(0, "TSStringEscape", { link = "Green" })
hi(0, "TSStringRegex", { link = "Green" })
hi(0, "TSStringSpecial", { link = "SpecialChar" })
hi(0, "TSStrong", { bold = true })
hi(0, "TSSymbol", { link = "Fg" })
hi(0, "TSTag", { link = "Orange" })
hi(0, "TSTagAttribute", { link = "Green" })
hi(0, "TSTagDelimiter", { link = "Green" })
hi(0, "TSText", { link = "Green" })
hi(0, "TSTextReference", { link = "Constant" })
hi(0, "TSTitle", { link = "Title" })
hi(0, "TSTodo", { link = "Todo" })
hi(0, "TSType", { link = "YellowItalic" })
hi(0, "TSTypeBuiltin", { link = "YellowItalic" })
hi(0, "TSTypeDefinition", { link = "YellowItalic" })
hi(0, "TSTypeQualifier", { link = "Orange" })
hi(0, "TSURI", { ctermfg = 109, fg = "#43c4ab", underline = true })
hi(0, "TSUnderline", { underline = true })
hi(0, "TSVariable", { link = "Fg" })
hi(0, "TSVariableBuiltin", { link = "PurpleItalic" })
hi(0, "TSWarning", { bg = "#ffb670", bold = true, ctermbg = 214, ctermfg = 234, fg = "#1d3139" })
hi(0, "TabLine", { bg = "#452723", ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "TabLineFill", { bg = "#0f2324", ctermbg = 234, ctermfg = 246, fg = "#cea44f" })
hi(0, "TabLineSel", { bg = "#ce8957", ctermbg = 246, ctermfg = 234, fg = "#1d3139" })
hi(0, "Tag", { ctermfg = 208, fg = "#ff9c44" })
hi(0, "TargetFileName", { link = "Grey" })
hi(0, "TelescopeBorder", { link = "Grey" })
hi(0, "TelescopeMatching", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "TelescopePromptPrefix", { link = "Orange" })
hi(0, "TelescopeSelection", { link = "DiffAdd" })
hi(0, "Terminal", { bg = "#0f2324", ctermbg = 234, ctermfg = 223, fg = "#ffeea4" })
hi(0, "TerminalMode", { link = "Operator" })
hi(0, "TerminalNormalMode", { ctermfg = 246, fg = "#cea44f" })
hi(0, "TinyInlineDiagnosticVirtualTextArrow", { bg = "#282828", fg = "#775030" })
hi(0, "TinyInlineDiagnosticVirtualTextArrowNoBg", { fg = "#775030" })
hi(0, "TinyInlineDiagnosticVirtualTextBg", { bg = "#282828" })
hi(0, "TinyInlineDiagnosticVirtualTextError", { bg = "#3f0014", fg = "#ff6939" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorCursorLine", { bg = "#282828", fg = "#ff6939" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixError", { bg = "#3f0014", fg = "#ff6939" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixHint", { bg = "#312500", fg = "#ff6939" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixInfo", { bg = "#152718", fg = "#ff6939" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixWarn", { bg = "#402505", fg = "#ff6939" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorNoBg", { fg = "#ff6939" })
hi(0, "TinyInlineDiagnosticVirtualTextHint", { bg = "#312500", fg = "#bbd13d" })
hi(0, "TinyInlineDiagnosticVirtualTextHintCursorLine", { bg = "#282828", fg = "#bbd13d" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixError", { bg = "#3f0014", fg = "#bbd13d" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixHint", { bg = "#312500", fg = "#bbd13d" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixInfo", { bg = "#152718", fg = "#bbd13d" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixWarn", { bg = "#402505", fg = "#bbd13d" })
hi(0, "TinyInlineDiagnosticVirtualTextHintNoBg", { fg = "#bbd13d" })
hi(0, "TinyInlineDiagnosticVirtualTextInfo", { bg = "#152718", fg = "#43c4ab" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoCursorLine", { bg = "#282828", fg = "#43c4ab" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixError", { bg = "#3f0014", fg = "#43c4ab" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixHint", { bg = "#312500", fg = "#43c4ab" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixInfo", { bg = "#152718", fg = "#43c4ab" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixWarn", { bg = "#402505", fg = "#43c4ab" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoNoBg", { fg = "#43c4ab" })
hi(0, "TinyInlineDiagnosticVirtualTextWarn", { bg = "#402505", fg = "#ffd450" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnCursorLine", { bg = "#282828", fg = "#ffd450" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixError", { bg = "#3f0014", fg = "#ffd450" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixHint", { bg = "#312500", fg = "#ffd450" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixInfo", { bg = "#152718", fg = "#ffd450" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixWarn", { bg = "#402505", fg = "#ffd450" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnNoBg", { fg = "#ffd450" })
hi(0, "TinyInlineInvDiagnosticVirtualTextError", { bg = "#282828", fg = "#4d1a0c" })
hi(0, "TinyInlineInvDiagnosticVirtualTextErrorNoBg", { fg = "#4d1a0c" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHint", { bg = "#282828", fg = "#323812" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHintNoBg", { fg = "#323812" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfo", { bg = "#282828", fg = "#18372f" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfoNoBg", { fg = "#18372f" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarn", { bg = "#282828", fg = "#443910" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarnNoBg", { fg = "#443910" })
hi(0, "Title", { bold = true, ctermfg = 208, fg = "#ff9c44" })
hi(0, "Todo", { bg = "#67af76", bold = true, ctermbg = 109, ctermfg = 234, fg = "#1d3139" })
hi(0, "ToolbarButton", { bg = "#ce8957", ctermbg = 246, ctermfg = 234, fg = "#1d3139" })
hi(0, "ToolbarLine", { bg = "#512e28", ctermbg = 237, ctermfg = 223, fg = "#ffeea4" })
hi(0, "TroubleCode", { link = "Grey" })
hi(0, "TroubleSource", { link = "Grey" })
hi(0, "TroubleText", { link = "Fg" })
hi(0, "Type", { ctermfg = 214, fg = "#ffd450" })
hi(0, "Typedef", { ctermfg = 167, fg = "#ff6939" })
hi(0, "VMCursor", { bg = "#693d34", ctermbg = 239, ctermfg = 109, fg = "#43c4ab" })
hi(0, "VertSplit", { ctermfg = 239, fg = "#775030" })
hi(0, "VirtualTextError", { link = "Grey" })
hi(0, "VirtualTextHint", { link = "Grey" })
hi(0, "VirtualTextInfo", { link = "Grey" })
hi(0, "VirtualTextWarning", { link = "Grey" })
hi(0, "Visual", { bg = "#512e28", ctermbg = 237 })
hi(0, "VisualMode", { link = "String" })
hi(0, "VisualNOS", { bg = "#512e28", ctermbg = 237 })
hi(0, "WarningFloat", { ctermfg = 214, fg = "#ffd450" })
hi(0, "WarningMsg", { bold = true, ctermfg = 214, fg = "#ffd450" })
hi(0, "WarningText", { sp = "#fabd2f", undercurl = true })
hi(0, "WhichKey", { link = "Red" })
hi(0, "WhichKeyDesc", { link = "Blue" })
hi(0, "WhichKeyGroup", { link = "Yellow" })
hi(0, "WhichKeyIconAzure", { link = "MiniIconsAzure" })
hi(0, "WhichKeyIconBlue", { link = "MiniIconsBlue" })
hi(0, "WhichKeyIconCyan", { link = "MiniIconsCyan" })
hi(0, "WhichKeyIconGreen", { link = "MiniIconsGreen" })
hi(0, "WhichKeyIconGrey", { link = "MiniIconsGrey" })
hi(0, "WhichKeyIconOrange", { link = "MiniIconsOrange" })
hi(0, "WhichKeyIconPurple", { link = "MiniIconsPurple" })
hi(0, "WhichKeyIconRed", { link = "MiniIconsRed" })
hi(0, "WhichKeyIconYellow", { link = "MiniIconsYellow" })
hi(0, "WhichKeySeperator", { link = "Green" })
hi(0, "Whitespace", { ctermfg = 239, fg = "#775030" })
hi(0, "WinBar", { bg = "#452723", bold = true, ctermbg = 235, ctermfg = 246, fg = "#cea44f" })
hi(0, "WinBarNC", { bg = "#282828", ctermbg = 235, ctermfg = 245, fg = "#bb8c48" })
hi(0, "WinSeparator", { link = "VertSplit" })
hi(0, "YcmErrorLine", { link = "ErrorLine" })
hi(0, "YcmErrorSection", { link = "ErrorText" })
hi(0, "YcmErrorSign", { link = "RedSign" })
hi(0, "YcmErrorText", { link = "VirtualTextError" })
hi(0, "YcmInlayHint", { link = "InlayHints" })
hi(0, "YcmWarningLine", { link = "WarningLine" })
hi(0, "YcmWarningSection", { link = "WarningText" })
hi(0, "YcmWarningSign", { link = "YellowSign" })
hi(0, "YcmWarningText", { link = "VirtualTextWarning" })
hi(0, "Yellow", { ctermfg = 214, fg = "#ffd450" })
hi(0, "YellowBold", { ctermfg = 214, fg = "#ffd450" })
hi(0, "YellowItalic", { ctermfg = 214, fg = "#ffd450" })
hi(0, "YellowSign", { ctermfg = 214, fg = "#ffd450" })
hi(0, "agitDate", { link = "Green" })
hi(0, "agitDiffAdd", { link = "Green" })
hi(0, "agitDiffHeader", { link = "Purple" })
hi(0, "agitDiffRemove", { link = "Red" })
hi(0, "agitHead", { link = "Orange" })
hi(0, "agitRef", { link = "Aqua" })
hi(0, "agitRemote", { link = "Red" })
hi(0, "agitStatAdded", { link = "Green" })
hi(0, "agitStatFile", { link = "Blue" })
hi(0, "agitStatMessage", { link = "Orange" })
hi(0, "agitStatRemoved", { link = "Red" })
hi(0, "agitTag", { link = "Orange" })
hi(0, "agitTree", { link = "Grey" })
hi(0, "debugBreakpoint", { bg = "#fc356e", ctermbg = 167, ctermfg = 234, fg = "#1d3139" })
hi(0, "debugPC", { bg = "#d8ad00", ctermbg = 142, ctermfg = 234, fg = "#1d3139" })
hi(0, "deniteInput", { bg = "#512e28", bold = true, ctermbg = 237, ctermfg = 142, fg = "#bbd13d" })
hi(0, "deniteMatchedChar", { bold = true, ctermfg = 142, fg = "#bbd13d" })
hi(0, "deniteMatchedRange", { bold = true, ctermfg = 142, fg = "#bbd13d", underline = true })
hi(0, "deniteSelectedLin", { link = "Green" })
hi(0, "deniteStatusLineNumber", { bg = "#512e28", ctermbg = 237, ctermfg = 175, fg = "#ff7196" })
hi(0, "deniteStatusLinePath", { bg = "#512e28", ctermbg = 237, ctermfg = 223, fg = "#ffeea4" })
hi(0, "diffAdded", { link = "Added" })
hi(0, "diffChanged", { link = "Changed" })
hi(0, "diffFile", { link = "Aqua" })
hi(0, "diffIndexLine", { link = "Purple" })
hi(0, "diffLine", { link = "Grey" })
hi(0, "diffNewFile", { link = "Orange" })
hi(0, "diffOldFile", { link = "Yellow" })
hi(0, "diffRemoved", { link = "Removed" })
hi(0, "healthError", { link = "Red" })
hi(0, "healthSuccess", { link = "Green" })
hi(0, "healthWarning", { link = "Yellow" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlBoldUnderline", { bold = true, underline = true })
hi(0, "htmlBoldUnderlineItalic", { bold = true, italic = true, underline = true })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlStrike", { strikethrough = true })
hi(0, "htmlUnderline", { underline = true })
hi(0, "htmlUnderlineItalic", { italic = true, underline = true })
hi(0, "iCursor", { link = "Cursor" })
hi(0, "illuminatedWord", { link = "CurrentWord" })
hi(0, "lCursor", { reverse = true })
hi(0, "lspInlayHintsParameter", { link = "InlayHints" })
hi(0, "lspInlayHintsType", { link = "InlayHints" })
hi(0, "lspReference", { link = "CurrentWord" })
hi(0, "luaBraces", { link = "Fg" })
hi(0, "luaBuiltIn", { link = "Purple" })
hi(0, "luaDocTag", { link = "Green" })
hi(0, "luaEllipsis", { link = "Orange" })
hi(0, "luaFunc", { link = "GreenBold" })
hi(0, "luaFuncArgName", { link = "Blue" })
hi(0, "luaFuncCall", { link = "GreenBold" })
hi(0, "luaFuncTable", { link = "Yellow" })
hi(0, "luaFunction", { link = "Aqua" })
hi(0, "luaIn", { link = "RedItalic" })
hi(0, "luaLabel", { link = "Purple" })
hi(0, "luaLocal", { link = "Orange" })
hi(0, "luaNoise", { link = "Grey" })
hi(0, "luaSpecialValue", { link = "GreenBold" })
hi(0, "luaTSConstructor", { link = "luaBraces" })
hi(0, "luaTable", { link = "Fg" })
hi(0, "multiple_cursors_cursor", { link = "Cursor" })
hi(0, "multiple_cursors_visual", { link = "Visual" })
hi(0, "phpClass", { link = "Orange" })
hi(0, "phpComparison", { link = "Orange" })
hi(0, "phpDefine", { link = "OrangeItalic" })
hi(0, "phpFunction", { link = "GreenBold" })
hi(0, "phpInterpSimpleCurly", { link = "Yellow" })
hi(0, "phpMemberSelector", { link = "Green" })
hi(0, "phpMethod", { link = "GreenBold" })
hi(0, "phpMethodsVar", { link = "Aqua" })
hi(0, "phpNowDoc", { link = "Green" })
hi(0, "phpParent", { link = "Fg" })
hi(0, "phpSpecialFunction", { link = "GreenBold" })
hi(0, "phpStructure", { link = "RedItalic" })
hi(0, "phpSuperglobals", { link = "Purple" })
hi(0, "phpVarSelector", { link = "Blue" })
hi(0, "vCursor", { link = "Cursor" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#504945"
g.terminal_color_1 = "#fb4934"
g.terminal_color_2 = "#b8bb26"
g.terminal_color_3 = "#fabd2f"
g.terminal_color_4 = "#83a598"
g.terminal_color_5 = "#d3869b"
g.terminal_color_6 = "#8ec07c"
g.terminal_color_7 = "#ebdbb2"
g.terminal_color_8 = "#504945"
g.terminal_color_9 = "#fb4934"
g.terminal_color_10 = "#b8bb26"
g.terminal_color_11 = "#fabd2f"
g.terminal_color_12 = "#83a598"
g.terminal_color_13 = "#d3869b"
g.terminal_color_14 = "#8ec07c"
g.terminal_color_15 = "#ebdbb2"
