-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "nightfox-2.0"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@attribute.css", { fg = "#ffd65c", italic = true })
hi(0, "@attribute.typescript", { link = "Function" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@class.constructor", { fg = "#22c4dd", italic = true })
hi(0, "@class.field.function", { link = "Function" })
hi(0, "@command", { fg = "#ffd65c", nocombine = true })
hi(0, "@comment.error", { bg = "#c5507f", fg = "#002d32" })
hi(0, "@comment.note", { bg = "#7d98d7", fg = "#002d32" })
hi(0, "@comment.todo", { bg = "#7cb2a1", fg = "#002d32" })
hi(0, "@comment.warning", { bg = "#d1c476", fg = "#002d32" })
hi(0, "@conditional.lua", { link = "Statement" })
hi(0, "@constant.builtin", { link = "Constant" })
hi(0, "@constant.identifier", { link = "Constant" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#81d78c" })
hi(0, "@constructor.javascript", { fg = "#22c4dd", nocombine = true })
hi(0, "@constructor.lua", { fg = "#1dcbce" })
hi(0, "@constructor.python", { fg = "#ffd65c", italic = true })
hi(0, "@constructor.typescript", { fg = "#22c4dd", nocombine = true })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@field", { fg = "#c3f6a0" })
hi(0, "@field.rust", { fg = "#1dcbce" })
hi(0, "@function.builtin", { fg = "#c36901" })
hi(0, "@function.builtin.bash", { fg = "#ffd65c", italic = true })
hi(0, "@function.builtin.lua", { fg = "#22c4dd", italic = true })
hi(0, "@function.builtin.python", { fg = "#ffd65c", nocombine = true })
hi(0, "@function.macro", { fg = "#c36901" })
hi(0, "@include.identifier", { fg = "#c3ecef", nocombine = true })
hi(0, "@keyword.abort", { link = "Statement" })
hi(0, "@keyword.command", { fg = "#ffd65c", nocombine = true })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.bash", { link = "Statement" })
hi(0, "@keyword.conditional.lua", { link = "Statement" })
hi(0, "@keyword.conditional.python", { link = "Statement" })
hi(0, "@keyword.conditional.r", { link = "Statement" })
hi(0, "@keyword.conditional.ternary", { link = "Conditional" })
hi(0, "@keyword.coroutine", { link = "Statement" })
hi(0, "@keyword.default", { link = "Statement" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.exception.python", { link = "Statement" })
hi(0, "@keyword.export", { link = "Statement" })
hi(0, "@keyword.extends", { link = "Statement" })
hi(0, "@keyword.function", { fg = "#ef449f" })
hi(0, "@keyword.function.lua", { link = "Statement" })
hi(0, "@keyword.function.r", { link = "Statement" })
hi(0, "@keyword.function.return", { link = "Statement" })
hi(0, "@keyword.function.vim", { link = "Statement" })
hi(0, "@keyword.if.vim", { link = "Statement" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.jsdoc", { fg = "#ff78a2", nocombine = true })
hi(0, "@keyword.lua.break", { link = "Statement" })
hi(0, "@keyword.operator", { fg = "#ff78a2" })
hi(0, "@keyword.operator.python", { link = "Statement" })
hi(0, "@keyword.operator.typescript", { fg = "#aae174" })
hi(0, "@keyword.repeat", { link = "Statement" })
hi(0, "@keyword.return", { link = "Statement" })
hi(0, "@keyword.static", { link = "Statement" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label", { fg = "#aae174" })
hi(0, "@label.json", { fg = "#00c3d1" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.mod.global.lua", { fg = "#ffd65c" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { fg = "#ffd65c", nocombine = true })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.interface", { fg = "#ffd65c", nocombine = true })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { fg = "#bbeaec" })
hi(0, "@lsp.type.property", { fg = "#c3f6a0" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", { fg = "#bbeaec" })
hi(0, "@lsp.type.variable.lua", { link = "Variable" })
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = "#9ae2e0" })
hi(0, "@markup.heading", { link = "Title" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#061628", fg = "#001f1f", nocombine = true, sp = "#d6deeb", underdouble = true })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#061628", fg = "#001f1f", nocombine = true, sp = "#d6deeb", underline = true })
hi(0, "@markup.italic", { link = "Italic" })
hi(0, "@markup.link", { bold = true, fg = "#ef449f" })
hi(0, "@markup.link.label", { link = "Special" })
hi(0, "@markup.link.url", { fg = "#e4c15f", italic = true, underline = true })
hi(0, "@markup.list", { fg = "#89e192" })
hi(0, "@markup.list.checked", { fg = "#adb521" })
hi(0, "@markup.list.unchecked", { fg = "#f2c217" })
hi(0, "@markup.math", { fg = "#00c3d1" })
hi(0, "@markup.quote", { fg = "#1dcbce" })
hi(0, "@markup.raw", { fg = "#81d78c", italic = true })
hi(0, "@markup.raw.block", { fg = "#ff6876" })
hi(0, "@markup.strikethrough", { fg = "#9ae2e0", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#a85900" })
hi(0, "@markup.underline", { link = "Underline" })
hi(0, "@module", { fg = "#89e192" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@module.r", { link = "@type.class" })
hi(0, "@module.vim", { link = "@type.class" })
hi(0, "@namespace", { fg = "#89e192" })
hi(0, "@namespace.vim", { fg = "#64dec3", italic = true })
hi(0, "@nowl.constant.builtin.na.r", { fg = "#dd8200", italic = true })
hi(0, "@nowl.constant.builtin.null", { fg = "#dd8200" })
hi(0, "@nowl.indentChar", { fg = "#00474e", nocombine = true })
hi(0, "@nowl.indentChar.active", { fg = "#00afae", nocombine = true })
hi(0, "@nowl.keyword.break", { link = "Statement" })
hi(0, "@nowl.keyword.operator.new.javascript", { fg = "#aae174" })
hi(0, "@nowl.punctuation.string.delimiter", { fg = "#fbf1b1", nocombine = true })
hi(0, "@nowl.variable.object", { fg = "#aae174", italic = true })
hi(0, "@nowl.variable.parameter.option.bash", { fg = "#22c4dd" })
hi(0, "@nowl.visual.active", { bg = "#243954" })
hi(0, "@nowl.visual.inactive", { bg = "#25305f" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@object.key", { link = "Statement" })
hi(0, "@object.property", { fg = "#fff4d5", italic = true })
hi(0, "@operator.lua", { fg = "#aae174" })
hi(0, "@operator.of", { fg = "#aae174" })
hi(0, "@operator.toml", { fg = "#c3ecef" })
hi(0, "@parameter", { fg = "#bbeaec" })
hi(0, "@parameter.jsdoc", { fg = "#64dec3" })
hi(0, "@property", { fg = "#c3f6a0" })
hi(0, "@property.css", { fg = "#93d67d" })
hi(0, "@property.toml", { fg = "#ff78a2", nocombine = true })
hi(0, "@punctuation.accessor", { link = "Statement" })
hi(0, "@punctuation.bracket", { fg = "#1dcbce" })
hi(0, "@punctuation.delimiter", { fg = "#1dcbce" })
hi(0, "@punctuation.special", { fg = "#89e192" })
hi(0, "@punctuation.special.bash", { fg = "#ffd65c" })
hi(0, "@string.escape", { bold = true, fg = "#fcca18" })
hi(0, "@string.json", { fg = "#ff6c89" })
hi(0, "@string.regex", { fg = "#22c4dd", nocombine = true })
hi(0, "@string.regexFlags", { fg = "#00bdbd", nocombine = true })
hi(0, "@string.regexp", { fg = "#fcca18" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.url", { fg = "#e4c15f", italic = true, underline = true })
hi(0, "@tag", { fg = "#ef449f" })
hi(0, "@tag.attribute", { fg = "#ffd65c", italic = true })
hi(0, "@tag.builtin", { fg = "#caf8b1", nocombine = true })
hi(0, "@tag.component.jsx", { fg = "#d4a800", nocombine = true })
hi(0, "@tag.css", { fg = "#d48d00", nocombine = true })
hi(0, "@tag.delimiter", { fg = "#aae174" })
hi(0, "@text", { fg = "#9ae2e0" })
hi(0, "@text.danger", { bg = "#c5507f", fg = "#002d32" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#ff78a2", italic = true })
hi(0, "@text.literal", { fg = "#ffd65c" })
hi(0, "@text.math", { fg = "#00c3d1" })
hi(0, "@text.note", { bg = "#7d98d7", fg = "#002d32" })
hi(0, "@text.reference", { bold = true, fg = "#ef449f" })
hi(0, "@text.strike", { fg = "#9ae2e0", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#ffd65c" })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.todo", { bg = "#d8ddeb", fg = "#001f1f" })
hi(0, "@text.todo.checked", { fg = "#adb521" })
hi(0, "@text.todo.unchecked", { fg = "#f2c217" })
hi(0, "@text.underline", { link = "Underline" })
hi(0, "@text.uri", { fg = "#f5943c", underline = true })
hi(0, "@text.warning", { bg = "#d1c476", fg = "#002d32" })
hi(0, "@type", { fg = "#f2d891", italic = true })
hi(0, "@type.builtin", { fg = "#ffd65c" })
hi(0, "@type.builtin.python", { fg = "#ffd65c", nocombine = true })
hi(0, "@type.class", { fg = "#f2d891", nocombine = true })
hi(0, "@type.inheritedClass", { fg = "#ffd65c", nocombine = true })
hi(0, "@type.python", { fg = "#f2d891", nocombine = true })
hi(0, "@type.toml", { fg = "#ffd65c", italic = true })
hi(0, "@type.typescript", { fg = "#f2d891", nocombine = true })
hi(0, "@variable", { fg = "#bbeaec" })
hi(0, "@variable.builtin", { fg = "#aae174" })
hi(0, "@variable.builtin.vim", { fg = "#aae174", italic = true })
hi(0, "@variable.lua", { link = "Variable" })
hi(0, "@variable.member", { fg = "#01b3c1" })
hi(0, "@variable.parameter", { fg = "#89e192" })
hi(0, "@variable.parameter.bash", { fg = "#f0cc66" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "@variable.parameter.python", { fg = "#aae174" })
hi(0, "@variable.vim", { link = "Variable" })
hi(0, "Added", { ctermfg = 10, fg = "#f9e876" })
hi(0, "AerialGuide", { fg = "#005f67" })
hi(0, "AerialLine", { link = "Search" })
hi(0, "AlphaButtons", { fg = "#81d78c" })
hi(0, "AlphaFooter", { fg = "#01b3c1" })
hi(0, "AlphaHeader", { fg = "#00c3d1" })
hi(0, "AlphaHeaderLabel", { fg = "#dfb637" })
hi(0, "AlphaShortcut", { fg = "#dfb637" })
hi(0, "AvanteAnnotation", { link = "Comment" })
hi(0, "AvanteButtonDanger", { bg = "#adb1bf", fg = "#002c35" })
hi(0, "AvanteButtonDangerHover", { bg = "#de6b86", fg = "#002c35" })
hi(0, "AvanteButtonDefault", { bg = "#adb1bf", fg = "#002c35" })
hi(0, "AvanteButtonDefaultHover", { bg = "#9cd295", fg = "#002c35" })
hi(0, "AvanteButtonPrimary", { bg = "#adb1bf", fg = "#002c35" })
hi(0, "AvanteButtonPrimaryHover", { bg = "#5ab4ca", fg = "#002c35" })
hi(0, "AvanteCommentFg", { fg = "#508656" })
hi(0, "AvanteConfirmTitle", { bg = "#de6b86", fg = "#002c35" })
hi(0, "AvanteConflictCurrent", { bg = "#552c36", bold = true })
hi(0, "AvanteConflictCurrentLabel", { bg = "#6e3946" })
hi(0, "AvanteConflictIncoming", { bg = "#344655", bold = true })
hi(0, "AvanteConflictIncomingLabel", { bg = "#425b6d" })
hi(0, "AvanteInlineHint", { link = "Keyword" })
hi(0, "AvantePopupHint", { link = "NormalFloat" })
hi(0, "AvantePromptInputBorder", { link = "NormalFloat" })
hi(0, "AvanteReversedNormal", { bg = "#d8ddeb", fg = "#001f1f" })
hi(0, "AvanteReversedSubtitle", { fg = "#61c38a" })
hi(0, "AvanteReversedThirdTitle", { fg = "#004852" })
hi(0, "AvanteReversedTitle", { fg = "#e2b300" })
hi(0, "AvanteSidebarNormal", { link = "NormalFloat" })
hi(0, "AvanteSidebarWinHorizontalSeparator", { bg = "#061628", fg = "#4f0059" })
hi(0, "AvanteSidebarWinSeparator", { bg = "#061628", fg = "#001f1f" })
hi(0, "AvanteStateSpinnerCompacting", { bg = "#b97de9", fg = "#002c35" })
hi(0, "AvanteStateSpinnerFailed", { bg = "#de6b86", fg = "#002c35" })
hi(0, "AvanteStateSpinnerGenerating", { bg = "#9da2f6", fg = "#002c35" })
hi(0, "AvanteStateSpinnerSearching", { bg = "#b97de9", fg = "#002c35" })
hi(0, "AvanteStateSpinnerSucceeded", { bg = "#89c685", fg = "#002c35" })
hi(0, "AvanteStateSpinnerThinking", { bg = "#b97de9", fg = "#002c35" })
hi(0, "AvanteStateSpinnerToolCalling", { bg = "#5ab4ca", fg = "#002c35" })
hi(0, "AvanteSubtitle", { bg = "#5ab4ca", fg = "#002c35" })
hi(0, "AvanteSuggestion", { link = "Comment" })
hi(0, "AvanteTaskCompleted", { bg = "#061628", fg = "#e2b300" })
hi(0, "AvanteThinking", { bg = "#061628", fg = "#ff5a82" })
hi(0, "AvanteThirdTitle", { bg = "#373a45", fg = "#45c9de" })
hi(0, "AvanteTitle", { bg = "#89c685", fg = "#002c35" })
hi(0, "AvanteToBeDeleted", { bg = "#fecbd3", strikethrough = true })
hi(0, "AvanteToBeDeletedWOStrikethrough", { bg = "#552c36" })
hi(0, "BlinkCmpDoc", { bg = "#151924", fg = "#9ae2e0" })
hi(0, "BlinkCmpDocBorder", { bg = "#151924", fg = "#004850" })
hi(0, "BlinkCmpKindClass", { link = "Type" })
hi(0, "BlinkCmpKindConstant", { link = "@constant" })
hi(0, "BlinkCmpKindConstructor", { link = "Function" })
hi(0, "BlinkCmpKindDefault", { fg = "#1dcbce" })
hi(0, "BlinkCmpKindEnum", { link = "Constant" })
hi(0, "BlinkCmpKindEnumMember", { link = "@field" })
hi(0, "BlinkCmpKindEvent", { link = "Constant" })
hi(0, "BlinkCmpKindField", { link = "@field" })
hi(0, "BlinkCmpKindFunction", { link = "Function" })
hi(0, "BlinkCmpKindInterface", { link = "Constant" })
hi(0, "BlinkCmpKindKeyword", { link = "Identifier" })
hi(0, "BlinkCmpKindMethod", { link = "Function" })
hi(0, "BlinkCmpKindModule", { link = "@namespace" })
hi(0, "BlinkCmpKindOperator", { link = "Operator" })
hi(0, "BlinkCmpKindProperty", { link = "@property" })
hi(0, "BlinkCmpKindReference", { link = "Keyword" })
hi(0, "BlinkCmpKindSnippet", { fg = "#1dcbce" })
hi(0, "BlinkCmpKindStruct", { link = "Type" })
hi(0, "BlinkCmpKindTypeParameter", { link = "@field" })
hi(0, "BlinkCmpKindUnit", { link = "Constant" })
hi(0, "BlinkCmpKindValue", { link = "Keyword" })
hi(0, "BlinkCmpKindVariable", { link = "@variable" })
hi(0, "BlinkCmpLabel", { fg = "#9ae2e0" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#0198a6", strikethrough = true })
hi(0, "BlinkCmpLabelDetail", { link = "Comment" })
hi(0, "BlinkCmpLabelMatch", { fg = "#00c3d1" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#dd8200", italic = true })
hi(0, "BufferCurrent", { bg = "#75819c", fg = "#9ae2e0" })
hi(0, "BufferCurrentIndex", { bg = "#75819c", fg = "#01b3c1" })
hi(0, "BufferCurrentMod", { bg = "#75819c", fg = "#f2c217" })
hi(0, "BufferCurrentSign", { bg = "#75819c", fg = "#01b3c1" })
hi(0, "BufferCurrentTarget", { bg = "#75819c", fg = "#c36901" })
hi(0, "BufferInactive", { bg = "#151924", fg = "#0196a3" })
hi(0, "BufferInactiveIndex", { bg = "#151924", fg = "#0196a3" })
hi(0, "BufferInactiveMod", { bg = "#151924", fg = "#574400" })
hi(0, "BufferInactiveSign", { bg = "#151924", fg = "#00464d" })
hi(0, "BufferInactiveTarget", { bg = "#151924", fg = "#c36901" })
hi(0, "BufferTabpage", { bg = "#151924", fg = "#00464d" })
hi(0, "BufferTabpages", { bg = "#151924" })
hi(0, "BufferVisible", { bg = "#151924", fg = "#9ae2e0" })
hi(0, "BufferVisibleIndex", { bg = "#151924", fg = "#01b3c1" })
hi(0, "BufferVisibleMod", { bg = "#151924", fg = "#f2c217" })
hi(0, "BufferVisibleSign", { bg = "#151924", fg = "#01b3c1" })
hi(0, "BufferVisibleTarget", { bg = "#151924", fg = "#c36901" })
hi(0, "Changed", { ctermfg = 14, fg = "#b7fcba" })
hi(0, "Character", { link = "String" })
hi(0, "CmpDocumentation", { bg = "#151924", fg = "#9ae2e0" })
hi(0, "CmpDocumentationBorder", { bg = "#151924", fg = "#004850" })
hi(0, "CmpItemAbbr", { fg = "#9ae2e0" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#0198a6", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { fg = "#00c3d1" })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = "#00c3d1" })
hi(0, "CmpItemKindClass", { link = "Type" })
hi(0, "CmpItemKindConstant", { link = "@constant" })
hi(0, "CmpItemKindConstructor", { link = "Function" })
hi(0, "CmpItemKindDefault", { fg = "#1dcbce" })
hi(0, "CmpItemKindEnum", { link = "Constant" })
hi(0, "CmpItemKindEnumMember", { link = "@field" })
hi(0, "CmpItemKindEvent", { link = "Constant" })
hi(0, "CmpItemKindField", { link = "@field" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Constant" })
hi(0, "CmpItemKindKeyword", { link = "Identifier" })
hi(0, "CmpItemKindMethod", { link = "Function" })
hi(0, "CmpItemKindModule", { link = "@namespace" })
hi(0, "CmpItemKindOperator", { link = "Operator" })
hi(0, "CmpItemKindProperty", { link = "@property" })
hi(0, "CmpItemKindReference", { link = "Keyword" })
hi(0, "CmpItemKindSnippet", { fg = "#1dcbce" })
hi(0, "CmpItemKindStruct", { link = "Type" })
hi(0, "CmpItemKindTypeParameter", { link = "@field" })
hi(0, "CmpItemKindUnit", { link = "Constant" })
hi(0, "CmpItemKindValue", { link = "Keyword" })
hi(0, "CmpItemKindVariable", { link = "@variable" })
hi(0, "CmpItemMenu", { link = "Comment" })
hi(0, "CocInlayHint", { bg = "#242d3f", fg = "#0196a3" })
hi(0, "ColorColumn", { bg = "#051221" })
hi(0, "CommandMode", { link = "Identifier" })
hi(0, "Comment", { fg = "#508656", italic = true })
hi(0, "Conceal", { fg = "#00464e" })
hi(0, "Conditional", { fg = "#ff78a2" })
hi(0, "Constant", { fg = "#22c4dd", italic = true })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = "#86a2c4", fg = "#806500" })
hi(0, "CursorColumn", { bg = "#051221" })
hi(0, "CursorIM", { bg = "#86a2c4", fg = "#806500" })
hi(0, "CursorLine", { bg = "#051221" })
hi(0, "CursorLineNr", { bold = true, fg = "#f2c217" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#adb521" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#0196a3" })
hi(0, "DapUIBreakpointsInfo", { fg = "#01b3c1" })
hi(0, "DapUIBreakpointsLine", { link = "DapUILineNumber" })
hi(0, "DapUIBreakpointsPath", { fg = "#89e192" })
hi(0, "DapUIDecoration", { fg = "#0198a6" })
hi(0, "DapUIFloatBorder", { link = "FloatBorder" })
hi(0, "DapUIFrameName", { link = "Normal" })
hi(0, "DapUILineNumber", { link = "Number" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#f8daed" })
hi(0, "DapUIScope", { fg = "#89e192" })
hi(0, "DapUISource", { link = "Keyword" })
hi(0, "DapUIStoppedThread", { fg = "#89e192" })
hi(0, "DapUIThread", { link = "String" })
hi(0, "DapUIType", { link = "Type" })
hi(0, "DapUIValue", { fg = "#f8daed" })
hi(0, "DapUIVariable", { fg = "#f8daed" })
hi(0, "DapUIWatchesEmpty", { fg = "#c36901" })
hi(0, "DapUIWatchesError", { fg = "#c36901" })
hi(0, "DapUIWatchesValue", { fg = "#f2c217" })
hi(0, "DashboardCenter", { link = "String" })
hi(0, "DashboardFooter", { fg = "#e4c15f", italic = true })
hi(0, "DashboardHeader", { link = "Title" })
hi(0, "DashboardShortCut", { link = "Identifier" })
hi(0, "Delimiter", { fg = "#c3ecef" })
hi(0, "DiagnosticError", { link = "Error" })
hi(0, "DiagnosticHint", { fg = "#adb521" })
hi(0, "DiagnosticInfo", { fg = "#01b3c1" })
hi(0, "DiagnosticOk", { fg = "#adb521" })
hi(0, "DiagnosticUnderlineError", { sp = "#ef5350", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#81b29a", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#719cd6", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#81b29a", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#dbc074", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#3a2d3f", fg = "#c36901" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#2f3f47", fg = "#adb521" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#2f3a51", fg = "#01b3c1" })
hi(0, "DiagnosticVirtualTextOk", { bg = "#2f3f47", fg = "#adb521" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#3f423f", fg = "#f2c217" })
hi(0, "DiagnosticWarn", { fg = "#f2c217" })
hi(0, "DiffAdd", { bg = "#87d076", fg = "#001f1f" })
hi(0, "DiffChange", { bg = "#eeb240", fg = "#001f1f", underline = true })
hi(0, "DiffDelete", { bg = "#ee5069", fg = "#001f1f" })
hi(0, "DiffText", { bg = "#283e4c" })
hi(0, "Directory", { fg = "#22c4dd" })
hi(0, "EndOfBuffer", { fg = "#002d32" })
hi(0, "Error", { fg = "#c38300" })
hi(0, "ErrorMsg", { link = "Error" })
hi(0, "Exception", { link = "Keyword" })
hi(0, "FernBranchText", { fg = "#01b3c1" })
hi(0, "FidgetTask", { link = "LineNr" })
hi(0, "FidgetTitle", { link = "Title" })
hi(0, "FloatBorder", { bg = "#061628", fg = "#009290" })
hi(0, "FloatShadow", { bg = "#505258", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#505258", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#061628", bold = true, fg = "#cf008e" })
hi(0, "FocusedSymbol", { link = "Search" })
hi(0, "FoldColumn", { bg = "#061628", fg = "#508656" })
hi(0, "Folded", { bg = "#0f2036", fg = "#508656" })
hi(0, "Function", { fg = "#22c4dd", italic = true })
hi(0, "GitGutterAdd", { fg = "#e9b900" })
hi(0, "GitGutterChange", { fg = "#edbe16" })
hi(0, "GitGutterChangeDelete", { fg = "#edbe16" })
hi(0, "GitGutterDelete", { fg = "#c38300" })
hi(0, "GitSignsAdd", { fg = "#e9b900" })
hi(0, "GitSignsChange", { fg = "#edbe16" })
hi(0, "GitSignsChangedelete", { fg = "#edbe16" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#004f4e" })
hi(0, "GitSignsDelete", { fg = "#c38300" })
hi(0, "GitSignsStagedAdd", { fg = "#575c13" })
hi(0, "GitSignsStagedAddCul", { fg = "#575c13" })
hi(0, "GitSignsStagedAddLn", { bg = "#28333d" })
hi(0, "GitSignsStagedAddNr", { fg = "#575c13" })
hi(0, "GitSignsStagedChange", { fg = "#7c620b" })
hi(0, "GitSignsStagedChangeCul", { fg = "#7c620b" })
hi(0, "GitSignsStagedChangeLn", { bg = "#283144" })
hi(0, "GitSignsStagedChangeNr", { fg = "#7c620b" })
hi(0, "GitSignsStagedChangedelete", { fg = "#7c620b" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#7c620b" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#283144" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#7c620b" })
hi(0, "GitSignsStagedDelete", { fg = "#683300" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#683300" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#683300" })
hi(0, "GitSignsStagedTopdelete", { fg = "#683300" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#683300" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#683300" })
hi(0, "GitSignsStagedUntracked", { fg = "#575c13" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#575c13" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#28333d" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#575c13" })
hi(0, "GlyphPalette0", { fg = "#6a0070" })
hi(0, "GlyphPalette1", { fg = "#c36901" })
hi(0, "GlyphPalette10", { fg = "#b7be20" })
hi(0, "GlyphPalette11", { fg = "#fcca18" })
hi(0, "GlyphPalette12", { fg = "#00c3d1" })
hi(0, "GlyphPalette13", { fg = "#fc87b7" })
hi(0, "GlyphPalette14", { fg = "#89e192" })
hi(0, "GlyphPalette15", { fg = "#f9e1f1" })
hi(0, "GlyphPalette2", { fg = "#adb521" })
hi(0, "GlyphPalette3", { fg = "#f2c217" })
hi(0, "GlyphPalette4", { fg = "#01b3c1" })
hi(0, "GlyphPalette5", { fg = "#ef449f" })
hi(0, "GlyphPalette6", { fg = "#81d78c" })
hi(0, "GlyphPalette7", { fg = "#f9e1f1" })
hi(0, "GlyphPalette8", { fg = "#9b0095" })
hi(0, "GlyphPalette9", { fg = "#db7200" })
hi(0, "HopNextKey", { bold = true, fg = "#81d78c" })
hi(0, "HopNextKey1", { bold = true, fg = "#01b3c1" })
hi(0, "HopNextKey2", { fg = "#019aa8" })
hi(0, "HopUnmatched", { fg = "#0196a3" })
hi(0, "IblIndent", { link = "@nowl.indentChar" })
hi(0, "IblScope", { link = "@nowl.indentChar.active" })
hi(0, "IblWhitespace", { link = "Whitespace" })
hi(0, "Identifier", { fg = "#64dec3" })
hi(0, "IlluminatedWordRead", { bg = "#32384d" })
hi(0, "IlluminatedWordText", { bg = "#32384d" })
hi(0, "IlluminatedWordWrite", { bg = "#2b3450" })
hi(0, "IncSearch", { bg = "#33475d" })
hi(0, "Include", { fg = "#ff78a2", italic = true })
hi(0, "IndentBlanklineChar", { link = "@nowl.indentChar" })
hi(0, "IndentBlanklineContextChar", { link = "@nowl.indentChar.active" })
hi(0, "IndentBlanklineContextStart", { sp = "#7e97ac", underline = true })
hi(0, "IndentBlanklineIndent1", { fg = "#ff6876" })
hi(0, "IndentBlanklineIndent2", { fg = "#01b3c1" })
hi(0, "IndentBlanklineIndent3", { fg = "#dfb637" })
hi(0, "IndentBlanklineIndent4", { fg = "#81d78c" })
hi(0, "IndentBlanklineIndent5", { fg = "#c36901" })
hi(0, "IndentBlanklineIndent6", { fg = "#f2c217" })
hi(0, "IndentBlanklineSpaceChar", { link = "Whitespace" })
hi(0, "IndentBlanklineSpaceCharBlankline", { link = "Whitespace" })
hi(0, "InsertMode", { link = "Question" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#ff78a2" })
hi(0, "Label", { link = "Conditional" })
hi(0, "LazyButtonActive", { link = "TabLineSel" })
hi(0, "LazyDimmed", { link = "LineNr" })
hi(0, "LazyProp", { link = "LineNr" })
hi(0, "LeapBackdrop", { fg = "#0196a3" })
hi(0, "LeapLabelPrimary", { bg = "#d292e5", fg = "#002d32" })
hi(0, "LeapLabelSecondary", { bg = "#7ad4df", fg = "#002d32" })
hi(0, "LeapMatch", { bg = "#d292e5", fg = "#002d32" })
hi(0, "LightspeedGreyWash", { fg = "#0196a3" })
hi(0, "LineNr", { fg = "#007575" })
hi(0, "LspCodeLens", { fg = "#0196a3" })
hi(0, "LspCodeLensSeparator", { fg = "#0198a6" })
hi(0, "LspFloatWinBorder", { fg = "#0198a6" })
hi(0, "LspFloatWinNormal", { bg = "#151924" })
hi(0, "LspInfoBorder", { fg = "#009290" })
hi(0, "LspInlayHint", { bg = "#0d2133", fg = "#9b9b9b" })
hi(0, "LspReferenceRead", { bg = "#2f3a51" })
hi(0, "LspReferenceText", { bg = "#2f3a51" })
hi(0, "LspReferenceWrite", { bg = "#2f3a51" })
hi(0, "LspSagaBorderTitle", { link = "Title" })
hi(0, "LspSagaCodeActionBorder", { fg = "#0198a6" })
hi(0, "LspSagaCodeActionContent", { link = "String" })
hi(0, "LspSagaCodeActionTitle", { link = "Title" })
hi(0, "LspSagaDefPreviewBorder", { fg = "#0198a6" })
hi(0, "LspSagaFinderSelection", { fg = "#004850" })
hi(0, "LspSagaHoverBorder", { fg = "#0198a6" })
hi(0, "LspSagaRenameBorder", { fg = "#0198a6" })
hi(0, "LspSagaSignatureHelpBorder", { fg = "#c36901" })
hi(0, "LspSignatureActiveParameter", { fg = "#00626c" })
hi(0, "LspTroubleCount", { bg = "#75819c", fg = "#ef449f" })
hi(0, "LspTroubleNormal", { bg = "#151924", fg = "#0198a6" })
hi(0, "LspTroubleText", { fg = "#1dcbce" })
hi(0, "MatchParen", { bg = "#23354b" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { link = "FloatTitle" })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { link = "LspReferenceText" })
hi(0, "MiniCursorwordCurrent", { link = "LspReferenceText" })
hi(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hi(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { bg = "#c5507f", fg = "#002429" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { bg = "#7cb2a1", fg = "#002429" })
hi(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hi(0, "MiniDiffOverChange", { link = "DiffText" })
hi(0, "MiniDiffOverContext", { link = "DiffChange" })
hi(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hi(0, "MiniDiffSignAdd", { fg = "#adb521" })
hi(0, "MiniDiffSignChange", { fg = "#f2c217" })
hi(0, "MiniDiffSignDelete", { fg = "#c36901" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#9ae2e0" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bold = true, fg = "#9ae2e0" })
hi(0, "MiniHipatternsFixme", { bg = "#c5507f", bold = true, fg = "#002429" })
hi(0, "MiniHipatternsHack", { bg = "#d1c476", bold = true, fg = "#002429" })
hi(0, "MiniHipatternsNote", { bg = "#7d98d7", bold = true, fg = "#002429" })
hi(0, "MiniHipatternsTodo", { bg = "#7cb2a1", bold = true, fg = "#002429" })
hi(0, "MiniIconsAzure", { fg = "#00c3d1" })
hi(0, "MiniIconsBlue", { fg = "#01b3c1" })
hi(0, "MiniIconsCyan", { fg = "#81d78c" })
hi(0, "MiniIconsGreen", { fg = "#adb521" })
hi(0, "MiniIconsGrey", { fg = "#f4cde8" })
hi(0, "MiniIconsOrange", { fg = "#dfb637" })
hi(0, "MiniIconsPurple", { fg = "#ef449f" })
hi(0, "MiniIconsRed", { fg = "#c36901" })
hi(0, "MiniIconsYellow", { fg = "#f2c217" })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { link = "Delimiter" })
hi(0, "MiniJump", { bg = "#8f7edd", fg = "#002429" })
hi(0, "MiniJump2dDim", { link = "Comment" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#81d78c" })
hi(0, "MiniJump2dSpotAhead", { bg = "#151924", fg = "#019aa8", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#f2c217" })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { link = "FloatTitle" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#e4c15f", italic = true })
hi(0, "MiniStarterHeader", { link = "Title" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { fg = "#0198a6" })
hi(0, "MiniStarterItemPrefix", { fg = "#ff6876" })
hi(0, "MiniStarterQuery", { fg = "#adb521" })
hi(0, "MiniStarterSection", { fg = "#c36901" })
hi(0, "MiniStatuslineDevinfo", { bg = "#242d3f", fg = "#1dcbce" })
hi(0, "MiniStatuslineFileinfo", { bg = "#242d3f", fg = "#1dcbce" })
hi(0, "MiniStatuslineFilename", { link = "StatusLine" })
hi(0, "MiniStatuslineInactive", { link = "StatusLineNC" })
hi(0, "MiniStatuslineModeCommand", { bg = "#d1c476", bold = true, fg = "#002429" })
hi(0, "MiniStatuslineModeInsert", { bg = "#7cb2a1", bold = true, fg = "#002429" })
hi(0, "MiniStatuslineModeNormal", { bg = "#64cbd9", bold = true, fg = "#002429" })
hi(0, "MiniStatuslineModeOther", { bg = "#7d98d7", bold = true, fg = "#002429" })
hi(0, "MiniStatuslineModeReplace", { bg = "#c5507f", bold = true, fg = "#002429" })
hi(0, "MiniStatuslineModeVisual", { bg = "#8f7edd", bold = true, fg = "#002429" })
hi(0, "MiniTablineCurrent", { bg = "#3f4e6e", bold = true, fg = "#1dcbce" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#242d3f", fg = "#0198a6" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#aeafb0", bold = true, fg = "#005f67" })
hi(0, "MiniTablineModifiedHidden", { bg = "#75819c", fg = "#003a40" })
hi(0, "MiniTablineModifiedVisible", { bg = "#aeafb0", fg = "#003a40" })
hi(0, "MiniTablineTabpagesection", { bg = "#1c2230", bold = true, fg = "#9ae2e0" })
hi(0, "MiniTablineVisible", { bg = "#242d3f", fg = "#1dcbce" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#c36901" })
hi(0, "MiniTestPass", { bold = true, fg = "#adb521" })
hi(0, "MiniTrailspace", { bg = "#c5507f" })
hi(0, "ModeMsg", { bold = true, fg = "#f2c217" })
hi(0, "ModesCopy", { bg = "#d1c476" })
hi(0, "ModesDelete", { bg = "#c5507f" })
hi(0, "ModesInsert", { bg = "#64cbd9" })
hi(0, "ModesVisual", { bg = "#8f7edd" })
hi(0, "MoreMsg", { bold = true, fg = "#01b3c1" })
hi(0, "NagicIconsOperator", { link = "Operator" })
hi(0, "NavicIconsBoolean", { link = "Boolean" })
hi(0, "NavicIconsClass", { link = "Type" })
hi(0, "NavicIconsConstant", { link = "Constant" })
hi(0, "NavicIconsConstructor", { link = "Function" })
hi(0, "NavicIconsEnum", { link = "Constant" })
hi(0, "NavicIconsEnumMember", { link = "@field" })
hi(0, "NavicIconsEvent", { link = "Constant" })
hi(0, "NavicIconsField", { link = "@field" })
hi(0, "NavicIconsFile", { link = "Directory" })
hi(0, "NavicIconsFunction", { link = "Function" })
hi(0, "NavicIconsInterface", { link = "Constant" })
hi(0, "NavicIconsKey", { link = "Identifier" })
hi(0, "NavicIconsMethod", { link = "Function" })
hi(0, "NavicIconsModule", { link = "@namespace" })
hi(0, "NavicIconsNamespace", { link = "@namespace" })
hi(0, "NavicIconsNull", { link = "Type" })
hi(0, "NavicIconsNumber", { link = "Number" })
hi(0, "NavicIconsObject", { link = "@namespace" })
hi(0, "NavicIconsPackage", { link = "@namespace" })
hi(0, "NavicIconsProperty", { link = "@property" })
hi(0, "NavicIconsString", { link = "String" })
hi(0, "NavicIconsStruct", { link = "Type" })
hi(0, "NavicIconsTypeParameter", { link = "@field" })
hi(0, "NavicIconsVariable", { link = "@variable" })
hi(0, "NavicSeparator", { fg = "#005f67" })
hi(0, "NavicText", { fg = "#9ae2e0" })
hi(0, "NeoTreeDimText", { link = "Conceal" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#01b3c1" })
hi(0, "NeoTreeDirectoryName", { fg = "#01b3c1" })
hi(0, "NeoTreeDotfile", { fg = "#019aa8" })
hi(0, "NeoTreeFileName", { fg = "#1dcbce" })
hi(0, "NeoTreeFileNameOpened", { fg = "#9ae2e0" })
hi(0, "NeoTreeGitAdded", { fg = "#adb521" })
hi(0, "NeoTreeGitConflict", { fg = "#dfb637", italic = true })
hi(0, "NeoTreeGitDeleted", { fg = "#c36901" })
hi(0, "NeoTreeGitIgnored", { fg = "#0196a3" })
hi(0, "NeoTreeGitModified", { fg = "#f2c217" })
hi(0, "NeoTreeGitUntracked", { fg = "#dd008f" })
hi(0, "NeoTreeIndentMarker", { fg = "#005f67" })
hi(0, "NeoTreeNormal", { bg = "#151924", fg = "#9ae2e0" })
hi(0, "NeoTreeNormalNC", { link = "NeoTreeNormal" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#dfb637" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#ff2651" })
hi(0, "NeogitBranch", { fg = "#f2c217" })
hi(0, "NeogitDiffAdd", { fg = "#adb521" })
hi(0, "NeogitDiffAddHighlight", { bg = "#28333d" })
hi(0, "NeogitDiffContextHighlight", { bg = "#242d3f" })
hi(0, "NeogitDiffDelete", { fg = "#c36901" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#2d2938" })
hi(0, "NeogitHunkHeader", { bg = "#2e384f", fg = "#01b3c1" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#2f3a51", fg = "#01b3c1" })
hi(0, "NeogitNotificationError", { fg = "#c36901" })
hi(0, "NeogitNotificationInfo", { fg = "#01b3c1" })
hi(0, "NeogitNotificationWarning", { fg = "#f2c217" })
hi(0, "NeogitRemote", { fg = "#adb521" })
hi(0, "NeotestAdapterName", { bold = true, fg = "#ff6876" })
hi(0, "NeotestDir", { fg = "#81d78c" })
hi(0, "NeotestExpandMarker", { link = "Conceal" })
hi(0, "NeotestFailed", { fg = "#c36901" })
hi(0, "NeotestFile", { fg = "#01b3c1" })
hi(0, "NeotestFocused", { underline = true })
hi(0, "NeotestIndent", { link = "Conceal" })
hi(0, "NeotestMarked", { bold = true, fg = "#9ae2e0" })
hi(0, "NeotestNamespace", { fg = "#6eb776" })
hi(0, "NeotestPassed", { fg = "#adb521" })
hi(0, "NeotestRunning", { fg = "#dfb637" })
hi(0, "NeotestSkipped", { fg = "#f2c217" })
hi(0, "NeotestTest", { link = "Normal" })
hi(0, "NoiceFormatProgressDone", { bg = "#425173", fg = "#9ae2e0" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#00afae" })
hi(0, "Normal", { bg = "#061628", fg = "#c3ecef" })
hi(0, "NormalFloat", { bg = "#061628", blend = 0 })
hi(0, "NormalMode", { bold = true, fg = "#f2c217" })
hi(0, "NormalNC", { bg = "#1c2230", fg = "#9ae2e0" })
hi(0, "NotifyBackground", { link = "NormalFloat" })
hi(0, "NotifyDEBUGBorder", { fg = "#55733a" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#adb521" })
hi(0, "NotifyERRORBorder", { fg = "#873700" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#c36901" })
hi(0, "NotifyINFOBorder", { fg = "#00717b" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#01b3c1" })
hi(0, "NotifyTRACEBorder", { fg = "#005f67" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#0196a3" })
hi(0, "NotifyWARNBorder", { fg = "#90720b" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#f2c217" })
hi(0, "Number", { fg = "#d4a800" })
hi(0, "NvimInternalError", { bg = "#fc0046", ctermbg = 9, ctermfg = 9, fg = "#b78102" })
hi(0, "NvimTreeCursorLine", { bg = "#152740" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#0198a6" })
hi(0, "NvimTreeFolderIcon", { fg = "#01b3c1" })
hi(0, "NvimTreeFolderName", { fg = "#01b3c1" })
hi(0, "NvimTreeGitDeleted", { fg = "#c38300" })
hi(0, "NvimTreeGitDirty", { fg = "#76d3e4" })
hi(0, "NvimTreeGitMerge", { fg = "#dfb637" })
hi(0, "NvimTreeGitNew", { fg = "#ffd65c" })
hi(0, "NvimTreeGitRenamed", { fg = "#e9b900" })
hi(0, "NvimTreeGitStaged", { fg = "#edbe16" })
hi(0, "NvimTreeImageFile", { fg = "#00bdbc" })
hi(0, "NvimTreeIndentMarker", { fg = "#5d5d5d" })
hi(0, "NvimTreeNormal", { fg = "#d2d2d2" })
hi(0, "NvimTreeNormalNC", { fg = "#009290" })
hi(0, "NvimTreeOpenedFile", { bold = true })
hi(0, "NvimTreeOpenedFolderName", { fg = "#00c3d1" })
hi(0, "NvimTreeRootFolder", { fg = "#ff78a2" })
hi(0, "NvimTreeSpecialFile", { fg = "#d4a800" })
hi(0, "NvimTreeSymlink", { fg = "#ff2651" })
hi(0, "NvimTreeVertSplit", { link = "VertSplit" })
hi(0, "NvimTreeWindowPicker", { bg = "#030c19", bold = true, fg = "#f2d891", italic = true })
hi(0, "Operator", { fg = "#ff78a2" })
hi(0, "Pmenu", { bg = "#030c19" })
hi(0, "PmenuSel", { bg = "#152740" })
hi(0, "PmenuThumb", { bg = "#425173" })
hi(0, "PounceAccept", { bg = "#fbac82", fg = "#002d32" })
hi(0, "PounceAcceptBest", { bg = "#7ad4df", fg = "#002d32" })
hi(0, "PounceGap", { bg = "#2f3a51", fg = "#9ae2e0" })
hi(0, "PounceMatch", { bg = "#425173", fg = "#9ae2e0" })
hi(0, "PreProc", { fg = "#e37000" })
hi(0, "Question", { link = "MoreMsg" })
hi(0, "QuickFixLine", { bg = "#152740" })
hi(0, "RainbowDelimiterBlue", { fg = "#00b5b8" })
hi(0, "RainbowDelimiterCyan", { fg = "#81d78c" })
hi(0, "RainbowDelimiterGreen", { fg = "#adb521" })
hi(0, "RainbowDelimiterOrange", { fg = "#dfb637" })
hi(0, "RainbowDelimiterPurple", { fg = "#ef449f" })
hi(0, "RainbowDelimiterRed", { fg = "#c36901" })
hi(0, "RainbowDelimiterViolet", { fg = "#ff6473" })
hi(0, "RainbowDelimiterYellow", { fg = "#ffdb72" })
hi(0, "RedrawDebugClear", { bg = "#724f03", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#005434", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#580018", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#edcc9b" })
hi(0, "Repeat", { link = "Conditional" })
hi(0, "ReplaceMode", { link = "WarningMsg" })
hi(0, "Search", { bg = "#163c60" })
hi(0, "SelectMode", { link = "ErrorMsg" })
hi(0, "SignColumn", { bg = "#061628" })
hi(0, "SignColumnSB", { link = "SignColumn" })
hi(0, "SignifySignAdd", { fg = "#adb521" })
hi(0, "SignifySignChange", { fg = "#f2c217" })
hi(0, "SignifySignDelete", { fg = "#c36901" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksImageMath", { fg = "#6ae7aa" })
hi(0, "Sneak", { bg = "#8f7edd", fg = "#002429" })
hi(0, "SneakScope", { bg = "#2f3a51" })
hi(0, "Special", { fg = "#f2d891" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#c94f6d", undercurl = true })
hi(0, "SpellCap", { sp = "#dbc074", undercurl = true })
hi(0, "SpellLocal", { sp = "#719cd6", undercurl = true })
hi(0, "SpellRare", { sp = "#719cd6", undercurl = true })
hi(0, "Statement", { fg = "#ff78a2", italic = true })
hi(0, "StatusLine", { bg = "#030c19", fg = "#c3ecef" })
hi(0, "StatusLineNC", { bg = "#152740", fg = "#009290" })
hi(0, "String", { fg = "#f0cc66" })
hi(0, "Substitute", { bg = "#c5507f", fg = "#002d32" })
hi(0, "SymbolOutlineConnector", { link = "Conceal" })
hi(0, "TSRainbowBlue", { fg = "#01b3c1" })
hi(0, "TSRainbowCyan", { fg = "#81d78c" })
hi(0, "TSRainbowGreen", { fg = "#adb521" })
hi(0, "TSRainbowOrange", { fg = "#dfb637" })
hi(0, "TSRainbowRed", { fg = "#c36901" })
hi(0, "TSRainbowViolet", { fg = "#ef449f" })
hi(0, "TSRainbowYellow", { fg = "#f2c217" })
hi(0, "TabLine", { bg = "#03101e", fg = "#009290" })
hi(0, "TabLineFill", { fg = "#001f1f" })
hi(0, "TabLineSel", { bg = "#132743", fg = "#bcede6" })
hi(0, "Tag", { fg = "#caf8b1" })
hi(0, "TelescopeBorder", { fg = "#009290" })
hi(0, "TelescopeMatching", { bold = true, fg = "#00bdbc" })
hi(0, "TelescopeSelection", { bg = "#243954" })
hi(0, "TelescopeSelectionCaret", { fg = "#adb521" })
hi(0, "TermCursor", { bg = "#86a2c4", fg = "#806500" })
hi(0, "Terminal", { bg = "#061628", fg = "#c3ecef" })
hi(0, "TerminalMode", { link = "Operator" })
hi(0, "TerminalNormalMode", { bold = true, fg = "#f2c217" })
hi(0, "TinyInlineDiagnosticVirtualTextArrow", { bg = "#051221", fg = "#00afae" })
hi(0, "TinyInlineDiagnosticVirtualTextArrowNoBg", { fg = "#00afae" })
hi(0, "TinyInlineDiagnosticVirtualTextBg", { bg = "#051221" })
hi(0, "TinyInlineDiagnosticVirtualTextError", { bg = "#351217", fg = "#c38300" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorCursorLine", { bg = "#051221", fg = "#c38300" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixError", { bg = "#351217", fg = "#c38300" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixHint", { bg = "#1b2724", fg = "#c38300" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixInfo", { bg = "#1c212f", fg = "#c38300" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixWarn", { bg = "#2e2b1a", fg = "#c38300" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorNoBg", { fg = "#c38300" })
hi(0, "TinyInlineDiagnosticVirtualTextHint", { bg = "#1b2724", fg = "#adb521" })
hi(0, "TinyInlineDiagnosticVirtualTextHintCursorLine", { bg = "#051221", fg = "#adb521" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixError", { bg = "#351217", fg = "#adb521" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixHint", { bg = "#1b2724", fg = "#adb521" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixInfo", { bg = "#1c212f", fg = "#adb521" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixWarn", { bg = "#2e2b1a", fg = "#adb521" })
hi(0, "TinyInlineDiagnosticVirtualTextHintNoBg", { fg = "#adb521" })
hi(0, "TinyInlineDiagnosticVirtualTextInfo", { bg = "#1c212f", fg = "#01b3c1" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoCursorLine", { bg = "#051221", fg = "#01b3c1" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixError", { bg = "#351217", fg = "#01b3c1" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixHint", { bg = "#1b2724", fg = "#01b3c1" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixInfo", { bg = "#1c212f", fg = "#01b3c1" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixWarn", { bg = "#2e2b1a", fg = "#01b3c1" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoNoBg", { fg = "#01b3c1" })
hi(0, "TinyInlineDiagnosticVirtualTextWarn", { bg = "#2e2b1a", fg = "#f2c217" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnCursorLine", { bg = "#051221", fg = "#f2c217" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixError", { bg = "#351217", fg = "#f2c217" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixHint", { bg = "#1b2724", fg = "#f2c217" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixInfo", { bg = "#1c212f", fg = "#f2c217" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixWarn", { bg = "#2e2b1a", fg = "#f2c217" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnNoBg", { fg = "#f2c217" })
hi(0, "TinyInlineInvDiagnosticVirtualTextError", { bg = "#051221", fg = "#331e00" })
hi(0, "TinyInlineInvDiagnosticVirtualTextErrorNoBg", { fg = "#331e00" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHint", { bg = "#051221", fg = "#272c09" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHintNoBg", { fg = "#272c09" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfo", { bg = "#051221", fg = "#002c32" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfoNoBg", { fg = "#002c32" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarn", { bg = "#051221", fg = "#3b2e04" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarnNoBg", { fg = "#3b2e04" })
hi(0, "Title", { bold = true, fg = "#3fcadb" })
hi(0, "Todo", { bg = "#7d98d7", fg = "#002d32" })
hi(0, "Type", { fg = "#f2d891" })
hi(0, "Variable", { fg = "#bbeaec" })
hi(0, "VertSplit", { fg = "#4f0059" })
hi(0, "Visual", { link = "@nowl.visual.active" })
hi(0, "VisualMode", { link = "String" })
hi(0, "WarningMsg", { fg = "#f2c217" })
hi(0, "WhichKey", { link = "Identifier" })
hi(0, "WhichKeyDesc", { link = "Keyword" })
hi(0, "WhichKeyFloat", { link = "NormalFloat" })
hi(0, "WhichKeyGroup", { link = "Function" })
hi(0, "WhichKeySeparator", { link = "Comment" })
hi(0, "WhichKeySeperator", { link = "Comment" })
hi(0, "WhichKeyValue", { link = "Comment" })
hi(0, "Whitespace", { fg = "#004442" })
hi(0, "WildMenu", { link = "Pmenu" })
hi(0, "WinBar", { bg = "#1c2230", bold = true, fg = "#0198a6" })
hi(0, "WinBarNC", { bg = "#1c2230", bold = true, fg = "#0198a6" })
hi(0, "WinSeparator", { fg = "#4f0059" })
hi(0, "diffAdded", { fg = "#adb521" })
hi(0, "diffChanged", { fg = "#f2c217" })
hi(0, "diffFile", { fg = "#01b3c1" })
hi(0, "diffIndexLine", { fg = "#ff7e87" })
hi(0, "diffLine", { fg = "#e4c15f" })
hi(0, "diffNewFile", { fg = "#adb521" })
hi(0, "diffOldFile", { fg = "#f2c217" })
hi(0, "diffRemoved", { fg = "#c36901" })
hi(0, "lCursor", { bg = "#86a2c4", fg = "#806500" })
hi(0, "luaFunc", {})
hi(0, "luaFunction", {})
hi(0, "luaTable", {})
hi(0, "qfFileName", { link = "Directory" })
hi(0, "qfLineNr", { link = "LineNr" })
hi(0, "rainbowcol1", { fg = "#c36901" })
hi(0, "rainbowcol2", { fg = "#f2c217" })
hi(0, "rainbowcol3", { fg = "#adb521" })
hi(0, "rainbowcol4", { fg = "#01b3c1" })
hi(0, "rainbowcol5", { fg = "#81d78c" })
hi(0, "rainbowcol6", { fg = "#ef449f" })
hi(0, "rainbowcol7", { fg = "#ff6876" })
hi(0, "tomlKey", { fg = "#ff78a2", nocombine = true })
hi(0, "tomlKeySq", { fg = "#ff78a2", nocombine = true })
hi(0, "tomlTable", { fg = "#ffd65c", italic = true })
hi(0, "typescriptParens", { fg = "#1dcbce" })
hi(0, "zshDeref", {})
hi(0, "zshFunction", {})
hi(0, "zshOptStart", {})
hi(0, "zshOption", {})
hi(0, "zshSubst", {})
hi(0, "zshTypes", {})
hi(0, "zshVariableDef", {})

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#010d18"
g.terminal_color_1 = "#ab0300"
g.terminal_color_2 = "#6cc85e"
g.terminal_color_3 = "#ffd602"
g.terminal_color_4 = "#82aaff"
g.terminal_color_5 = "#7e57c2"
g.terminal_color_6 = "#7fdbca"
g.terminal_color_7 = "#cccccc"
g.terminal_color_8 = "#36414a"
g.terminal_color_9 = "#ff5874"
g.terminal_color_10 = "#c5e478"
g.terminal_color_11 = "#faf39f"
g.terminal_color_12 = "#78ccf0"
g.terminal_color_13 = "#c792ea"
g.terminal_color_14 = "#baebe2"
g.terminal_color_15 = "#ffffff"
