-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "rose-pine-2"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#cd9bff" })
hi(0, "@attribute.builtin", { bold = true, fg = "#cd9bff" })
hi(0, "@attribute.diff", { fg = "#ffbd5b" })
hi(0, "@character.special", { link = "Character" })
hi(0, "@class", { fg = "#18ddf6" })
hi(0, "@comment.error", { fg = "#ff508d" })
hi(0, "@comment.hint", { bg = "#1d3054", fg = "#cd9bff" })
hi(0, "@comment.info", { bg = "#00394d", fg = "#18ddf6" })
hi(0, "@comment.note", { bg = "#002939", fg = "#007699" })
hi(0, "@comment.todo", { bg = "#31304d", fg = "#ffaba9" })
hi(0, "@comment.warning", { fg = "#ffbd5b" })
hi(0, "@conceal", { link = "Conceal" })
hi(0, "@conceal.markdown", { fg = "#9378f0" })
hi(0, "@constant", { fg = "#ffbd5b" })
hi(0, "@constant.builtin", { bold = true, fg = "#ffbd5b" })
hi(0, "@constant.macro", { fg = "#ffbd5b" })
hi(0, "@constructor", { fg = "#18ddf6" })
hi(0, "@diff.delta", { bg = "#3e3756" })
hi(0, "@diff.minus", { bg = "#3c2850", fg = "#ff508d" })
hi(0, "@diff.plus", { bg = "#1b414d", fg = "#18ddf6" })
hi(0, "@field", { fg = "#18ddf6" })
hi(0, "@float", { link = "Number" })
hi(0, "@function", { fg = "#ffaba9" })
hi(0, "@function.builtin", { bold = true, fg = "#ffaba9" })
hi(0, "@function.macro", { link = "Function" })
hi(0, "@function.method", { fg = "#ffaba9" })
hi(0, "@function.method.call", { fg = "#cd9bff" })
hi(0, "@interface", { fg = "#18ddf6" })
hi(0, "@keyword.conditional", { fg = "#007699" })
hi(0, "@keyword.conditional.ternary", { fg = "#007699" })
hi(0, "@keyword.debug", { fg = "#ffaba9" })
hi(0, "@keyword.directive", { fg = "#cd9bff" })
hi(0, "@keyword.directive.define", { fg = "#cd9bff" })
hi(0, "@keyword.exception", { fg = "#007699" })
hi(0, "@keyword.import", { fg = "#007699" })
hi(0, "@keyword.operator", { fg = "#9378f0" })
hi(0, "@keyword.repeat", { fg = "#007699" })
hi(0, "@keyword.return", { fg = "#007699" })
hi(0, "@keyword.storage", { fg = "#18ddf6" })
hi(0, "@lsp.type.comment", {})
hi(0, "@lsp.type.comment.c", { link = "@comment" })
hi(0, "@lsp.type.comment.cpp", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.interface", { link = "@interface" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.namespace.python", { link = "@variable" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.type.variable.svelte", { link = "@variable" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.constant", { link = "@constant" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@macro", { link = "Macro" })
hi(0, "@markup.environment", { link = "Macro" })
hi(0, "@markup.environment.name", { link = "@type" })
hi(0, "@markup.heading", { bold = true, fg = "#18ddf6" })
hi(0, "@markup.heading.1.delimiter.vimdoc", { bg = "#08192e", fg = "#1c0941", nocombine = true, sp = "#e0def4", underdouble = true })
hi(0, "@markup.heading.1.markdown", { link = "markdownH1" })
hi(0, "@markup.heading.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@markup.heading.2.delimiter.vimdoc", { bg = "#08192e", fg = "#1c0941", nocombine = true, sp = "#e0def4", underline = true })
hi(0, "@markup.heading.2.markdown", { link = "markdownH2" })
hi(0, "@markup.heading.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@markup.heading.3.markdown", { link = "markdownH3" })
hi(0, "@markup.heading.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@markup.heading.4.markdown", { link = "markdownH4" })
hi(0, "@markup.heading.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@markup.heading.5.markdown", { link = "markdownH5" })
hi(0, "@markup.heading.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@markup.heading.6.markdown", { link = "markdownH6" })
hi(0, "@markup.heading.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#18ddf6" })
hi(0, "@markup.link.markdown_inline", { fg = "#9378f0" })
hi(0, "@markup.link.url", { fg = "#cd9bff" })
hi(0, "@markup.list", { fg = "#007699" })
hi(0, "@markup.list.checked", { bg = "#062d43", fg = "#18ddf6" })
hi(0, "@markup.list.unchecked", { fg = "#e0dbff" })
hi(0, "@markup.math", { link = "Special" })
hi(0, "@markup.quote", { fg = "#e0dbff" })
hi(0, "@markup.raw.delimiter.markdown", { fg = "#9378f0" })
hi(0, "@method", { fg = "#ffaba9" })
hi(0, "@module", { fg = "#e0dbff" })
hi(0, "@module.builtin", { bold = true, fg = "#e0dbff" })
hi(0, "@number.float", { link = "Number" })
hi(0, "@parameter", { fg = "#cd9bff", italic = true })
hi(0, "@property", { fg = "#18ddf6", italic = true })
hi(0, "@punctuation", { fg = "#9378f0" })
hi(0, "@punctuation.bracket", { fg = "#9378f0" })
hi(0, "@punctuation.delimiter", { fg = "#9378f0" })
hi(0, "@punctuation.special", { fg = "#9378f0" })
hi(0, "@regexp", { link = "String" })
hi(0, "@string.escape", { fg = "#007699" })
hi(0, "@string.regexp", { fg = "#cd9bff" })
hi(0, "@string.special", { link = "String" })
hi(0, "@string.special.symbol", { link = "Identifier" })
hi(0, "@string.special.url", { fg = "#cd9bff" })
hi(0, "@tag.attribute", { fg = "#cd9bff" })
hi(0, "@tag.delimiter", { fg = "#9378f0" })
hi(0, "@text", { fg = "#e0dbff" })
hi(0, "@text.danger", { fg = "#ff508d" })
hi(0, "@text.diff.add", { bg = "#1b414d", fg = "#18ddf6" })
hi(0, "@text.diff.delete", { bg = "#3c2850", fg = "#ff508d" })
hi(0, "@text.emphasis", { italic = true })
hi(0, "@text.environment", { link = "Macro" })
hi(0, "@text.environment.name", { link = "Type" })
hi(0, "@text.math", { link = "Special" })
hi(0, "@text.note", { link = "SpecialComment" })
hi(0, "@text.strike", { strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { link = "Title" })
hi(0, "@text.title.1.markdown", { link = "markdownH1" })
hi(0, "@text.title.1.marker.markdown", { link = "markdownH1Delimiter" })
hi(0, "@text.title.2.markdown", { link = "markdownH2" })
hi(0, "@text.title.2.marker.markdown", { link = "markdownH2Delimiter" })
hi(0, "@text.title.3.markdown", { link = "markdownH3" })
hi(0, "@text.title.3.marker.markdown", { link = "markdownH3Delimiter" })
hi(0, "@text.title.4.markdown", { link = "markdownH4" })
hi(0, "@text.title.4.marker.markdown", { link = "markdownH4Delimiter" })
hi(0, "@text.title.5.markdown", { link = "markdownH5" })
hi(0, "@text.title.5.marker.markdown", { link = "markdownH5Delimiter" })
hi(0, "@text.title.6.markdown", { link = "markdownH6" })
hi(0, "@text.title.6.marker.markdown", { link = "markdownH6Delimiter" })
hi(0, "@text.underline", { underline = true })
hi(0, "@text.uri", { fg = "#cd9bff" })
hi(0, "@text.warning", { fg = "#ffbd5b" })
hi(0, "@type", { fg = "#18ddf6" })
hi(0, "@type.builtin", { bold = true, fg = "#18ddf6" })
hi(0, "@variable", { fg = "#e0dbff", italic = true })
hi(0, "@variable.builtin", { bold = true, fg = "#ff508d", italic = true })
hi(0, "@variable.member", { fg = "#18ddf6" })
hi(0, "@variable.parameter", { fg = "#cd9bff", italic = true })
hi(0, "@variable.parameter.builtin", { bold = true, fg = "#cd9bff", italic = true })
hi(0, "Added", { ctermfg = 10, fg = "#8bffa8" })
hi(0, "AlphaButtons", { fg = "#18ddf6" })
hi(0, "AlphaFooter", { fg = "#ffbd5b" })
hi(0, "AlphaHeader", { fg = "#007699" })
hi(0, "AlphaShortcut", { fg = "#ffaba9" })
hi(0, "AvanteReversedSubtitle", { fg = "#18ddf6" })
hi(0, "AvanteReversedThirdTitle", { fg = "#cd9bff" })
hi(0, "AvanteReversedTitle", { fg = "#ffaba9" })
hi(0, "AvanteSubtitle", { bg = "#8bd7c2", fg = "#45248c" })
hi(0, "AvanteThirdTitle", { bg = "#96b2ff", fg = "#45248c" })
hi(0, "AvanteTitle", { bg = "#efb6d4", fg = "#5731b0" })
hi(0, "BlinkCmpDefault", { fg = "#45248c" })
hi(0, "BlinkCmpDoc", { bg = "#0d233b" })
hi(0, "BlinkCmpDocBorder", { fg = "#5731b0" })
hi(0, "BlinkCmpDocSeparator", { bg = "#0d233b" })
hi(0, "BlinkCmpGhostText", { fg = "#7548dd" })
hi(0, "BlinkCmpKindClass", { fg = "#ffbd5b" })
hi(0, "BlinkCmpKindCodeium", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindColor", { fg = "#ff508d" })
hi(0, "BlinkCmpKindConstant", { fg = "#ffbd5b" })
hi(0, "BlinkCmpKindConstructor", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindCopilot", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindEnum", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindEnumMember", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindEvent", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindField", { fg = "#007699" })
hi(0, "BlinkCmpKindFile", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindFolder", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindFunction", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindInterface", { fg = "#ffbd5b" })
hi(0, "BlinkCmpKindKeyword", { fg = "#cd9bff" })
hi(0, "BlinkCmpKindMethod", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindModule", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindOperator", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindProperty", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindReference", { fg = "#ff508d" })
hi(0, "BlinkCmpKindSnippet", { fg = "#ffaba9" })
hi(0, "BlinkCmpKindStruct", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindSupermaven", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindTabNine", { fg = "#18ddf6" })
hi(0, "BlinkCmpKindText", { fg = "#007699" })
hi(0, "BlinkCmpKindTypeParameter", { fg = "#cd9bff" })
hi(0, "BlinkCmpKindUnit", { fg = "#007699" })
hi(0, "BlinkCmpKindValue", { fg = "#ff508d" })
hi(0, "BlinkCmpKindVariable", { fg = "#ffaba9" })
hi(0, "BlinkCmpLabel", { fg = "#7548dd" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#7548dd", strikethrough = true })
hi(0, "BlinkCmpLabelMatch", { bold = true, fg = "#e0dbff" })
hi(0, "Boolean", { fg = "#ffaba9" })
hi(0, "BufferCurrent", { bg = "#082748", fg = "#e0dbff" })
hi(0, "BufferCurrentIndex", { bg = "#082748", fg = "#e0dbff" })
hi(0, "BufferCurrentMod", { bg = "#082748", fg = "#18ddf6" })
hi(0, "BufferCurrentSign", { bg = "#082748", fg = "#9378f0" })
hi(0, "BufferCurrentTarget", { bg = "#082748", fg = "#ffbd5b" })
hi(0, "BufferInactive", { fg = "#9378f0" })
hi(0, "BufferInactiveIndex", { fg = "#9378f0" })
hi(0, "BufferInactiveMod", { fg = "#18ddf6" })
hi(0, "BufferInactiveSign", { fg = "#7548dd" })
hi(0, "BufferInactiveTarget", { fg = "#ffbd5b" })
hi(0, "BufferVisible", { fg = "#9378f0" })
hi(0, "BufferVisibleIndex", { fg = "#9378f0" })
hi(0, "BufferVisibleMod", { fg = "#18ddf6" })
hi(0, "BufferVisibleSign", { fg = "#7548dd" })
hi(0, "BufferVisibleTarget", { fg = "#ffbd5b" })
hi(0, "Changed", { ctermfg = 14, fg = "#4effff" })
hi(0, "Character", { fg = "#ffbd5b" })
hi(0, "CmpItemAbbr", { fg = "#9378f0" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#9378f0", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e0dbff" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e0dbff" })
hi(0, "CmpItemKind", { fg = "#9378f0" })
hi(0, "CmpItemKindClass", { link = "StorageClass" })
hi(0, "CmpItemKindFunction", { link = "Function" })
hi(0, "CmpItemKindInterface", { link = "Type" })
hi(0, "CmpItemKindMethod", { link = "PreProc" })
hi(0, "CmpItemKindSnippet", { link = "String" })
hi(0, "CmpItemKindVariable", { link = "Identifier" })
hi(0, "ColorColumn", { bg = "#09203a" })
hi(0, "CommandMode", { link = "Identifier" })
hi(0, "Comment", { fg = "#9378f0", italic = true })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#007699" })
hi(0, "Constant", { fg = "#ffbd5b" })
hi(0, "CopilotSuggestion", { fg = "#7548dd", italic = true })
hi(0, "CurSearch", { bg = "#ffb497", fg = "#1c0941" })
hi(0, "Cursor", { bg = "#305382", fg = "#e0dbff" })
hi(0, "CursorColumn", { bg = "#082748" })
hi(0, "CursorLine", { bg = "#082748" })
hi(0, "CursorLineNr", { bold = true, fg = "#e0dbff" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#ffbd5b" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#7548dd" })
hi(0, "DapUIBreakpointsInfo", { link = "DapUIThread" })
hi(0, "DapUIBreakpointsLine", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIBreakpointsPath", { fg = "#18ddf6" })
hi(0, "DapUIDecoration", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIFloatBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "DapUIFrameName", { fg = "#e0dbff" })
hi(0, "DapUILineNumber", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#18ddf6" })
hi(0, "DapUIScope", { link = "DapUIBreakpointsPath" })
hi(0, "DapUISource", { fg = "#cd9bff" })
hi(0, "DapUIStoppedThread", { link = "DapUIBreakpointsPath" })
hi(0, "DapUIThread", { fg = "#ffbd5b" })
hi(0, "DapUIType", { fg = "#cd9bff" })
hi(0, "DapUIValue", { fg = "#e0dbff" })
hi(0, "DapUIVariable", { fg = "#e0dbff" })
hi(0, "DapUIWatchesEmpty", { fg = "#ff508d" })
hi(0, "DapUIWatchesError", { link = "DapUIWatchesEmpty" })
hi(0, "DapUIWatchesValue", { link = "DapUIThread" })
hi(0, "DashboardCenter", { fg = "#ffbd5b" })
hi(0, "DashboardFooter", { fg = "#cd9bff" })
hi(0, "DashboardHeader", { fg = "#007699" })
hi(0, "DashboardShortCut", { fg = "#ff508d" })
hi(0, "Debug", { fg = "#ffaba9" })
hi(0, "Define", { fg = "#cd9bff" })
hi(0, "DefinitionCount", { fg = "#ffaba9" })
hi(0, "DefinitionIcon", { fg = "#ffaba9" })
hi(0, "DefinitionPreviewTitle", { bold = true, fg = "#ffaba9" })
hi(0, "Delimiter", { fg = "#9378f0" })
hi(0, "DiagnosticDefaultError", { link = "DiagnosticError" })
hi(0, "DiagnosticDefaultHint", { link = "DiagnosticHint" })
hi(0, "DiagnosticDefaultInfo", { link = "DiagnosticInfo" })
hi(0, "DiagnosticDefaultOk", { link = "DiagnosticOk" })
hi(0, "DiagnosticDefaultWarn", { link = "DiagnosticWarn" })
hi(0, "DiagnosticError", { fg = "#ff508d" })
hi(0, "DiagnosticHint", { fg = "#cd9bff" })
hi(0, "DiagnosticInfo", { fg = "#18ddf6" })
hi(0, "DiagnosticOk", { fg = "#46c1b1" })
hi(0, "DiagnosticUnderlineError", { sp = "#eb6f92", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#c4a7e7", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#9ccfd8", undercurl = true })
hi(0, "DiagnosticUnderlineOk", { sp = "#95b1ac", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#f6c177", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#25203f", fg = "#ff508d" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#162848", fg = "#cd9bff" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#062d43", fg = "#18ddf6" })
hi(0, "DiagnosticVirtualTextOk", { bg = "#0e2a40", fg = "#46c1b1" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#2f2538", fg = "#ffbd5b" })
hi(0, "DiagnosticWarn", { fg = "#ffbd5b" })
hi(0, "DiffAdd", { bg = "#1b414d" })
hi(0, "DiffChange", { bg = "#3e3756" })
hi(0, "DiffDelete", { bg = "#3c2850" })
hi(0, "DiffText", { bg = "#705377" })
hi(0, "Directory", { bold = true, fg = "#18ddf6" })
hi(0, "Error", { fg = "#ff508d" })
hi(0, "ErrorMsg", { bold = true, fg = "#ff508d" })
hi(0, "Exception", { fg = "#007699" })
hi(0, "FlashLabel", { bg = "#de68d9", fg = "#1c0941" })
hi(0, "Float", { fg = "#ffbd5b" })
hi(0, "FloatBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "FloatShadow", { bg = "#225970", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#225970", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { bg = "#09203a", bold = true, fg = "#18ddf6" })
hi(0, "FoldColumn", { fg = "#7548dd" })
hi(0, "Folded", { bg = "#09203a", fg = "#e0dbff" })
hi(0, "Function", { fg = "#ffaba9" })
hi(0, "FzfLuaBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#9378f0" })
hi(0, "FzfLuaBufFlagCur", { fg = "#9378f0" })
hi(0, "FzfLuaCursorLine", { bg = "#082748", fg = "#e0dbff" })
hi(0, "FzfLuaFilePart", { fg = "#e0dbff" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffaba9" })
hi(0, "FzfLuaHeaderText", { fg = "#ff508d" })
hi(0, "FzfLuaNormal", { link = "NormalFloat" })
hi(0, "FzfLuaTitle", { link = "FloatTitle" })
hi(0, "GitSignsAdd", { fg = "#18ddf6" })
hi(0, "GitSignsChange", { fg = "#ffaba9" })
hi(0, "GitSignsDelete", { fg = "#ff508d" })
hi(0, "GitSignsStagedAdd", { fg = "#106e7d" })
hi(0, "GitSignsStagedAddCul", { fg = "#106e7d" })
hi(0, "GitSignsStagedAddLn", { bg = "#1b414d" })
hi(0, "GitSignsStagedAddNr", { fg = "#106e7d" })
hi(0, "GitSignsStagedChange", { fg = "#aa353c" })
hi(0, "GitSignsStagedChangeCul", { fg = "#aa353c" })
hi(0, "GitSignsStagedChangeLn", { bg = "#3e3756" })
hi(0, "GitSignsStagedChangeNr", { fg = "#aa353c" })
hi(0, "GitSignsStagedChangedelete", { fg = "#aa353c" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#aa353c" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#3e3756" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#aa353c" })
hi(0, "GitSignsStagedDelete", { fg = "#910045" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#910045" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#910045" })
hi(0, "GitSignsStagedTopdelete", { fg = "#910045" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#910045" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#910045" })
hi(0, "GitSignsStagedUntracked", { fg = "#106e7d" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#106e7d" })
hi(0, "GitSignsStagedUntrackedLn", { bg = "#1b414d" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#106e7d" })
hi(0, "GrugFarHelpHeader", { fg = "#007699" })
hi(0, "GrugFarHelpHeaderKey", { fg = "#ffbd5b" })
hi(0, "GrugFarHelpWinActionKey", { fg = "#ffbd5b" })
hi(0, "GrugFarHelpWinActionPrefix", { fg = "#18ddf6" })
hi(0, "GrugFarHelpWinActionText", { fg = "#007699" })
hi(0, "GrugFarHelpWinHeader", { link = "FloatTitle" })
hi(0, "GrugFarInputLabel", { fg = "#18ddf6" })
hi(0, "GrugFarInputPlaceholder", { link = "Comment" })
hi(0, "GrugFarResultsActionMessage", { fg = "#18ddf6" })
hi(0, "GrugFarResultsAddIndicator", { fg = "#18ddf6" })
hi(0, "GrugFarResultsChangeIndicator", { fg = "#ffaba9" })
hi(0, "GrugFarResultsHeader", { fg = "#007699" })
hi(0, "GrugFarResultsLineColumn", { link = "GrugFarResultsLineNo" })
hi(0, "GrugFarResultsLineNo", { fg = "#cd9bff" })
hi(0, "GrugFarResultsMatch", { link = "CurSearch" })
hi(0, "GrugFarResultsPath", { fg = "#18ddf6" })
hi(0, "GrugFarResultsRemoveIndicator", { fg = "#ff508d" })
hi(0, "GrugFarResultsStats", { fg = "#cd9bff" })
hi(0, "HopNextKey", { bg = "#3c2850", fg = "#ff508d" })
hi(0, "HopNextKey1", { bg = "#1b414d", fg = "#18ddf6" })
hi(0, "HopNextKey2", { bg = "#022f3a", fg = "#007699" })
hi(0, "HopUnmatched", { fg = "#7548dd" })
hi(0, "IblIndent", { fg = "#2a0d62" })
hi(0, "IblScope", { fg = "#18ddf6" })
hi(0, "IblWhitespace", { fg = "#2a0d62" })
hi(0, "Identifier", { fg = "#e0dbff" })
hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
hi(0, "Include", { fg = "#007699" })
hi(0, "IndentBlanklineChar", { fg = "#7548dd", nocombine = true })
hi(0, "IndentBlanklineSpaceChar", { fg = "#7548dd", nocombine = true })
hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#7548dd", nocombine = true })
hi(0, "InsertMode", { link = "Question" })
hi(0, "Keyword", { fg = "#007699" })
hi(0, "Label", { fg = "#18ddf6" })
hi(0, "LeapLabelPrimary", { link = "IncSearch" })
hi(0, "LeapLabelSecondary", { link = "StatusLineTerm" })
hi(0, "LeapMatch", { link = "MatchParen" })
hi(0, "LineNr", { fg = "#7548dd" })
hi(0, "LspCodeLens", { fg = "#9378f0" })
hi(0, "LspCodeLensSeparator", { fg = "#7548dd" })
hi(0, "LspFloatWinBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "LspFloatWinNormal", { bg = "#09203a" })
hi(0, "LspInlayHint", { bg = "#10223b", fg = "#7548dd" })
hi(0, "LspReferenceRead", { bg = "#244168" })
hi(0, "LspReferenceText", { bg = "#244168" })
hi(0, "LspReferenceWrite", { bg = "#244168" })
hi(0, "LspSagaAutoPreview", { fg = "#9378f0" })
hi(0, "LspSagaCodeActionBorder", { bg = "#09203a", fg = "#ffaba9" })
hi(0, "LspSagaCodeActionContent", { fg = "#18ddf6" })
hi(0, "LspSagaCodeActionTitle", { bold = true, fg = "#ffbd5b" })
hi(0, "LspSagaCodeActionTruncateLine", { link = "LspSagaCodeActionBorder" })
hi(0, "LspSagaDefPreviewBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "LspSagaDiagnosticBorder", { bg = "#09203a", fg = "#ffbd5b" })
hi(0, "LspSagaDiagnosticHeader", { bold = true, fg = "#18ddf6" })
hi(0, "LspSagaDiagnosticTruncateLine", { link = "LspSagaDiagnosticBorder" })
hi(0, "LspSagaDocTruncateLine", { link = "LspSagaHoverBorder" })
hi(0, "LspSagaFinderSelection", { fg = "#ffbd5b" })
hi(0, "LspSagaHoverBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaLspFinderBorder", { link = "LspFloatWinBorder" })
hi(0, "LspSagaRenameBorder", { bg = "#09203a", fg = "#007699" })
hi(0, "LspSagaRenamePromptPrefix", { fg = "#ff508d" })
hi(0, "LspSagaShTruncateLine", { link = "LspSagaSignatureHelpBorder" })
hi(0, "LspSagaSignatureHelpBorder", { bg = "#09203a", fg = "#18ddf6" })
hi(0, "LspSignatureActiveParameter", { bg = "#082748" })
hi(0, "Macro", { fg = "#cd9bff" })
hi(0, "MatchParen", { bg = "#00333e", fg = "#007699" })
hi(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hi(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hi(0, "MiniClueBorder", { link = "FloatBorder" })
hi(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniClueDescSingle", { link = "NormalFloat" })
hi(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hi(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hi(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hi(0, "MiniClueTitle", { bg = "#09203a", bold = true })
hi(0, "MiniCompletionActiveParameter", { underline = true })
hi(0, "MiniCursorword", { underline = true })
hi(0, "MiniCursorwordCurrent", { underline = true })
hi(0, "MiniDepsChangeAdded", { fg = "#18ddf6" })
hi(0, "MiniDepsChangeRemoved", { fg = "#ff508d" })
hi(0, "MiniDepsHint", { link = "DiagnosticHint" })
hi(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hi(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hi(0, "MiniDepsPlaceholder", { link = "Comment" })
hi(0, "MiniDepsTitle", { link = "Title" })
hi(0, "MiniDepsTitleError", { link = "DiffDelete" })
hi(0, "MiniDepsTitleSame", { link = "DiffText" })
hi(0, "MiniDepsTitleUpdate", { link = "DiffAdd" })
hi(0, "MiniDiffOverAdd", { bg = "#1b414d", fg = "#18ddf6" })
hi(0, "MiniDiffOverChange", { bg = "#3e3756", fg = "#ffaba9" })
hi(0, "MiniDiffOverContext", { bg = "#09203a" })
hi(0, "MiniDiffOverDelete", { bg = "#3c2850", fg = "#ff508d" })
hi(0, "MiniDiffSignAdd", { fg = "#18ddf6" })
hi(0, "MiniDiffSignChange", { fg = "#ffaba9" })
hi(0, "MiniDiffSignDelete", { fg = "#ff508d" })
hi(0, "MiniFilesBorder", { link = "FloatBorder" })
hi(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniFilesCursorLine", { link = "CursorLine" })
hi(0, "MiniFilesDirectory", { link = "Directory" })
hi(0, "MiniFilesFile", { fg = "#e0dbff" })
hi(0, "MiniFilesNormal", { link = "NormalFloat" })
hi(0, "MiniFilesTitle", { link = "FloatTitle" })
hi(0, "MiniFilesTitleFocused", { bg = "#09203a", bold = true, fg = "#ffaba9" })
hi(0, "MiniHipatternsFixme", { bg = "#de68d9", bold = true, fg = "#1c0941" })
hi(0, "MiniHipatternsHack", { bg = "#ffb497", bold = true, fg = "#1c0941" })
hi(0, "MiniHipatternsNote", { bg = "#8bd7c2", bold = true, fg = "#1c0941" })
hi(0, "MiniHipatternsTodo", { bg = "#96b2ff", bold = true, fg = "#1c0941" })
hi(0, "MiniIconsAzure", { fg = "#18ddf6" })
hi(0, "MiniIconsBlue", { fg = "#007699" })
hi(0, "MiniIconsCyan", { fg = "#18ddf6" })
hi(0, "MiniIconsGreen", { fg = "#46c1b1" })
hi(0, "MiniIconsGrey", { fg = "#9378f0" })
hi(0, "MiniIconsOrange", { fg = "#ffaba9" })
hi(0, "MiniIconsPurple", { fg = "#cd9bff" })
hi(0, "MiniIconsRed", { fg = "#ff508d" })
hi(0, "MiniIconsYellow", { fg = "#ffbd5b" })
hi(0, "MiniIndentscopeSymbol", { fg = "#7548dd" })
hi(0, "MiniIndentscopeSymbolOff", { fg = "#ffbd5b" })
hi(0, "MiniJump", { sp = "#f6c177", undercurl = true })
hi(0, "MiniJump2dDim", { fg = "#9378f0" })
hi(0, "MiniJump2dSpot", { bold = true, fg = "#ffbd5b", nocombine = true })
hi(0, "MiniJump2dSpotAhead", { bg = "#09203a", fg = "#18ddf6", nocombine = true })
hi(0, "MiniJump2dSpotUnique", { bold = true, fg = "#ffaba9", nocombine = true })
hi(0, "MiniMapNormal", { link = "NormalFloat" })
hi(0, "MiniMapSymbolCount", { link = "Special" })
hi(0, "MiniMapSymbolLine", { link = "Title" })
hi(0, "MiniMapSymbolView", { link = "Delimiter" })
hi(0, "MiniNotifyBorder", { link = "FloatBorder" })
hi(0, "MiniNotifyNormal", { link = "NormalFloat" })
hi(0, "MiniNotifyTitle", { link = "FloatTitle" })
hi(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hi(0, "MiniPickBorder", { link = "FloatBorder" })
hi(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hi(0, "MiniPickBorderText", { bg = "#09203a" })
hi(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hi(0, "MiniPickIconDirectory", { link = "Directory" })
hi(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hi(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hi(0, "MiniPickMatchMarked", { link = "Visual" })
hi(0, "MiniPickMatchRanges", { fg = "#18ddf6" })
hi(0, "MiniPickNormal", { link = "NormalFloat" })
hi(0, "MiniPickPreviewLine", { link = "CursorLine" })
hi(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hi(0, "MiniPickPrompt", { bg = "#09203a", bold = true })
hi(0, "MiniStarterCurrent", { nocombine = true })
hi(0, "MiniStarterFooter", { fg = "#9378f0" })
hi(0, "MiniStarterHeader", { link = "Title" })
hi(0, "MiniStarterInactive", { link = "Comment" })
hi(0, "MiniStarterItem", { link = "Normal" })
hi(0, "MiniStarterItemBullet", { link = "Delimiter" })
hi(0, "MiniStarterItemPrefix", { link = "WarningMsg" })
hi(0, "MiniStarterQuery", { link = "MoreMsg" })
hi(0, "MiniStarterSection", { fg = "#ffaba9" })
hi(0, "MiniStatuslineDevinfo", { bg = "#082748", fg = "#9378f0" })
hi(0, "MiniStatuslineFileinfo", { link = "MiniStatuslineDevinfo" })
hi(0, "MiniStatuslineFilename", { bg = "#09203a", fg = "#7548dd" })
hi(0, "MiniStatuslineInactive", { link = "MiniStatuslineFilename" })
hi(0, "MiniStatuslineModeCommand", { bg = "#de68d9", bold = true, fg = "#1c0941" })
hi(0, "MiniStatuslineModeInsert", { bg = "#8bd7c2", bold = true, fg = "#1c0941" })
hi(0, "MiniStatuslineModeNormal", { bg = "#efb6d4", bold = true, fg = "#1c0941" })
hi(0, "MiniStatuslineModeOther", { bg = "#efb6d4", bold = true, fg = "#1c0941" })
hi(0, "MiniStatuslineModeReplace", { bg = "#007c79", bold = true, fg = "#1c0941" })
hi(0, "MiniStatuslineModeVisual", { bg = "#96b2ff", bold = true, fg = "#1c0941" })
hi(0, "MiniTablineCurrent", { bg = "#082748", bold = true, fg = "#e0dbff" })
hi(0, "MiniTablineFill", { link = "TabLineFill" })
hi(0, "MiniTablineHidden", { bg = "#09203a", fg = "#9378f0" })
hi(0, "MiniTablineModifiedCurrent", { bg = "#cfe3fc", bold = true, fg = "#2a0d62" })
hi(0, "MiniTablineModifiedHidden", { bg = "#6d92c4", fg = "#220c51" })
hi(0, "MiniTablineModifiedVisible", { bg = "#cfe3fc", fg = "#220c51" })
hi(0, "MiniTablineTabpagesection", { link = "Search" })
hi(0, "MiniTablineVisible", { bg = "#09203a", fg = "#e0dbff" })
hi(0, "MiniTestEmphasis", { bold = true })
hi(0, "MiniTestFail", { bold = true, fg = "#ff508d" })
hi(0, "MiniTestPass", { bold = true, fg = "#18ddf6" })
hi(0, "MiniTrailspace", { bg = "#de68d9" })
hi(0, "ModeMsg", { fg = "#9378f0" })
hi(0, "ModesCopy", { bg = "#ffb497" })
hi(0, "ModesDelete", { bg = "#de68d9" })
hi(0, "ModesFormat", { bg = "#efb6d4" })
hi(0, "ModesInsert", { bg = "#8bd7c2" })
hi(0, "ModesReplace", { bg = "#007c79" })
hi(0, "ModesVisual", { bg = "#96b2ff" })
hi(0, "MoreMsg", { fg = "#cd9bff" })
hi(0, "NavicIconsArray", { fg = "#ffbd5b" })
hi(0, "NavicIconsBoolean", { fg = "#ffaba9" })
hi(0, "NavicIconsClass", { fg = "#18ddf6" })
hi(0, "NavicIconsConstant", { fg = "#ffbd5b" })
hi(0, "NavicIconsConstructor", { fg = "#ffbd5b" })
hi(0, "NavicIconsEnum", { fg = "#ffbd5b" })
hi(0, "NavicIconsEnumMember", { fg = "#18ddf6" })
hi(0, "NavicIconsEvent", { fg = "#ffbd5b" })
hi(0, "NavicIconsField", { fg = "#18ddf6" })
hi(0, "NavicIconsFile", { fg = "#7548dd" })
hi(0, "NavicIconsFunction", { fg = "#007699" })
hi(0, "NavicIconsInterface", { fg = "#18ddf6" })
hi(0, "NavicIconsKey", { fg = "#cd9bff" })
hi(0, "NavicIconsKeyword", { fg = "#007699" })
hi(0, "NavicIconsMethod", { fg = "#cd9bff" })
hi(0, "NavicIconsModule", { fg = "#ffaba9" })
hi(0, "NavicIconsNamespace", { fg = "#7548dd" })
hi(0, "NavicIconsNull", { fg = "#ff508d" })
hi(0, "NavicIconsNumber", { fg = "#ffbd5b" })
hi(0, "NavicIconsObject", { fg = "#ffbd5b" })
hi(0, "NavicIconsOperator", { fg = "#9378f0" })
hi(0, "NavicIconsPackage", { fg = "#7548dd" })
hi(0, "NavicIconsProperty", { fg = "#18ddf6" })
hi(0, "NavicIconsString", { fg = "#ffbd5b" })
hi(0, "NavicIconsStruct", { fg = "#18ddf6" })
hi(0, "NavicIconsTypeParameter", { fg = "#18ddf6" })
hi(0, "NavicIconsVariable", { fg = "#e0dbff" })
hi(0, "NavicSeparator", { fg = "#9378f0" })
hi(0, "NavicText", { fg = "#9378f0" })
hi(0, "NeoTreeGitAdded", { fg = "#18ddf6" })
hi(0, "NeoTreeGitConflict", { fg = "#cd9bff" })
hi(0, "NeoTreeGitDeleted", { fg = "#ff508d" })
hi(0, "NeoTreeGitIgnored", { fg = "#7548dd" })
hi(0, "NeoTreeGitModified", { fg = "#ffaba9" })
hi(0, "NeoTreeGitRenamed", { fg = "#007699" })
hi(0, "NeoTreeGitUntracked", { fg = "#9378f0" })
hi(0, "NeoTreeTabActive", { bg = "#082748", fg = "#e0dbff" })
hi(0, "NeoTreeTabInactive", { fg = "#9378f0" })
hi(0, "NeoTreeTabSeparatorActive", { link = "WinSeparator" })
hi(0, "NeoTreeTabSeparatorInactive", { link = "WinSeparator" })
hi(0, "NeoTreeTitleBar", { link = "StatusLineTerm" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#18ddf6", italic = true })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#ffaba9", italic = true })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#9378f0", italic = true })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#ff508d", italic = true })
hi(0, "NeogitChangeModified", { bold = true, fg = "#ffaba9", italic = true })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#cd9bff", italic = true })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#007699", italic = true })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#ffaba9", italic = true })
hi(0, "NeogitDiffAddHighlight", { link = "DiffAdd" })
hi(0, "NeogitDiffContextHighlight", { bg = "#09203a" })
hi(0, "NeogitDiffDeleteHighlight", { link = "DiffDelete" })
hi(0, "NeogitFilePath", { fg = "#18ddf6", italic = true })
hi(0, "NeogitHunkHeader", { bg = "#09203a" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#09203a" })
hi(0, "NeorgHeading1Prefix", { link = "markdownH1Delimiter" })
hi(0, "NeorgHeading1Title", { link = "markdownH1" })
hi(0, "NeorgHeading2Prefix", { link = "markdownH2Delimiter" })
hi(0, "NeorgHeading2Title", { link = "markdownH2" })
hi(0, "NeorgHeading3Prefix", { link = "markdownH3Delimiter" })
hi(0, "NeorgHeading3Title", { link = "markdownH3" })
hi(0, "NeorgHeading4Prefix", { link = "markdownH4Delimiter" })
hi(0, "NeorgHeading4Title", { link = "markdownH4" })
hi(0, "NeorgHeading5Prefix", { link = "markdownH5Delimiter" })
hi(0, "NeorgHeading5Title", { link = "markdownH5" })
hi(0, "NeorgHeading6Prefix", { link = "markdownH6Delimiter" })
hi(0, "NeorgHeading6Title", { link = "markdownH6" })
hi(0, "NeorgMarkerTitle", { bold = true, fg = "#18ddf6" })
hi(0, "NeotestAdapterName", { fg = "#cd9bff" })
hi(0, "NeotestBorder", { fg = "#45248c" })
hi(0, "NeotestDir", { fg = "#18ddf6" })
hi(0, "NeotestExpandMarker", { fg = "#45248c" })
hi(0, "NeotestFailed", { fg = "#ff508d" })
hi(0, "NeotestFile", { fg = "#e0dbff" })
hi(0, "NeotestFocused", { bg = "#244168", fg = "#ffbd5b" })
hi(0, "NeotestIndent", { fg = "#45248c" })
hi(0, "NeotestMarked", { bold = true, fg = "#ffaba9" })
hi(0, "NeotestNamespace", { fg = "#ffbd5b" })
hi(0, "NeotestPassed", { fg = "#007699" })
hi(0, "NeotestRunning", { fg = "#ffbd5b" })
hi(0, "NeotestSkipped", { fg = "#9378f0" })
hi(0, "NeotestTarget", { fg = "#ff508d" })
hi(0, "NeotestTest", { fg = "#ffbd5b" })
hi(0, "NeotestUnknown", { fg = "#9378f0" })
hi(0, "NeotestWatching", { fg = "#cd9bff" })
hi(0, "NeotestWinSelect", { fg = "#7548dd" })
hi(0, "NoiceCursor", { bg = "#cfe3fc", fg = "#5731b0" })
hi(0, "NoiceFormatProgressDone", { bg = "#4f3339", fg = "#e0dbff" })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = "#7548dd" })
hi(0, "Normal", { bg = "#08192e", fg = "#e0dbff" })
hi(0, "NormalFloat", { bg = "#09203a" })
hi(0, "NormalMode", { bold = true, fg = "#e0dbff" })
hi(0, "NormalNC", { bg = "#08192e", fg = "#e0dbff" })
hi(0, "NotifyBackground", { link = "NormalFloat" })
hi(0, "NotifyDEBUGBody", { link = "NormalFloat" })
hi(0, "NotifyDEBUGBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "NotifyDEBUGIcon", { link = "NotifyDEBUGTitle" })
hi(0, "NotifyDEBUGTitle", { fg = "#7548dd" })
hi(0, "NotifyERRORBody", { link = "NormalFloat" })
hi(0, "NotifyERRORBorder", { bg = "#09203a", fg = "#ff508d" })
hi(0, "NotifyERRORIcon", { link = "NotifyERRORTitle" })
hi(0, "NotifyERRORTitle", { fg = "#ff508d" })
hi(0, "NotifyINFOBody", { link = "NormalFloat" })
hi(0, "NotifyINFOBorder", { bg = "#09203a", fg = "#18ddf6" })
hi(0, "NotifyINFOIcon", { link = "NotifyINFOTitle" })
hi(0, "NotifyINFOTitle", { fg = "#18ddf6" })
hi(0, "NotifyTRACEBody", { link = "NormalFloat" })
hi(0, "NotifyTRACEBorder", { bg = "#09203a", fg = "#cd9bff" })
hi(0, "NotifyTRACEIcon", { link = "NotifyTRACETitle" })
hi(0, "NotifyTRACETitle", { fg = "#cd9bff" })
hi(0, "NotifyWARNBody", { link = "NormalFloat" })
hi(0, "NotifyWARNBorder", { bg = "#09203a", fg = "#ffbd5b" })
hi(0, "NotifyWARNIcon", { link = "NotifyWARNTitle" })
hi(0, "NotifyWARNTitle", { fg = "#ffbd5b" })
hi(0, "Number", { fg = "#ffbd5b" })
hi(0, "NvimInternalError", { link = "ErrorMsg" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#7548dd" })
hi(0, "NvimTreeFileDeleted", { fg = "#ff508d" })
hi(0, "NvimTreeFileDirty", { fg = "#ffaba9" })
hi(0, "NvimTreeFileMerge", { fg = "#cd9bff" })
hi(0, "NvimTreeFileNew", { fg = "#18ddf6" })
hi(0, "NvimTreeFileRenamed", { fg = "#007699" })
hi(0, "NvimTreeFileStaged", { fg = "#cd9bff" })
hi(0, "NvimTreeFolderIcon", { fg = "#9378f0" })
hi(0, "NvimTreeFolderName", { fg = "#18ddf6" })
hi(0, "NvimTreeGitDeleted", { fg = "#ff508d" })
hi(0, "NvimTreeGitDirty", { fg = "#ffaba9" })
hi(0, "NvimTreeGitIgnored", { fg = "#7548dd" })
hi(0, "NvimTreeGitMerge", { fg = "#cd9bff" })
hi(0, "NvimTreeGitNew", { fg = "#18ddf6" })
hi(0, "NvimTreeGitRenamed", { fg = "#007699" })
hi(0, "NvimTreeGitStaged", { fg = "#cd9bff" })
hi(0, "NvimTreeImageFile", { fg = "#e0dbff" })
hi(0, "NvimTreeNormal", { link = "Normal" })
hi(0, "NvimTreeOpenedFile", { bg = "#082748", fg = "#e0dbff" })
hi(0, "NvimTreeOpenedFolderName", { link = "NvimTreeFolderName" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#18ddf6" })
hi(0, "NvimTreeSpecialFile", { link = "NvimTreeNormal" })
hi(0, "NvimTreeWindowPicker", { link = "StatusLineTerm" })
hi(0, "Operator", { fg = "#9378f0" })
hi(0, "Pmenu", { bg = "#09203a", fg = "#9378f0" })
hi(0, "PmenuExtra", { bg = "#09203a", fg = "#7548dd" })
hi(0, "PmenuExtraSel", { bg = "#082748", fg = "#9378f0" })
hi(0, "PmenuKind", { bg = "#09203a", fg = "#18ddf6" })
hi(0, "PmenuKindSel", { bg = "#082748", fg = "#9378f0" })
hi(0, "PmenuSbar", { bg = "#09203a" })
hi(0, "PmenuSel", { bg = "#082748", fg = "#e0dbff" })
hi(0, "PmenuThumb", { bg = "#476fa6" })
hi(0, "PounceAccept", { bg = "#3c2850", fg = "#ff508d" })
hi(0, "PounceAcceptBest", { bg = "#4f3339", fg = "#ffbd5b" })
hi(0, "PounceGap", { link = "Search" })
hi(0, "PounceMatch", { link = "Search" })
hi(0, "PreCondit", { fg = "#cd9bff" })
hi(0, "PreProc", { link = "PreCondit" })
hi(0, "Question", { fg = "#ffbd5b" })
hi(0, "QuickFixLine", { fg = "#18ddf6" })
hi(0, "RainbowDelimiterBlue", { fg = "#007699" })
hi(0, "RainbowDelimiterCyan", { fg = "#18ddf6" })
hi(0, "RainbowDelimiterGreen", { fg = "#46c1b1" })
hi(0, "RainbowDelimiterOrange", { fg = "#ffaba9" })
hi(0, "RainbowDelimiterRed", { fg = "#ff508d" })
hi(0, "RainbowDelimiterViolet", { fg = "#cd9bff" })
hi(0, "RainbowDelimiterYellow", { fg = "#ffbd5b" })
hi(0, "RedrawDebugClear", { bg = "#ffb497", fg = "#1c0941" })
hi(0, "RedrawDebugComposed", { bg = "#007c79", fg = "#1c0941" })
hi(0, "RedrawDebugRecompose", { bg = "#de68d9", fg = "#1c0941" })
hi(0, "ReferencesCount", { fg = "#ffaba9" })
hi(0, "ReferencesIcon", { fg = "#ffaba9" })
hi(0, "Removed", { ctermfg = 9, fg = "#ffbab2" })
hi(0, "RenderMarkdownBullet", { fg = "#ffaba9" })
hi(0, "RenderMarkdownChecked", { fg = "#18ddf6" })
hi(0, "RenderMarkdownCode", { bg = "#082748" })
hi(0, "RenderMarkdownCodeInline", { bg = "#082748", fg = "#e0dbff" })
hi(0, "RenderMarkdownDash", { fg = "#7548dd" })
hi(0, "RenderMarkdownH1Bg", { bg = "#24375f" })
hi(0, "RenderMarkdownH2Bg", { bg = "#1b414d" })
hi(0, "RenderMarkdownH3Bg", { bg = "#3e3756" })
hi(0, "RenderMarkdownH4Bg", { bg = "#4f3339" })
hi(0, "RenderMarkdownH5Bg", { bg = "#022f3a" })
hi(0, "RenderMarkdownH6Bg", { bg = "#0d3b4f" })
hi(0, "RenderMarkdownQuote", { fg = "#9378f0" })
hi(0, "RenderMarkdownTableFill", { link = "Conceal" })
hi(0, "RenderMarkdownTableHead", { fg = "#9378f0" })
hi(0, "RenderMarkdownTableRow", { fg = "#9378f0" })
hi(0, "RenderMarkdownUnchecked", { fg = "#9378f0" })
hi(0, "Repeat", { fg = "#007699" })
hi(0, "ReplaceMode", { link = "WarningMsg" })
hi(0, "SagaShadow", { bg = "#082748" })
hi(0, "Search", { bg = "#4f3339", fg = "#e0dbff" })
hi(0, "SelectMode", { link = "ErrorMsg" })
hi(0, "SignAdd", { fg = "#18ddf6" })
hi(0, "SignChange", { fg = "#ffaba9" })
hi(0, "SignColumn", { fg = "#e0dbff" })
hi(0, "SignDelete", { fg = "#ff508d" })
hi(0, "SnacksBackdrop", { bg = "#000000" })
hi(0, "SnacksImageMath", { fg = "#e10083" })
hi(0, "SnacksIndent", { fg = "#2a0d62" })
hi(0, "SnacksIndentBlank", { fg = "#2a0d62" })
hi(0, "SnacksIndentChunk", { fg = "#2a0d62" })
hi(0, "SnacksIndentScope", { fg = "#18ddf6" })
hi(0, "SnacksPickerMatch", { bold = true, fg = "#ffaba9" })
hi(0, "Sneak", { bg = "#de68d9", fg = "#1c0941" })
hi(0, "SneakCurrent", { link = "StatusLineTerm" })
hi(0, "SneakScope", { link = "IncSearch" })
hi(0, "Special", { fg = "#18ddf6" })
hi(0, "SpecialComment", { fg = "#cd9bff" })
hi(0, "SpecialKey", { fg = "#18ddf6" })
hi(0, "SpellBad", { sp = "#908caa", undercurl = true })
hi(0, "SpellCap", { sp = "#908caa", undercurl = true })
hi(0, "SpellLocal", { sp = "#908caa", undercurl = true })
hi(0, "SpellRare", { sp = "#908caa", undercurl = true })
hi(0, "Statement", { bold = true, fg = "#007699" })
hi(0, "StatusLine", { bg = "#09203a", fg = "#9378f0" })
hi(0, "StatusLineNC", { bg = "#0a1d35", fg = "#7548dd" })
hi(0, "StatusLineTerm", { bg = "#007c79", fg = "#1c0941" })
hi(0, "StatusLineTermNC", { bg = "#005557", fg = "#1c0941" })
hi(0, "StorageClass", { fg = "#18ddf6" })
hi(0, "String", { fg = "#ffbd5b" })
hi(0, "Structure", { fg = "#18ddf6" })
hi(0, "Substitute", { link = "IncSearch" })
hi(0, "TabLine", { bg = "#09203a", fg = "#9378f0" })
hi(0, "TabLineFill", { bg = "#09203a" })
hi(0, "TabLineSel", { bg = "#082748", bold = true, fg = "#e0dbff" })
hi(0, "Tag", { fg = "#18ddf6" })
hi(0, "TargetWord", { fg = "#cd9bff" })
hi(0, "TelescopeBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "TelescopeMatching", { fg = "#ffaba9" })
hi(0, "TelescopeNormal", { link = "NormalFloat" })
hi(0, "TelescopePromptNormal", { link = "TelescopeNormal" })
hi(0, "TelescopePromptPrefix", { fg = "#9378f0" })
hi(0, "TelescopeSelection", { bg = "#082748", fg = "#e0dbff" })
hi(0, "TelescopeSelectionCaret", { bg = "#082748", fg = "#ffaba9" })
hi(0, "TelescopeTitle", { bold = true, fg = "#18ddf6" })
hi(0, "TerminalMode", { link = "Operator" })
hi(0, "TerminalNormalMode", { bold = true, fg = "#e0dbff" })
hi(0, "TinyInlineDiagnosticVirtualTextArrow", { bg = "#082748", fg = "#7548dd" })
hi(0, "TinyInlineDiagnosticVirtualTextArrowNoBg", { fg = "#7548dd" })
hi(0, "TinyInlineDiagnosticVirtualTextBg", { bg = "#082748" })
hi(0, "TinyInlineDiagnosticVirtualTextError", { bg = "#321532", fg = "#ff508d" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorCursorLine", { bg = "#082748", fg = "#ff508d" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixError", { bg = "#321532", fg = "#ff508d" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixHint", { bg = "#1d2743", fg = "#ff508d" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixInfo", { bg = "#1c302b", fg = "#ff508d" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorMixWarn", { bg = "#3f251c", fg = "#ff508d" })
hi(0, "TinyInlineDiagnosticVirtualTextErrorNoBg", { fg = "#ff508d" })
hi(0, "TinyInlineDiagnosticVirtualTextHint", { bg = "#1d2743", fg = "#cd9bff" })
hi(0, "TinyInlineDiagnosticVirtualTextHintCursorLine", { bg = "#082748", fg = "#cd9bff" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixError", { bg = "#321532", fg = "#cd9bff" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixHint", { bg = "#1d2743", fg = "#cd9bff" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixInfo", { bg = "#1c302b", fg = "#cd9bff" })
hi(0, "TinyInlineDiagnosticVirtualTextHintMixWarn", { bg = "#3f251c", fg = "#cd9bff" })
hi(0, "TinyInlineDiagnosticVirtualTextHintNoBg", { fg = "#cd9bff" })
hi(0, "TinyInlineDiagnosticVirtualTextInfo", { bg = "#1c302b", fg = "#18ddf6" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoCursorLine", { bg = "#082748", fg = "#18ddf6" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixError", { bg = "#321532", fg = "#18ddf6" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixHint", { bg = "#1d2743", fg = "#18ddf6" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixInfo", { bg = "#1c302b", fg = "#18ddf6" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoMixWarn", { bg = "#3f251c", fg = "#18ddf6" })
hi(0, "TinyInlineDiagnosticVirtualTextInfoNoBg", { fg = "#18ddf6" })
hi(0, "TinyInlineDiagnosticVirtualTextWarn", { bg = "#3f251c", fg = "#ffbd5b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnCursorLine", { bg = "#082748", fg = "#ffbd5b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixError", { bg = "#321532", fg = "#ffbd5b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixHint", { bg = "#1d2743", fg = "#ffbd5b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixInfo", { bg = "#1c302b", fg = "#ffbd5b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnMixWarn", { bg = "#3f251c", fg = "#ffbd5b" })
hi(0, "TinyInlineDiagnosticVirtualTextWarnNoBg", { fg = "#ffbd5b" })
hi(0, "TinyInlineInvDiagnosticVirtualTextError", { bg = "#082748", fg = "#45001e" })
hi(0, "TinyInlineInvDiagnosticVirtualTextErrorNoBg", { fg = "#45001e" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHint", { bg = "#082748", fg = "#351254" })
hi(0, "TinyInlineInvDiagnosticVirtualTextHintNoBg", { fg = "#351254" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfo", { bg = "#082748", fg = "#053238" })
hi(0, "TinyInlineInvDiagnosticVirtualTextInfoNoBg", { fg = "#053238" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarn", { bg = "#082748", fg = "#3e2700" })
hi(0, "TinyInlineInvDiagnosticVirtualTextWarnNoBg", { fg = "#3e2700" })
hi(0, "Title", { bold = true, fg = "#18ddf6" })
hi(0, "Todo", { bg = "#3e3756", fg = "#ffaba9" })
hi(0, "TreesitterContext", { bg = "#082748" })
hi(0, "TreesitterContextLineNumber", { bg = "#082748", fg = "#ffaba9" })
hi(0, "TroubleCount", { bg = "#09203a", fg = "#cd9bff" })
hi(0, "TroubleNormal", { bg = "#09203a", fg = "#e0dbff" })
hi(0, "TroubleText", { fg = "#9378f0" })
hi(0, "Type", { fg = "#18ddf6" })
hi(0, "Underlined", { fg = "#cd9bff", underline = true })
hi(0, "VertSplit", { fg = "#7548dd" })
hi(0, "VimwikiHR", { fg = "#9378f0" })
hi(0, "VimwikiHeader1", { link = "markdownH1" })
hi(0, "VimwikiHeader2", { link = "markdownH2" })
hi(0, "VimwikiHeader3", { link = "markdownH3" })
hi(0, "VimwikiHeader4", { link = "markdownH4" })
hi(0, "VimwikiHeader5", { link = "markdownH5" })
hi(0, "VimwikiHeader6", { link = "markdownH6" })
hi(0, "VimwikiHeaderChar", { fg = "#9378f0" })
hi(0, "VimwikiLink", { link = "markdownUrl" })
hi(0, "VimwikiList", { fg = "#cd9bff" })
hi(0, "VimwikiNoExistsLink", { fg = "#ff508d" })
hi(0, "Visual", { bg = "#1d3054" })
hi(0, "VisualMode", { link = "String" })
hi(0, "WarningMsg", { bold = true, fg = "#ffbd5b" })
hi(0, "WhichKey", { fg = "#cd9bff" })
hi(0, "WhichKeyBorder", { bg = "#09203a", fg = "#7548dd" })
hi(0, "WhichKeyDesc", { fg = "#ffbd5b" })
hi(0, "WhichKeyFloat", { bg = "#09203a" })
hi(0, "WhichKeyGroup", { fg = "#18ddf6" })
hi(0, "WhichKeyIcon", { fg = "#007699" })
hi(0, "WhichKeyIconAzure", { fg = "#007699" })
hi(0, "WhichKeyIconBlue", { fg = "#007699" })
hi(0, "WhichKeyIconCyan", { fg = "#18ddf6" })
hi(0, "WhichKeyIconGreen", { fg = "#46c1b1" })
hi(0, "WhichKeyIconGrey", { fg = "#9378f0" })
hi(0, "WhichKeyIconOrange", { fg = "#ffaba9" })
hi(0, "WhichKeyIconPurple", { fg = "#cd9bff" })
hi(0, "WhichKeyIconRed", { fg = "#ff508d" })
hi(0, "WhichKeyIconYellow", { fg = "#ffbd5b" })
hi(0, "WhichKeySeparator", { fg = "#9378f0" })
hi(0, "WhichKeyValue", { fg = "#ffaba9" })
hi(0, "WildMenu", { link = "IncSearch" })
hi(0, "WinBar", { bg = "#09203a", fg = "#9378f0" })
hi(0, "WinBarNC", { bg = "#0a1d35", fg = "#7548dd" })
hi(0, "WinSeparator", { fg = "#7548dd" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "healthError", { fg = "#ff508d" })
hi(0, "healthSuccess", { fg = "#18ddf6" })
hi(0, "healthWarning", { fg = "#ffbd5b" })
hi(0, "htmlArg", { fg = "#cd9bff" })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlEndTag", { fg = "#9378f0" })
hi(0, "htmlH1", { link = "markdownH1" })
hi(0, "htmlH2", { link = "markdownH2" })
hi(0, "htmlH3", { link = "markdownH3" })
hi(0, "htmlH4", { link = "markdownH4" })
hi(0, "htmlH5", { link = "markdownH5" })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlLink", { link = "markdownUrl" })
hi(0, "htmlTag", { fg = "#9378f0" })
hi(0, "htmlTagN", { fg = "#e0dbff" })
hi(0, "htmlTagName", { fg = "#18ddf6" })
hi(0, "lCursor", { bg = "#cfe3fc", fg = "#1c0941" })
hi(0, "markdownDelimiter", { fg = "#9378f0" })
hi(0, "markdownH1", { bold = true, fg = "#cd9bff" })
hi(0, "markdownH1Delimiter", { link = "markdownH1" })
hi(0, "markdownH2", { bold = true, fg = "#18ddf6" })
hi(0, "markdownH2Delimiter", { link = "markdownH2" })
hi(0, "markdownH3", { bold = true, fg = "#ffaba9" })
hi(0, "markdownH3Delimiter", { link = "markdownH3" })
hi(0, "markdownH4", { bold = true, fg = "#ffbd5b" })
hi(0, "markdownH4Delimiter", { link = "markdownH4" })
hi(0, "markdownH5", { bold = true, fg = "#007699" })
hi(0, "markdownH5Delimiter", { link = "markdownH5" })
hi(0, "markdownH6", { bold = true, fg = "#46c1b1" })
hi(0, "markdownH6Delimiter", { link = "markdownH6" })
hi(0, "markdownLinkText", { link = "markdownUrl" })
hi(0, "markdownUrl", { fg = "#cd9bff", sp = "#c4a7e7", underline = true })
hi(0, "mkdCode", { fg = "#18ddf6", italic = true })
hi(0, "mkdCodeDelimiter", { fg = "#ffaba9" })
hi(0, "mkdCodeEnd", { fg = "#18ddf6" })
hi(0, "mkdCodeStart", { fg = "#18ddf6" })
hi(0, "mkdFootnotes", { fg = "#18ddf6" })
hi(0, "mkdID", { fg = "#18ddf6", underline = true })
hi(0, "mkdInlineURL", { link = "markdownUrl" })
hi(0, "mkdLink", { link = "markdownUrl" })
hi(0, "mkdLinkDef", { link = "markdownUrl" })
hi(0, "mkdListItemLine", { fg = "#e0dbff" })
hi(0, "mkdRule", { fg = "#9378f0" })
hi(0, "mkdURL", { link = "markdownUrl" })
hi(0, "zshDeref", {})
hi(0, "zshFunction", {})
hi(0, "zshOptStart", {})
hi(0, "zshOption", {})
hi(0, "zshSubst", {})
hi(0, "zshTypes", {})
hi(0, "zshVariableDef", {})

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#26233a"
g.terminal_color_1 = "#eb6f92"
g.terminal_color_2 = "#31748f"
g.terminal_color_3 = "#f6c177"
g.terminal_color_4 = "#9ccfd8"
g.terminal_color_5 = "#c4a7e7"
g.terminal_color_6 = "#ebbcba"
g.terminal_color_7 = "#e0def4"
g.terminal_color_8 = "#908caa"
g.terminal_color_9 = "#eb6f92"
g.terminal_color_10 = "#31748f"
g.terminal_color_11 = "#f6c177"
g.terminal_color_12 = "#9ccfd8"
g.terminal_color_13 = "#c4a7e7"
g.terminal_color_14 = "#ebbcba"
g.terminal_color_15 = "#e0def4"
