return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   opts = {
  --     -- @type lspconfig.options
  --     servers = {
  --       emmet_ls = {
  --         filetypes = {
  --           "astro",
  --           "blade",
  --           "css",
  --           "eruby",
  --           "html",
  --           "htmldjango",
  --           "javascriptreact",
  --           "less",
  --           "pug",
  --           "sass",
  --           "scss",
  --           "svelte",
  --           "typescriptreact",
  --           "vue",
  --         },
  --         init_options = {
  --           includeLanguages = {
  --             blade = "html",
  --           },
  --           html = {
  --             options = {
  --               -- For possible options, see: https://github.com/emmetio/emmet/blob/master/src/config.ts#L79-L267
  --               ["bem.enabled"] = true,
  --             },
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
